"use client";

import { useEffect, useState } from "react";
import { consoleApi } from "@/lib/consoleApi";
import { ConsoleAlert, ConsoleButton, ConsoleCard, ConsoleIcon, ConsoleInput, ConsolePageHeader, ConsoleSelect, ConsoleTextarea } from "@/features/console/ui";

type Setting = { key: string; value: Record<string, unknown>; version: number; updatedAt: string };
type Field = { key: string; label: string; help?: string; type: "text" | "number" | "boolean" | "textarea" | "language" | "timezone" | "types" };
const sections: Record<string, { label: string; description: string; fields: Field[] }> = {
  site: { label: "站点信息", description: "网站对外展示的组织名称与备案联系信息。", fields: [{ key: "groupName", label: "课题组名称", type: "text" }, { key: "contact", label: "联系信息", type: "text" }, { key: "icp", label: "ICP备案号", type: "text" }] },
  locale: { label: "语言与时区", description: "控制平台默认语言、日期和时间的显示方式。", fields: [{ key: "defaultLanguage", label: "默认语言", type: "language" }, { key: "timezone", label: "默认时区", type: "timezone" }] },
  security: { label: "安全设置", description: "设置登录会话的有效期限。", fields: [{ key: "sessionDurationHours", label: "会话有效时间（小时）", help: "建议保持在 24–168 小时之间。", type: "number" }] },
  monitor: { label: "监控设置", description: "控制设备多长时间未上报后显示为离线。", fields: [{ key: "offlineThresholdSeconds", label: "离线阈值（秒）", type: "number" }] },
  procurement: { label: "采购设置", description: "控制采购编号格式与流程是否可用。", fields: [{ key: "numberPrefix", label: "采购编号前缀", type: "text" }, { key: "workflowEnabled", label: "启用采购工作流", type: "boolean" }] },
  media: { label: "媒体设置", description: "限制单个文件大小与允许上传的文件格式。", fields: [{ key: "maxUploadBytes", label: "单文件上限（字节）", help: "20 MB = 20971520 字节。", type: "number" }, { key: "allowedTypes", label: "允许的 MIME 类型", help: "使用英文逗号分隔。", type: "types" }] },
  maintenance: { label: "维护模式", description: "开启后向访问者显示维护提示。", fields: [{ key: "enabled", label: "开启维护模式", type: "boolean" }, { key: "message", label: "维护提示", type: "textarea" }] },
};

function StructuredField({ field, value, onChange }: { field: Field; value: unknown; onChange: (value: unknown) => void }) {
  if (field.type === "boolean") return <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-slate-200 bg-slate-50 px-4 py-3"><input checked={Boolean(value)} className="mt-0.5 size-4" onChange={(event) => onChange(event.target.checked)} type="checkbox"/><span><span className="block text-sm font-semibold text-slate-800">{field.label}</span>{field.help ? <span className="mt-1 block text-xs text-slate-500">{field.help}</span> : null}</span></label>;
  const label = <><span className="text-sm font-semibold text-slate-700">{field.label}</span>{field.help ? <span className="mt-1 block text-xs font-normal text-slate-500">{field.help}</span> : null}</>;
  if (field.type === "textarea") return <label className="block">{label}<ConsoleTextarea className="mt-2" onChange={(event) => onChange(event.target.value)} value={String(value ?? "")}/></label>;
  if (field.type === "language") return <label className="block">{label}<ConsoleSelect className="mt-2" onChange={(event) => onChange(event.target.value)} value={String(value ?? "zh")}><option value="zh">简体中文</option><option value="en">English</option></ConsoleSelect></label>;
  if (field.type === "timezone") return <label className="block">{label}<ConsoleSelect className="mt-2" onChange={(event) => onChange(event.target.value)} value={String(value ?? "Asia/Shanghai")}><option value="Asia/Shanghai">Asia/Shanghai (UTC+8)</option><option value="UTC">UTC</option></ConsoleSelect></label>;
  if (field.type === "types") return <label className="block">{label}<ConsoleInput className="mt-2 font-mono text-xs" onChange={(event) => onChange(event.target.value.split(",").map((item) => item.trim()).filter(Boolean))} value={Array.isArray(value) ? value.join(", ") : ""}/></label>;
  return <label className="block">{label}<ConsoleInput className="mt-2" min={field.type === "number" ? 1 : undefined} onChange={(event) => onChange(field.type === "number" ? Number(event.target.value) : event.target.value)} type={field.type} value={String(value ?? "")}/></label>;
}

export function SettingsConsole() {
  const [settings, setSettings] = useState<Setting[]>([]); const [active, setActive] = useState("site"); const [value, setValue] = useState<Record<string, unknown>>({}); const [raw, setRaw] = useState("{}"); const [advanced, setAdvanced] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { consoleApi<{ settings: Setting[] }>("/api/settings").then((result) => { setSettings(result.settings); const first = result.settings.find((item) => item.key === "site") || result.settings[0]; if (first) { setActive(first.key); setValue(first.value); setRaw(JSON.stringify(first.value, null, 2)); } }).catch((cause) => setError(cause.message)); }, []);
  const current = settings.find((setting) => setting.key === active); const section = sections[active];
  function select(key: string) { const next = settings.find((setting) => setting.key === key); if (!next) return; setActive(key); setValue(next.value); setRaw(JSON.stringify(next.value, null, 2)); setAdvanced(false); setError(""); setMessage(""); }
  function setField(key: string, next: unknown) { setValue((currentValue) => { const updated = { ...currentValue, [key]: next }; setRaw(JSON.stringify(updated, null, 2)); return updated; }); setMessage(""); }
  function formatRaw() { try { const parsed = JSON.parse(raw) as Record<string, unknown>; setRaw(JSON.stringify(parsed, null, 2)); setValue(parsed); setError(""); } catch { setError("JSON 格式有误，请检查逗号、引号与括号。"); } }
  async function save() { if (!current) return; let nextValue = value; if (advanced) { try { nextValue = JSON.parse(raw) as Record<string, unknown>; } catch { setError("设置内容必须是合法 JSON。"); return; } } setBusy(true); setError(""); setMessage(""); try { const next = await consoleApi<Setting>(`/api/settings/${current.key}`, { method: "PUT", body: JSON.stringify({ value: nextValue, version: current.version }) }); setSettings((all) => all.map((item) => item.key === next.key ? next : item)); setValue(next.value); setRaw(JSON.stringify(next.value, null, 2)); setMessage("系统设置已保存。"); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  return <section><ConsolePageHeader description="使用结构化表单维护平台运行参数；原始 JSON 已收纳至高级模式。" eyebrow="平台运行参数" title="系统设置"/>
    <div className="mt-5 space-y-3">{error ? <ConsoleAlert tone="danger">{error}</ConsoleAlert> : null}{message ? <ConsoleAlert tone="success">{message}</ConsoleAlert> : null}</div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><nav aria-label="设置分类" className="h-fit rounded-xl border border-slate-200 bg-white p-2 shadow-sm">{settings.map((setting) => <button aria-current={active === setting.key ? "page" : undefined} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm ${active === setting.key ? "bg-cyan-50 font-semibold text-cyan-900" : "text-slate-600 hover:bg-slate-50 hover:text-slate-900"}`} key={setting.key} onClick={() => select(setting.key)}>{sections[setting.key]?.label ?? setting.key}<span className="text-[10px] text-slate-400">v{setting.version}</span></button>)}</nav>
      {current && section ? <ConsoleCard className="overflow-hidden"><header className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-semibold text-slate-950">{section.label}</h2><p className="mt-1 text-sm text-slate-500">{section.description}</p><p className="mt-2 text-[11px] text-slate-400">上次修改 {new Date(current.updatedAt).toLocaleString("zh-CN")}</p></div><button aria-expanded={advanced} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-100 hover:text-slate-800" onClick={() => setAdvanced((shown) => !shown)}><ConsoleIcon name="settings"/>高级模式</button></header>
        <div className="p-5">{advanced ? <div><ConsoleAlert tone="warning" title="谨慎编辑原始设置">高级模式会直接保存 JSON。错误的字段名或值可能影响平台功能，请仅在明确了解结构时使用。</ConsoleAlert><div className="mt-4 flex justify-end"><ConsoleButton onClick={formatRaw} size="sm">格式化 JSON</ConsoleButton></div><ConsoleTextarea aria-label="原始 JSON 设置" className="mt-3 min-h-[360px] bg-slate-950 font-mono text-xs leading-6 text-slate-100" onChange={(event) => { setRaw(event.target.value); setMessage(""); }} spellCheck={false} value={raw}/></div> : <div className="grid gap-5 sm:grid-cols-2">{section.fields.map((field) => <div className={field.type === "textarea" || field.type === "types" || field.type === "boolean" ? "sm:col-span-2" : ""} key={field.key}><StructuredField field={field} onChange={(next) => setField(field.key, next)} value={value[field.key]}/></div>)}</div>}</div>
        <footer className="flex justify-end border-t border-slate-100 bg-slate-50/60 px-5 py-4"><ConsoleButton disabled={busy} onClick={() => void save()} variant="primary">{busy ? "保存中…" : "保存设置"}</ConsoleButton></footer></ConsoleCard> : <ConsoleCard className="p-8 text-sm text-slate-500">正在加载系统设置…</ConsoleCard>}
    </div>
  </section>;
}
