DELETE FROM procurement_catalog_items
WHERE sku IN (
  'BOLT-SHCS-M3X8',
  'BOLT-SHCS-M3X12',
  'BOLT-SHCS-M4X10',
  'BOLT-SHCS-M4X16',
  'BOLT-SHCS-M5X20',
  'BOLT-SHCS-M6X20',
  'NUT-HEX-M3',
  'NUT-HEX-M4',
  'NUT-HEX-M5',
  'NUT-HEX-M6',
  'WASHER-FLAT-M3',
  'WASHER-FLAT-M4',
  'WASHER-FLAT-M5',
  'WASHER-FLAT-M6',
  'ROD-THREADED-M5',
  'ROD-THREADED-M6'
);
