"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { consoleApi, ConsoleApiError } from "@/lib/consoleApi";

type Profile={version:number;username:string;memberCategory:string;nameZh:string;nameEn:string;titleZh:string;titleEn:string;email:string;phone:string;bioZh:string;bioEn:string;researchInterestsZh:string;researchInterestsEn:string;homepageUrl:string;githubUrl:string;avatarAssetId:string|null;publicFields:string[]};
const fields=[['avatar','头像'],['name_zh','中文姓名'],['name_en','英文姓名'],['title','职称'],['bio','个人简介'],['research_interests','研究方向'],['email','邮箱'],['homepage','个人主页'],['github','GitHub']];
const input="mt-1 w-full border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100";
const tabs=[['profile','个人资料'],['public','公开展示'],['security','账号安全']] as const;

export function ProfileConsole({mustChangePassword}:{mustChangePassword:boolean}){const params=useSearchParams(),router=useRouter();const initial=mustChangePassword?'security':params.get('section')==='security'?'security':params.get('section')==='public'?'public':'profile';const[tab,setTab]=useState<string>(initial),[profile,setProfile]=useState<Profile|null>(null),[draft,setDraft]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
useEffect(()=>{consoleApi<Profile>('/api/profile').then(v=>{setProfile(v);setDraft(v)}).catch(e=>setError(e.message))},[]);const visible=useMemo(()=>new Set(draft?.publicFields??[]),[draft]);const update=(key:keyof Profile,value:Profile[keyof Profile])=>setDraft(d=>d?{...d,[key]:value}:d);const switchTab=(next:string)=>{if(mustChangePassword&&next!=='security')return;setTab(next);router.replace(`/console/profile?section=${next}`,{scroll:false})};
async function save(){if(!draft)return;setBusy(true);setError('');setMessage('');try{const saved=await consoleApi<Profile>('/api/profile',{method:'PUT',body:JSON.stringify(draft)});setProfile(saved);setDraft(saved);setMessage('个人资料已保存，并同步到公开成员页。')}catch(e){setError(e instanceof ConsoleApiError&&e.code==='VERSION_CONFLICT'?'资料已被其他操作更新，请重新加载页面后再编辑。':(e as Error).message)}finally{setBusy(false)}}
async function changePassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),next=String(data.get('newPassword')??''),confirm=String(data.get('confirmPassword')??'');if(next!==confirm){setError('两次输入的新密码不一致。');return}setBusy(true);setError('');try{await consoleApi('/api/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:data.get('currentPassword'),newPassword:next})});setMessage('密码已修改，其他登录会话已失效。');event.currentTarget.reset();router.refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
if(mustChangePassword&&!draft)return <section className="max-w-xl"><p className="text-sm font-semibold text-cyan-800">账号安全</p><h1 className="mt-1 font-serif text-3xl font-bold text-blue-950">首次登录修改密码</h1>{error?<p className="mt-5 border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">临时密码账号只能使用账号安全功能。</p>:null}<form className="mt-7 space-y-5" onSubmit={changePassword}><label className="block text-sm font-medium">当前临时密码<input autoComplete="current-password" className={input} name="currentPassword" required type="password"/></label><label className="block text-sm font-medium">新密码<input autoComplete="new-password" className={input} name="newPassword" required type="password"/><span className="mt-2 block text-xs text-slate-500">至少 12 位，包含大写字母、小写字母、数字和特殊字符。</span></label><label className="block text-sm font-medium">确认新密码<input autoComplete="new-password" className={input} name="confirmPassword" required type="password"/></label><button className="bg-blue-950 px-5 py-2.5 text-sm font-semibold text-white" disabled={busy}>{busy?'修改中...':'修改密码并继续'}</button></form></section>;if(error&&!draft)return <div className="border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}</div>;if(!draft)return <p className="text-sm text-slate-600">正在加载个人资料...</p>;
return <section className="max-w-5xl"><div><p className="text-sm font-semibold text-cyan-800">账号与公开身份</p><h1 className="mt-1 font-serif text-3xl font-bold text-blue-950">个人资料</h1></div>{mustChangePassword?<div className="mt-6 border-l-4 border-amber-500 bg-amber-50 p-4 text-sm text-amber-900">当前账号使用临时密码，请先完成密码修改。</div>:null}<div className="mt-7 flex border-b border-slate-200" role="tablist">{tabs.map(([key,label])=><button className={`px-4 py-3 text-sm font-semibold ${tab===key?'border-b-2 border-cyan-700 text-cyan-800':'text-slate-600'} ${mustChangePassword&&key!=='security'?'cursor-not-allowed opacity-40':''}`} disabled={mustChangePassword&&key!=='security'} key={key} onClick={()=>switchTab(key)}>{label}</button>)}</div>{message?<p className="mt-5 border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>:null}{error&&draft?<p className="mt-5 border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}
{tab==='profile'?<div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">用户名<input className={`${input} bg-slate-100`} disabled value={draft.username}/></label><label className="text-sm font-medium">成员类别<input className={`${input} bg-slate-100`} disabled value={draft.memberCategory}/></label>{[['nameZh','中文姓名'],['nameEn','英文姓名'],['titleZh','中文职称'],['titleEn','英文职称'],['email','邮箱'],['phone','手机号（仅内部）'],['homepageUrl','个人主页'],['githubUrl','GitHub']] .map(([key,label])=><label className="text-sm font-medium" key={key}>{label}<input className={input} value={String(draft[key as keyof Profile]??'')} onChange={e=>update(key as keyof Profile,e.target.value)}/></label>)}{[['bioZh','中文简介'],['bioEn','英文简介'],['researchInterestsZh','中文研究方向'],['researchInterestsEn','英文研究方向']].map(([key,label])=><label className="text-sm font-medium sm:col-span-2" key={key}>{label}<textarea className={`${input} min-h-28`} value={String(draft[key as keyof Profile]??'')} onChange={e=>update(key as keyof Profile,e.target.value)}/></label>)}<div className="sm:col-span-2"><button className="bg-blue-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={busy||JSON.stringify(profile)===JSON.stringify(draft)} onClick={save}>{busy?'保存中...':'保存资料'}</button></div></div>:null}
{tab==='public'?<div className="mt-7 grid gap-8 lg:grid-cols-[1fr_1.2fr]"><div className="space-y-3">{fields.map(([key,label])=><label className="flex items-center justify-between border-b border-slate-200 py-3 text-sm" key={key}><span>{label}</span><input checked={visible.has(key)} type="checkbox" onChange={e=>update('publicFields',e.target.checked?[...draft.publicFields,key]:draft.publicFields.filter(v=>v!==key))}/></label>)}<button className="mt-4 bg-blue-950 px-5 py-2.5 text-sm font-semibold text-white" disabled={busy} onClick={save}>保存公开设置</button></div><article className="border border-slate-200 bg-white p-6"><p className="text-xs font-bold text-cyan-800">公开成员页预览</p><h2 className="mt-3 font-serif text-2xl text-blue-950">{visible.has('name_zh')&&draft.nameZh?draft.nameZh:'课题组成员'} <span className="text-base text-slate-500">/ {visible.has('name_en')&&draft.nameEn?draft.nameEn:'Lab Member'}</span></h2>{visible.has('title')?<p className="mt-2 text-sm text-slate-600">{draft.titleZh} · {draft.titleEn}</p>:null}{visible.has('bio')?<p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-700">{draft.bioZh||draft.bioEn}</p>:null}{visible.has('research_interests')?<p className="mt-5 text-sm"><b>研究方向：</b>{draft.researchInterestsZh||draft.researchInterestsEn}</p>:null}{visible.has('email')&&draft.email?<p className="mt-5 text-sm text-cyan-800">{draft.email}</p>:null}</article></div>:null}
{tab==='security'?<form className="mt-7 max-w-xl space-y-5" onSubmit={changePassword}><label className="block text-sm font-medium">当前密码<input autoComplete="current-password" className={input} name="currentPassword" required type="password"/></label><label className="block text-sm font-medium">新密码<input autoComplete="new-password" className={input} name="newPassword" required type="password"/><span className="mt-2 block text-xs text-slate-500">至少 12 位，包含大写字母、小写字母、数字和特殊字符。</span></label><label className="block text-sm font-medium">确认新密码<input autoComplete="new-password" className={input} name="confirmPassword" required type="password"/></label><button className="bg-blue-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={busy}>{busy?'修改中...':'修改密码'}</button></form>:null}</section>}
