"use client";

import Link from "next/link";
import { useLanguage } from "./LanguageProvider";
import { getLocalizedText, isExternalHref, normalizeInternalHref } from "./i18n";

function MonitorPreview({ preview, status }: { preview: any; status: unknown }) {
  const { locale } = useLanguage();
  const statusText = preview.summary.statusText || getLocalizedText(status, locale) || (locale === "zh" ? "监控数据暂不可用" : "Monitor data unavailable");
  return <section className="border border-slate-200 bg-white shadow-sm"><div className="flex items-start justify-between gap-4 border-b border-slate-200 p-5"><div><span className="public-kicker">{locale === "zh" ? "实验平台状态" : "PLATFORM STATUS"}</span><p className="mt-2 text-sm text-on-surface-variant">{statusText}</p></div><Link className="text-sm font-semibold text-secondary" href="/monitor">{locale === "zh" ? "进入监控" : "Open Monitor"}</Link></div><div className="grid min-h-[260px] content-start gap-3 bg-slate-950 p-5 sm:grid-cols-2">{preview.devices.length ? preview.devices.map((device: any) => <article className="border border-white/15 bg-white/5 p-4 text-white" key={device.code || device.displayName}><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{device.displayName || device.code}</h3><span className={device.isOnline ? "h-2.5 w-2.5 rounded-full bg-emerald-400" : "h-2.5 w-2.5 rounded-full bg-slate-500"}/></div><p className="mt-2 text-xs text-slate-300">{device.statusLabel || (device.isOnline ? (locale === "zh" ? "在线" : "Online") : (locale === "zh" ? "离线" : "Offline"))}</p></article>) : <div className="col-span-full grid min-h-[220px] place-items-center text-center text-sm text-slate-300">{locale === "zh" ? "当前没有公开设备状态" : "No public device status available"}</div>}</div></section>;
}

export function HomePage({ data }: { data: any }) {
  const { locale } = useLanguage();
  const home = data.home ?? {}, hero = home.hero ?? {}, sections = home.sections ?? {};
  const featured = (data.research?.publications ?? []).find((item: any) => item.id === home.featuredPublicationId);
  const newsItems = (home.newsPreviewIds ?? []).map((id: string) => (data.news?.items ?? []).find((item: any) => item.id === id)).filter(Boolean);
  return <main>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-6 lg:grid-cols-12 lg:px-8 lg:py-20"><div className="self-center lg:col-span-7"><span className="public-kicker mb-5 block">{getLocalizedText(hero.eyebrow, locale)}</span><h1 className="font-serif text-4xl font-semibold leading-tight text-primary sm:text-6xl">{getLocalizedText(hero.title, locale)} <span className="italic text-secondary">{getLocalizedText(hero.highlight, locale)}</span></h1><p className="public-copy mt-7 max-w-2xl">{getLocalizedText(hero.description, locale)}</p><div className="mt-8 flex flex-wrap gap-3">{(hero.actions ?? []).map((action: any, index: number) => { const href = normalizeInternalHref(action.href); const className = action.variant === "secondary" ? "border border-primary px-5 py-3 font-semibold text-primary" : "bg-primary px-5 py-3 font-semibold text-white"; return isExternalHref(href) ? <a className={className} href={href} key={index}>{getLocalizedText(action.label, locale)}</a> : <Link className={className} href={href} key={index}>{getLocalizedText(action.label, locale)}</Link>; })}</div></div><div className="lg:col-span-5"><MonitorPreview preview={data.monitorPreview} status={hero.status}/></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8"><div className="mb-10 flex items-end justify-between"><h2 className="font-serif text-3xl font-semibold text-primary">{getLocalizedText(sections.researchAreasTitle, locale)}</h2><Link className="text-sm font-semibold text-secondary" href="/research">{getLocalizedText(sections.researchAreasCta, locale)}</Link></div><div className="grid gap-6 md:grid-cols-3">{(home.researchAreas ?? []).map((item: any, index: number) => <article className="border border-slate-200 bg-white p-7 shadow-sm" key={index}><span className="public-kicker">{item.icon || "R-NAV"}</span><h3 className="mt-4 font-serif text-2xl font-semibold text-primary">{getLocalizedText(item.title, locale)}</h3><p className="mt-3 leading-7 text-on-surface-variant">{getLocalizedText(item.description, locale)}</p><Link className="mt-5 inline-block font-semibold text-secondary" href={normalizeInternalHref(item.href || "/research")}>{getLocalizedText(item.label, locale)}</Link></article>)}</div></section>
    <section className="bg-surface-container-low px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><section><div className="mb-7 flex items-end justify-between"><div><span className="public-kicker">{getLocalizedText(sections.featuredEyebrow, locale)}</span><h2 className="mt-2 font-serif text-3xl text-primary">{getLocalizedText(sections.featuredTitle, locale)}</h2></div><Link className="text-sm underline" href="/research">{getLocalizedText(sections.archiveLabel, locale)}</Link></div>{featured ? <article className="border border-slate-200 bg-white p-7 shadow-sm"><span className="public-kicker">{getLocalizedText(home.featuredPublication?.badge, locale)}</span><h3 className="mt-4 text-2xl font-semibold text-primary">{getLocalizedText(featured.title, locale)}</h3><p className="mt-3 italic text-on-surface-variant">{getLocalizedText(home.featuredPublication?.authors, locale) || (featured.authors ?? []).map((author: any) => getLocalizedText(author.name, locale)).join(", ")}</p><div className="mt-6 flex flex-wrap gap-4 border-t border-slate-200 pt-5">{(home.featuredPublication?.links ?? []).map((link: any, index: number) => isExternalHref(link.href) ? <a className="font-semibold text-secondary" href={normalizeInternalHref(link.href)} key={index}>{getLocalizedText(link.label, locale)}</a> : <Link className="font-semibold text-secondary" href={normalizeInternalHref(link.href)} key={index}>{getLocalizedText(link.label, locale)}</Link>)}</div></article> : <p className="border border-slate-200 bg-white p-7 text-on-surface-variant">{locale === "zh" ? "暂无代表论文" : "No featured publication"}</p>}</section><section><div className="mb-7 flex items-end justify-between"><div><span className="public-kicker">{getLocalizedText(sections.newsEyebrow, locale)}</span><h2 className="mt-2 font-serif text-3xl text-primary">{getLocalizedText(sections.newsTitle, locale)}</h2></div><Link className="text-sm underline" href="/news">{locale === "zh" ? "全部新闻" : "All News"}</Link></div><div className="divide-y divide-slate-200">{newsItems.length ? newsItems.map((item: any) => <article className="grid gap-3 py-5 sm:grid-cols-[110px_1fr]" key={item.id}><time className="text-sm text-slate-500">{getLocalizedText(item.date, locale)}</time><div><Link href="/news"><h3 className="text-lg font-semibold text-primary hover:text-secondary">{getLocalizedText(item.title, locale)}</h3></Link><p className="mt-1 text-sm leading-6 text-on-surface-variant">{getLocalizedText(item.excerpt, locale) || getLocalizedText(item.description, locale)}</p></div></article>) : <p className="border border-slate-200 bg-white p-7 text-on-surface-variant">{locale === "zh" ? "暂无新闻预览" : "No news preview"}</p>}</div></section></div></section>
  </main>;
}
