"use client";

import Link from "next/link";
import { PageHeader } from "./PageHeader";
import { useLanguage } from "./LanguageProvider";
import { getLocalizedText } from "./i18n";

function MemberCard({ member }: { member: any }) { const { locale } = useLanguage(); return <article className="border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-5">{member.image?.src ? <img className="h-24 w-24 shrink-0 object-cover" src={member.image.src} alt={member.image.alt || getLocalizedText(member.name, locale)} /> : <div className="h-24 w-24 shrink-0 bg-slate-200"/>}<div><h3 className="font-serif text-xl font-semibold text-primary">{getLocalizedText(member.name, locale)}</h3><p className="mt-1 text-sm text-secondary">{getLocalizedText(member.role, locale) || getLocalizedText(member.degree, locale)}</p><p className="mt-3 text-sm leading-6 text-on-surface-variant">{getLocalizedText(member.bio, locale) || getLocalizedText(member.research, locale) || getLocalizedText(member.focus, locale)}</p></div></div></article>; }
export function TeamPage({ data }: { data: any }) { const { locale } = useLanguage(); const groups = [["faculty", data.advisors], ["postdocs", data.postdocs], ["phd", data.phdStudents], ["master", data.masterStudents], ["undergrad", data.undergraduateStudents], ["alumni", data.alumni]]; return <main className="mx-auto max-w-7xl px-5 pb-20 pt-12 sm:px-6 lg:px-8"><PageHeader header={data.header}/><div className="space-y-16">{groups.map(([key, members]: any) => members?.length ? <section key={key}><h2 className="mb-7 border-l-4 border-cyan-600 pl-4 font-serif text-3xl text-primary">{getLocalizedText(data.sectionTitles?.[key], locale)}</h2><div className="grid gap-6 md:grid-cols-2">{members.map((member: any) => <MemberCard key={member.slug} member={member}/>)}</div></section> : null)}</div><section className="mt-20 bg-primary p-9 text-white sm:flex sm:items-center sm:justify-between"><div><h2 className="font-serif text-3xl">{getLocalizedText(data.recruitment?.title, locale)}</h2><p className="mt-3 max-w-2xl text-blue-100">{getLocalizedText(data.recruitment?.description, locale)}</p></div><Link className="mt-6 inline-block bg-cyan-300 px-5 py-3 font-semibold text-primary sm:mt-0" href={data.recruitment?.buttonHref || "/contact"}>{getLocalizedText(data.recruitment?.buttonLabel, locale)}</Link></section></main>; }
