"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { addProcurementComment, createProcurement, loadProcurement, loadProcurements, transitionProcurement } from "./api";
import { availableActions, procurementCapabilities, type ProcurementStatus } from "./model";

type Props = { permissions: string[]; userId: string };
type RequestSummary = { id: string; requestNo: string; requesterId: string; requesterName: string; title: string; reason: string; status: ProcurementStatus; totalEstimatedAmount: number; createdAt: string; updatedAt: string };
type ItemDraft = { itemName: string; spec: string; quantity: number; estimatedUnitPrice: number; vendor: string; url: string; remark: string };
type ProcurementItem = { id: string; item_name: string; spec: string; quantity: number; estimated_unit_price: number | null };
type ProcurementDetail = { id: string; request_no?: string; requestNo?: string; requester_id?: string; requesterId?: string; title: string; reason: string; status: ProcurementStatus; items?: ProcurementItem[] };

const field = "mt-1 w-full border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 focus:border-cyan-700 focus:outline-none";
const primary = "bg-blue-950 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400";
const secondary = "border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:border-cyan-700";
const statusLabels: Record<ProcurementStatus, string> = { draft: "草稿", submitted: "待审批", approved: "已批准", rejected: "已驳回", purchasing: "采购中", purchased: "已采购", received: "已到货", closed: "已关闭", cancelled: "已撤回" };
const emptyItem = (): ItemDraft => ({ itemName: "", spec: "", quantity: 1, estimatedUnitPrice: 0, vendor: "", url: "", remark: "" });

export function ProcurementConsole({ permissions, userId }: Props) {
  const capability = procurementCapabilities(permissions);
  const [scope, setScope] = useState<"mine" | "all">("mine"); const [requests, setRequests] = useState<RequestSummary[]>([]); const [selected, setSelected] = useState<ProcurementDetail | null>(null);
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false);
  const [title, setTitle] = useState(""); const [reason, setReason] = useState(""); const [items, setItems] = useState<ItemDraft[]>([emptyItem()]); const [comment, setComment] = useState(""); const [note, setNote] = useState("");

  const refresh = useCallback(async (nextScope = scope) => { setLoading(true); try { setRequests(await loadProcurements(nextScope) as RequestSummary[]); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "无法加载采购申请。"); } finally { setLoading(false); } }, [scope]);
  useEffect(() => { void refresh(); }, [refresh]);

  async function openRequest(id: string) { try { setSelected(await loadProcurement(id) as ProcurementDetail); setNote(""); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "无法加载申请详情。"); } }
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); try { await action(); await refresh(); if (selected?.id) setSelected(await loadProcurement(selected.id) as ProcurementDetail); setMessage(success); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败。"); return false; } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); const succeeded = await run(() => createProcurement({ title, reason, items: items.map((item) => ({ ...item, estimatedUnitPrice: item.estimatedUnitPrice || null, vendor: item.vendor || null, url: item.url || null, remark: item.remark || null })) }), "采购申请已提交。"); if (succeeded) { setTitle(""); setReason(""); setItems([emptyItem()]); setShowForm(false); } }
  const actions = useMemo(() => selected ? availableActions(selected.status, capability, selected.requester_id === userId || selected.requesterId === userId) : [], [capability, selected, userId]);

  return <section aria-labelledby="procurement-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-300 pb-5"><div><p className="text-sm font-semibold text-cyan-800">内部业务</p><h1 className="mt-2 font-serif text-3xl font-bold text-slate-950" id="procurement-heading">零件采购</h1><p className="mt-2 text-sm text-slate-600">提交采购申请，并按权限完成审批、采购、到货和关闭流程</p></div>{capability.create ? <button className={primary} onClick={() => setShowForm(true)} type="button">新建申请</button> : null}</header>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex border border-slate-300 bg-white p-1"><button className={`px-3 py-2 text-sm font-semibold ${scope === "mine" ? "bg-blue-950 text-white" : "text-slate-600"}`} onClick={() => { setScope("mine"); setSelected(null); }} type="button">我的申请</button>{capability.readAll ? <button className={`px-3 py-2 text-sm font-semibold ${scope === "all" ? "bg-blue-950 text-white" : "text-slate-600"}`} onClick={() => { setScope("all"); setSelected(null); }} type="button">全部申请</button> : null}</div><button className={secondary} onClick={() => void refresh()} type="button">刷新</button></div>
    {message ? <p className="mt-4 border border-cyan-200 bg-white px-4 py-3 text-sm text-slate-700" role="status">{message}</p> : null}
    {showForm ? <form className="mt-6 border border-slate-200 bg-white p-5" onSubmit={submit}><div className="flex items-center justify-between"><h2 className="font-bold">新建采购申请</h2><button className="text-sm text-slate-600 underline" onClick={() => setShowForm(false)} type="button">关闭</button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">申请标题<input className={field} required value={title} onChange={(event) => setTitle(event.target.value)}/></label><label className="text-sm font-semibold">申请理由<input className={field} required value={reason} onChange={(event) => setReason(event.target.value)}/></label></div><div className="mt-5 space-y-4">{items.map((item, index) => <fieldset className="grid gap-3 border border-slate-200 p-4 md:grid-cols-3" key={index}><legend className="px-2 text-sm font-bold">零件 {index + 1}</legend><label className="text-sm">名称<input className={field} required value={item.itemName} onChange={(event) => setItems(items.map((value, itemIndex) => itemIndex === index ? { ...value, itemName: event.target.value } : value))}/></label><label className="text-sm">规格<input className={field} value={item.spec} onChange={(event) => setItems(items.map((value, itemIndex) => itemIndex === index ? { ...value, spec: event.target.value } : value))}/></label><label className="text-sm">数量<input className={field} min="0.01" step="0.01" type="number" value={item.quantity} onChange={(event) => setItems(items.map((value, itemIndex) => itemIndex === index ? { ...value, quantity: Number(event.target.value) } : value))}/></label><label className="text-sm">预计单价<input className={field} min="0" step="0.01" type="number" value={item.estimatedUnitPrice} onChange={(event) => setItems(items.map((value, itemIndex) => itemIndex === index ? { ...value, estimatedUnitPrice: Number(event.target.value) } : value))}/></label><label className="text-sm">供应商<input className={field} value={item.vendor} onChange={(event) => setItems(items.map((value, itemIndex) => itemIndex === index ? { ...value, vendor: event.target.value } : value))}/></label><label className="text-sm">链接<input className={field} type="url" value={item.url} onChange={(event) => setItems(items.map((value, itemIndex) => itemIndex === index ? { ...value, url: event.target.value } : value))}/></label>{items.length > 1 ? <button className="text-left text-sm font-semibold text-red-700" onClick={() => setItems(items.filter((_, itemIndex) => itemIndex !== index))} type="button">删除零件</button> : null}</fieldset>)}</div><div className="mt-4 flex gap-3"><button className={secondary} onClick={() => setItems([...items, emptyItem()])} type="button">添加零件</button><button className={primary} disabled={busy} type="submit">提交申请</button></div></form> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]"><div className="overflow-x-auto border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">申请</th><th className="px-4 py-3">申请人</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">预计金额</th></tr></thead><tbody className="divide-y divide-slate-200">{requests.map((request) => <tr className="cursor-pointer hover:bg-cyan-50" key={request.id} onClick={() => void openRequest(request.id)}><td className="px-4 py-3"><strong>{request.title}</strong><p className="font-mono text-xs text-slate-500">{request.requestNo}</p></td><td className="px-4 py-3">{request.requesterName}</td><td className="px-4 py-3">{statusLabels[request.status]}</td><td className="px-4 py-3">¥{request.totalEstimatedAmount.toFixed(2)}</td></tr>)}</tbody></table>{loading ? <p className="p-5 text-sm text-slate-500">正在加载...</p> : !requests.length ? <p className="p-5 text-sm text-slate-500">暂无采购申请。</p> : null}</div>
      {selected ? <aside className="border border-slate-200 bg-white p-5"><p className="font-mono text-xs text-slate-500">{selected.request_no || selected.requestNo}</p><h2 className="mt-2 text-xl font-bold">{selected.title}</h2><p className="mt-2 text-sm text-slate-600">{selected.reason}</p><p className="mt-4 text-sm"><strong>状态：</strong>{statusLabels[selected.status]}</p><h3 className="mt-5 border-b border-slate-200 pb-2 font-bold">零件明细</h3><div className="mt-3 space-y-3">{(selected.items ?? []).map((item) => <div className="border-l-2 border-cyan-700 pl-3 text-sm" key={item.id}><strong>{item.item_name}</strong><p className="text-slate-500">{item.spec || "未填写规格"} · {item.quantity} × ¥{Number(item.estimated_unit_price ?? 0).toFixed(2)}</p></div>)}</div>{actions.length ? <div className="mt-5 border-t border-slate-200 pt-4"><label className="text-sm font-semibold">处理备注<textarea className={`${field} min-h-20`} value={note} onChange={(event) => setNote(event.target.value)}/></label><div className="mt-3 flex flex-wrap gap-2">{actions.map((action) => <button className={action.action === "reject" || action.action === "cancel" ? "border border-red-300 bg-white px-3 py-2 text-sm font-semibold text-red-700" : primary} disabled={busy} key={action.action} onClick={() => void run(() => transitionProcurement(selected.id, action.action, note), `${action.label}成功。`).then((succeeded) => { if (succeeded) setNote(""); })} type="button">{action.label}</button>)}</div></div> : null}<form className="mt-5 border-t border-slate-200 pt-4" onSubmit={(event) => { event.preventDefault(); if (!comment.trim()) return; void run(() => addProcurementComment(selected.id, comment), "评论已添加。").then((succeeded) => { if (succeeded) setComment(""); }); }}><label className="text-sm font-semibold">添加评论<textarea className={`${field} min-h-20`} value={comment} onChange={(event) => setComment(event.target.value)}/></label><button className={`${secondary} mt-2`} disabled={busy} type="submit">发送评论</button></form></aside> : <aside className="border border-dashed border-slate-300 p-6 text-sm text-slate-500">选择一条申请查看明细和处理记录。</aside>}</div>
  </section>;
}
