"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { loadProcurementCatalog } from "./api";
import { addCatalogItem, cartEstimatedTotal, updateCartQuantity, type CartItem, type CatalogItem, type CustomItemDraft } from "./model";

type Category = { id: string; code: string; nameZh: string; descriptionZh: string; isActive: boolean };
type Props = { busy: boolean; onCancel: () => void; onSubmit: (body: unknown) => Promise<boolean> };
const field = "w-full border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 focus:border-cyan-700 focus:outline-none";
const primary = "bg-blue-950 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400";
const secondary = "border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:border-cyan-700";
const emptyCustom = (): CustomItemDraft => ({ itemName: "", spec: "", unit: "件", quantity: 1, estimatedUnitPrice: null, vendor: null, url: null, remark: null });

export function ProcurementOrderBuilder({ busy, onCancel, onSubmit }: Props) {
  const [catalog, setCatalog] = useState<{ categories: Category[]; items: CatalogItem[] }>({ categories: [], items: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [search, setSearch] = useState("");
  const [cart, setCart] = useState<CartItem[]>([]);
  const [title, setTitle] = useState("");
  const [reason, setReason] = useState("");
  const [custom, setCustom] = useState<CustomItemDraft | null>(null);

  useEffect(() => { void loadProcurementCatalog().then((value) => setCatalog(value as { categories: Category[]; items: CatalogItem[] })).catch((value) => setError(value instanceof Error ? value.message : "无法加载标准件目录。")).finally(() => setLoading(false)); }, []);
  const visibleItems = useMemo(() => {
    const keyword = search.trim().toLocaleLowerCase();
    return catalog.items.filter((item) => (!categoryId || item.categoryId === categoryId) && (!keyword || [item.nameZh, item.nameEn, item.spec, item.sku ?? "", item.vendor ?? "", ...item.keywords].join(" ").toLocaleLowerCase().includes(keyword)));
  }, [catalog.items, categoryId, search]);
  const quantityFor = (id: string) => cart.find((item) => item.key === `catalog:${id}`)?.quantity ?? 0;
  const changeCatalogQuantity = (item: CatalogItem, direction: number) => {
    const current = quantityFor(item.id);
    setCart(current === 0 && direction > 0 ? addCatalogItem(cart, item) : updateCartQuantity(cart, `catalog:${item.id}`, current + direction * item.packSize));
  };
  const addCustom = (event: FormEvent) => {
    event.preventDefault();
    if (!custom?.itemName.trim()) return;
    setCart([...cart, { ...custom, key: `custom:${crypto.randomUUID()}`, sourceType: "custom" }]);
    setCustom(null);
  };
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!cart.length) { setError("请先向采购清单添加至少一个项目。"); return; }
    const items = cart.map((item) => item.sourceType === "catalog"
      ? { sourceType: "catalog", catalogItemId: item.catalogItemId, quantity: item.quantity, remark: item.remark || null }
      : { sourceType: "custom", itemName: item.itemName, spec: item.spec, unit: item.unit, quantity: item.quantity, estimatedUnitPrice: item.estimatedUnitPrice, vendor: item.vendor, url: item.url, remark: item.remark });
    await onSubmit({ title, reason, items });
  };

  return <section className="mt-6 border-t-4 border-cyan-700 bg-white shadow-sm">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 px-5 py-4"><div><p className="text-sm font-semibold text-cyan-800">新建采购申请</p><h2 className="mt-1 text-xl font-bold text-blue-950">选择标准件并加入采购清单</h2></div><button className={secondary} onClick={onCancel} type="button">关闭</button></header>
    {error ? <p className="mx-5 mt-4 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">{error}</p> : null}
    <div className="grid min-h-[540px] lg:grid-cols-[190px_minmax(0,1fr)_340px]">
      <nav aria-label="标准件分类" className="border-b border-slate-200 bg-slate-50 p-3 lg:border-b-0 lg:border-r"><button className={`w-full px-3 py-2 text-left text-sm font-semibold ${!categoryId ? "bg-blue-950 text-white" : "text-slate-700 hover:bg-white"}`} onClick={() => setCategoryId("")} type="button">全部标准件</button>{catalog.categories.map((category) => <button className={`mt-1 w-full px-3 py-2 text-left text-sm ${categoryId === category.id ? "bg-cyan-700 font-semibold text-white" : "text-slate-700 hover:bg-white"}`} key={category.id} onClick={() => setCategoryId(category.id)} type="button">{category.nameZh}</button>)}<button className="mt-4 w-full border border-dashed border-cyan-700 px-3 py-2 text-left text-sm font-semibold text-cyan-800" onClick={() => setCustom(emptyCustom())} type="button">+ 自定义项目</button></nav>
      <div className="min-w-0 border-b border-slate-200 p-4 lg:border-b-0 lg:border-r"><label className="sr-only" htmlFor="catalog-search">搜索标准件</label><input className={field} id="catalog-search" onChange={(event) => setSearch(event.target.value)} placeholder="搜索名称、规格、型号或关键词，例如 M6x20" value={search}/><div className="mt-3 text-xs text-slate-500">找到 {visibleItems.length} 个项目</div><div className="mt-2 divide-y divide-slate-200 border border-slate-200">{visibleItems.map((item) => { const quantity = quantityFor(item.id); return <article className="grid min-h-24 grid-cols-[minmax(0,1fr)_116px] items-center gap-3 px-4 py-3" key={item.id}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-950">{item.nameZh}</h3>{item.sku ? <code className="text-xs text-slate-500">{item.sku}</code> : null}</div><p className="mt-1 text-sm text-slate-700"><strong>{item.spec || "通用规格"}</strong> · {item.unit}{item.packSize !== 1 ? ` · 每次 ${item.packSize}${item.unit}` : ""}</p><p className="mt-1 truncate text-xs text-slate-500">{item.vendor || item.categoryNameZh}{item.estimatedUnitPrice === null ? " · 价格待询" : ` · 参考 ¥${item.estimatedUnitPrice.toFixed(2)}/${item.unit}`}</p></div><div className="grid h-9 grid-cols-3 border border-slate-300" aria-label={`${item.nameZh}数量`}><button aria-label={`减少${item.nameZh}`} className="text-lg text-slate-700 disabled:text-slate-300" disabled={!quantity} onClick={() => changeCatalogQuantity(item, -1)} type="button">−</button><output className="grid place-items-center border-x border-slate-300 text-sm font-semibold">{quantity}</output><button aria-label={`增加${item.nameZh}`} className="bg-blue-950 text-lg text-white" onClick={() => changeCatalogQuantity(item, 1)} type="button">+</button></div></article>; })}{loading ? <p className="p-5 text-sm text-slate-500">正在加载目录...</p> : !visibleItems.length ? <p className="p-5 text-sm text-slate-500">没有匹配项目，可调整筛选或添加自定义项目。</p> : null}</div></div>
      <form className="flex min-h-0 flex-col bg-slate-50" onSubmit={submit}><div className="border-b border-slate-200 px-4 py-3"><div className="flex items-center justify-between"><h3 className="font-bold text-blue-950">采购清单</h3><span className="text-xs text-slate-500">{cart.length} 项</span></div></div><div className="max-h-[420px] flex-1 overflow-y-auto p-3"><div className="space-y-2">{cart.map((item) => <div className="border border-slate-200 bg-white p-3" key={item.key}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><strong className="text-sm">{item.sourceType === "catalog" ? item.name : item.itemName}</strong><p className="mt-1 truncate text-xs text-slate-500">{item.spec || "未填写规格"} · {item.sourceType === "catalog" ? "目录" : "自定义"}</p></div><button aria-label="从清单移除" className="text-lg text-slate-400 hover:text-red-700" onClick={() => setCart(cart.filter((entry) => entry.key !== item.key))} type="button">×</button></div><div className="mt-3 flex items-center justify-between gap-3"><div className="grid h-8 w-28 grid-cols-3 border border-slate-300"><button onClick={() => setCart(updateCartQuantity(cart, item.key, item.quantity - (item.sourceType === "catalog" ? catalog.items.find((catalogItem) => catalogItem.id === item.catalogItemId)?.packSize ?? 1 : 1)))} type="button">−</button><input aria-label="采购数量" className="min-w-0 border-x border-slate-300 text-center text-xs outline-none" min="0.01" onChange={(event) => setCart(updateCartQuantity(cart, item.key, Number(event.target.value)))} step="0.01" type="number" value={item.quantity}/><button onClick={() => setCart(updateCartQuantity(cart, item.key, item.quantity + (item.sourceType === "catalog" ? catalog.items.find((catalogItem) => catalogItem.id === item.catalogItemId)?.packSize ?? 1 : 1)))} type="button">+</button></div><span className="text-xs text-slate-500">{item.estimatedUnitPrice === null ? "待询价" : `¥${(item.quantity * item.estimatedUnitPrice).toFixed(2)}`}</span></div></div>)}{!cart.length ? <p className="border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">从目录选择项目，或添加自定义项目。</p> : null}</div></div><div className="mt-auto border-t border-slate-200 bg-white p-4"><div className="mb-4 flex justify-between text-sm"><span className="text-slate-600">预计合计</span><strong>¥{cartEstimatedTotal(cart).toFixed(2)}</strong></div><label className="text-sm font-semibold">申请标题<input className={`${field} mt-1`} maxLength={200} onChange={(event) => setTitle(event.target.value)} required value={title}/></label><label className="mt-3 block text-sm font-semibold">申请理由<textarea className={`${field} mt-1 min-h-20`} maxLength={4000} onChange={(event) => setReason(event.target.value)} required value={reason}/></label><button className={`${primary} mt-4 w-full`} disabled={busy || !cart.length} type="submit">{busy ? "提交中..." : "提交采购申请"}</button></div></form>
    </div>
    {custom ? <div aria-labelledby="custom-item-title" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog"><form className="w-full max-w-2xl border-t-4 border-cyan-700 bg-white p-6 shadow-2xl" onSubmit={addCustom}><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-cyan-800">目录外物料</p><h2 className="mt-1 text-2xl font-bold text-blue-950" id="custom-item-title">添加自定义项目</h2></div><button aria-label="关闭" className="text-2xl text-slate-500" onClick={() => setCustom(null)} type="button">×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">名称<input autoFocus className={`${field} mt-1`} onChange={(event) => setCustom({ ...custom, itemName: event.target.value })} required value={custom.itemName}/></label><label className="text-sm font-semibold">规格<input className={`${field} mt-1`} onChange={(event) => setCustom({ ...custom, spec: event.target.value })} value={custom.spec}/></label><label className="text-sm font-semibold">数量<input className={`${field} mt-1`} min="0.01" onChange={(event) => setCustom({ ...custom, quantity: Number(event.target.value) })} required step="0.01" type="number" value={custom.quantity}/></label><label className="text-sm font-semibold">单位<input className={`${field} mt-1`} onChange={(event) => setCustom({ ...custom, unit: event.target.value })} required value={custom.unit}/></label><label className="text-sm font-semibold">预计单价<input className={`${field} mt-1`} min="0" onChange={(event) => setCustom({ ...custom, estimatedUnitPrice: event.target.value ? Number(event.target.value) : null })} step="0.01" type="number" value={custom.estimatedUnitPrice ?? ""}/></label><label className="text-sm font-semibold">供应商<input className={`${field} mt-1`} onChange={(event) => setCustom({ ...custom, vendor: event.target.value || null })} value={custom.vendor ?? ""}/></label><label className="text-sm font-semibold sm:col-span-2">商品链接<input className={`${field} mt-1`} onChange={(event) => setCustom({ ...custom, url: event.target.value || null })} type="url" value={custom.url ?? ""}/></label><label className="text-sm font-semibold sm:col-span-2">备注<textarea className={`${field} mt-1 min-h-20`} onChange={(event) => setCustom({ ...custom, remark: event.target.value || null })} value={custom.remark ?? ""}/></label></div><div className="mt-6 flex justify-end gap-3"><button className={secondary} onClick={() => setCustom(null)} type="button">取消</button><button className={primary} type="submit">加入清单</button></div></form></div> : null}
  </section>;
}
