"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { addProcurementComment,completeProcurementProcessing,confirmProcurementReceived,createProcurement,loadProcurement,loadProcurements,saveProcurementProcessing,transitionProcurement } from "./api";
import { availableActions,procurementCapabilities,type ProcurementStatus } from "./model";
import { ProcurementCatalogManager } from "./ProcurementCatalogManager";
import { ProcurementOrderBuilder } from "./ProcurementOrderBuilder";

type Props={permissions:string[];userId:string};type RequestSummary={id:string;requestNo:string;requesterId:string;requesterName:string;title:string;reason:string;status:ProcurementStatus;totalEstimatedAmount:number;createdAt:string;updatedAt:string};
type ProcessingStatus="pending"|"purchased"|"rejected";
type ProcurementItem={id:string;item_name:string;spec:string;unit?:string;quantity:number;estimated_unit_price:number|null;source_type?:"catalog"|"custom";url?:string|null;catalog_snapshot?:Record<string,unknown>;processing_status?:ProcessingStatus;rejection_reason?:string|null};
type ProcurementDetail={id:string;request_no?:string;requestNo?:string;requester_id?:string;requesterId?:string;title:string;reason:string;status:ProcurementStatus;items?:ProcurementItem[]};
const field="mt-1 w-full border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 focus:border-cyan-700 focus:outline-none",primary="bg-blue-950 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400",secondary="border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:border-cyan-700";
const statusLabels:Record<ProcurementStatus,string>={draft:"草稿",submitted:"待处理",approved:"已批准",rejected:"已驳回",purchasing:"处理中",purchased:"已下单",received:"已到货",closed:"已完成",cancelled:"已撤回"};

function linkFor(item:ProcurementItem){const snapshot=item.catalog_snapshot&&typeof item.catalog_snapshot==="object"?item.catalog_snapshot:{};return item.url||typeof snapshot.url==="string"?String(item.url||snapshot.url):null;}

function ProcessingPanel({request,busy,onRun}:{request:ProcurementDetail;busy:boolean;onRun(action:()=>Promise<unknown>,success:string):Promise<boolean>}){
  const[draft,setDraft]=useState(()=>Object.fromEntries((request.items??[]).map((item)=>[item.id,{status:item.processing_status??"pending",rejectionReason:item.rejection_reason??""}])) as Record<string,{status:ProcessingStatus;rejectionReason:string}>);
  useEffect(()=>setDraft(Object.fromEntries((request.items??[]).map((item)=>[item.id,{status:item.processing_status??"pending",rejectionReason:item.rejection_reason??""}]))),[request]);
  const items=request.items??[],allDone=items.length>0&&items.every((item)=>draft[item.id]?.status!=="pending");
  const setStatus=(id:string,status:ProcessingStatus)=>setDraft((current)=>({...current,[id]:{status,rejectionReason:status==="rejected"?current[id]?.rejectionReason??"":""}}));
  const processingBody=()=>({items:items.map((item)=>({itemId:item.id,status:draft[item.id]?.status??"pending",rejectionReason:draft[item.id]?.status==="rejected"?draft[item.id]?.rejectionReason||null:null}))});
  const save=()=>onRun(()=>saveProcurementProcessing(request.id,processingBody()),"采购处理进度已保存。");
  const complete=()=>onRun(async()=>{await saveProcurementProcessing(request.id,processingBody());await completeProcurementProcessing(request.id)},"采购申请处理完成。");
  return <section className="mt-5 border-t border-slate-200 pt-4"><div className="flex items-center justify-between"><h3 className="font-bold text-blue-950">逐条采购处理</h3><span className="text-xs text-slate-500">{items.filter((item)=>draft[item.id]?.status!=="pending").length} / {items.length} 已处理</span></div><div className="mt-3 space-y-3">{items.map((item)=>{const state=draft[item.id]??{status:"pending" as const,rejectionReason:""},url=linkFor(item);return <article className={`border p-3 ${state.status==="purchased"?"border-emerald-300 bg-emerald-50":state.status==="rejected"?"border-red-300 bg-red-50":"border-slate-200 bg-white"}`} key={item.id}><div className="flex items-start justify-between gap-3"><div><strong>{item.item_name}</strong><p className="mt-1 text-xs text-slate-500">{item.spec||"未填写规格"}</p><p className="mt-2 text-lg font-black text-blue-950">{item.quantity}{item.unit||"件"}</p>{url?<a className="mt-2 inline-block text-sm font-semibold text-cyan-800 underline" href={url} rel="noreferrer" target="_blank">前往购物平台购买 ↗</a>:<p className="mt-2 text-xs font-semibold text-amber-700">该条目没有购买链接</p>}</div><div className="flex gap-2"><button aria-label="标记已购买" className={`grid h-10 w-10 place-items-center border text-xl font-bold ${state.status==="purchased"?"border-emerald-700 bg-emerald-700 text-white":"border-slate-300 text-emerald-700"}`} onClick={()=>setStatus(item.id,state.status==="purchased"?"pending":"purchased")} title="已购买/取消" type="button">✓</button><button aria-label="标记驳回" className={`grid h-10 w-10 place-items-center border text-xl font-bold ${state.status==="rejected"?"border-red-700 bg-red-700 text-white":"border-slate-300 text-red-700"}`} onClick={()=>setStatus(item.id,state.status==="rejected"?"pending":"rejected")} title="驳回/取消" type="button">×</button></div></div>{state.status==="rejected"?<label className="mt-3 block text-xs font-semibold text-red-800">驳回意见<textarea className={`${field} min-h-16 border-red-300`} maxLength={2000} onChange={(event)=>setDraft((current)=>({...current,[item.id]:{...current[item.id],rejectionReason:event.target.value}}))} placeholder="说明不同意购买或无法购买的原因" required value={state.rejectionReason}/></label>:null}</article>})}</div><div className="mt-4 flex flex-wrap gap-3"><button className={secondary} disabled={busy} onClick={()=>void save()} type="button">保存当前进度</button><button className={primary} disabled={busy||!allDone||items.some((item)=>draft[item.id]?.status==="rejected"&&!draft[item.id]?.rejectionReason.trim())} onClick={()=>void complete()} type="button">完成处理</button></div>{!allDone?<p className="mt-2 text-xs text-slate-500">所有条目都标记为已购买或已驳回后，才能完成处理。</p>:null}</section>;
}

export function ProcurementConsole({permissions,userId}:Props){const capability=procurementCapabilities(permissions);const[scope,setScope]=useState<"mine"|"all">("mine"),[requests,setRequests]=useState<RequestSummary[]>([]),[selected,setSelected]=useState<ProcurementDetail|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[view,setView]=useState<"requests"|"catalog">("requests"),[comment,setComment]=useState(""),[note,setNote]=useState("");
  const refresh=useCallback(async(nextScope=scope)=>{setLoading(true);try{setRequests(await loadProcurements(nextScope) as RequestSummary[]);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"无法加载采购申请。")}finally{setLoading(false)}},[scope]);useEffect(()=>{void refresh()},[refresh]);
  async function openRequest(id:string){try{setSelected(await loadProcurement(id) as ProcurementDetail);setNote("");setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"无法加载申请详情。")}}
  async function reloadSelected(messageText:string){await refresh();if(selected?.id)setSelected(await loadProcurement(selected.id) as ProcurementDetail);setMessage(messageText)}
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);try{await action();await reloadSelected(success);return true}catch(error){setMessage(error instanceof Error?error.message:"操作失败。");return false}finally{setBusy(false)}}
  async function submit(body:unknown){const succeeded=await run(()=>createProcurement(body),"采购申请已提交。");if(succeeded)setShowForm(false);return succeeded}
  const actions=useMemo(()=>selected?availableActions(selected.status,capability,selected.requester_id===userId||selected.requesterId===userId).filter((action)=>action.action==="cancel"||!capability.purchase||!["submitted","purchasing","purchased"].includes(selected.status)):[],[capability,selected,userId]);
  return <section aria-labelledby="procurement-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-300 pb-5"><div><p className="text-sm font-semibold text-cyan-800">内部业务</p><h1 className="mt-2 font-serif text-3xl font-bold text-slate-950" id="procurement-heading">零件采购</h1><p className="mt-2 text-sm text-slate-600">成员提交清单，采购管理员逐条处理并跟踪收货</p></div>{capability.create?<button className={primary} onClick={()=>setShowForm(true)} type="button">新建申请</button>:null}</header><nav aria-label="采购模块视图" className="mt-5 flex gap-1 border-b border-slate-300"><button className={`border-b-2 px-3 py-2.5 text-sm font-semibold ${view==="requests"?"border-cyan-700 text-cyan-800":"border-transparent text-slate-600"}`} onClick={()=>setView("requests")} type="button">采购申请</button>{capability.purchase?<button className={`border-b-2 px-3 py-2.5 text-sm font-semibold ${view==="catalog"?"border-cyan-700 text-cyan-800":"border-transparent text-slate-600"}`} onClick={()=>setView("catalog")} type="button">标准件目录</button>:null}</nav>{message?<p className="mt-4 border border-cyan-200 bg-white px-4 py-3 text-sm text-slate-700" role="status">{message}</p>:null}
    {view==="catalog"&&capability.purchase?<ProcurementCatalogManager/>:<>{showForm?<ProcurementOrderBuilder busy={busy} onCancel={()=>setShowForm(false)} onSubmit={submit}/>:null}<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex border border-slate-300 bg-white p-1"><button className={`px-3 py-2 text-sm font-semibold ${scope==="mine"?"bg-blue-950 text-white":"text-slate-600"}`} onClick={()=>{setScope("mine");setSelected(null)}} type="button">我的申请</button>{capability.readAll?<button className={`px-3 py-2 text-sm font-semibold ${scope==="all"?"bg-blue-950 text-white":"text-slate-600"}`} onClick={()=>{setScope("all");setSelected(null)}} type="button">全部申请</button>:null}</div><button className={secondary} onClick={()=>void refresh()} type="button">刷新</button></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_480px]"><div className="overflow-x-auto border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">申请</th><th className="px-4 py-3">申请人</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">预计金额</th></tr></thead><tbody className="divide-y divide-slate-200">{requests.map((request)=><tr className="cursor-pointer hover:bg-cyan-50" key={request.id} onClick={()=>void openRequest(request.id)}><td className="px-4 py-3"><strong>{request.title}</strong><p className="font-mono text-xs text-slate-500">{request.requestNo}</p></td><td className="px-4 py-3">{request.requesterName}</td><td className="px-4 py-3">{statusLabels[request.status]}</td><td className="px-4 py-3">¥{request.totalEstimatedAmount.toFixed(2)}</td></tr>)}</tbody></table>{loading?<p className="p-5 text-sm text-slate-500">正在加载...</p>:!requests.length?<p className="p-5 text-sm text-slate-500">暂无采购申请。</p>:null}</div>
      {selected?<aside className="border border-slate-200 bg-white p-5"><p className="font-mono text-xs text-slate-500">{selected.request_no||selected.requestNo}</p><h2 className="mt-2 text-xl font-bold">{selected.title}</h2><p className="mt-2 text-sm text-slate-600">{selected.reason}</p><p className="mt-4 text-sm"><strong>状态：</strong>{statusLabels[selected.status]}</p><h3 className="mt-5 border-b border-slate-200 pb-2 font-bold">零件明细</h3><div className="mt-3 space-y-3">{(selected.items??[]).map((item)=>{const url=linkFor(item);return <div className="border-l-2 border-cyan-700 pl-3 text-sm" key={item.id}><div className="flex items-center gap-2"><strong>{item.item_name}</strong><span className="text-xs text-slate-400">{item.source_type==="catalog"?"目录":"自定义"}</span></div><p className="text-slate-500">{item.spec||"未填写规格"}</p><p className="mt-1 text-lg font-black text-blue-950">{item.quantity}{item.unit||"件"}</p>{url?<a className="text-xs font-semibold text-cyan-800 underline" href={url} rel="noreferrer" target="_blank">购买链接 ↗</a>:null}{item.processing_status&&item.processing_status!=="pending"?<p className={`mt-1 text-xs font-semibold ${item.processing_status==="purchased"?"text-emerald-700":"text-red-700"}`}>{item.processing_status==="purchased"?"已购买":`已驳回：${item.rejection_reason||""}`}</p>:null}</div>})}</div>
        {capability.purchase&&["submitted","purchasing"].includes(selected.status)?<ProcessingPanel busy={busy} onRun={run} request={selected}/>:null}
        {capability.purchase&&selected.status==="purchased"?<div className="mt-5 border-t border-slate-200 pt-4"><button className={primary} disabled={busy} onClick={()=>void run(()=>confirmProcurementReceived(selected.id),"已确认全部收货，采购申请完成。")} type="button">确认全部收货并完成</button></div>:null}
        {actions.length?<div className="mt-5 border-t border-slate-200 pt-4"><label className="text-sm font-semibold">处理备注<textarea className={`${field} min-h-20`} value={note} onChange={(event)=>setNote(event.target.value)}/></label><div className="mt-3 flex flex-wrap gap-2">{actions.map((action)=><button className={action.action==="reject"||action.action==="cancel"?"border border-red-300 bg-white px-3 py-2 text-sm font-semibold text-red-700":primary} disabled={busy} key={action.action} onClick={()=>void run(()=>transitionProcurement(selected.id,action.action,note),`${action.label}成功。`).then((succeeded)=>{if(succeeded)setNote("")})} type="button">{action.label}</button>)}</div></div>:null}<form className="mt-5 border-t border-slate-200 pt-4" onSubmit={(event)=>{event.preventDefault();if(!comment.trim())return;void run(()=>addProcurementComment(selected.id,comment),"评论已添加。").then((succeeded)=>{if(succeeded)setComment("")})}}><label className="text-sm font-semibold">添加评论<textarea className={`${field} min-h-20`} value={comment} onChange={(event)=>setComment(event.target.value)}/></label><button className={`${secondary} mt-2`} disabled={busy} type="submit">发送评论</button></form></aside>:<aside className="border border-dashed border-slate-300 p-6 text-sm text-slate-500">选择一条申请查看明细和处理记录。</aside>}</div></>}</section>;
}
