"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { addProcurementComment, createProcurement, loadProcurement, loadProcurements, transitionProcurement } from "./api";
import { availableActions, procurementCapabilities, type ProcurementStatus } from "./model";
import { ProcurementCatalogManager } from "./ProcurementCatalogManager";
import { ProcurementOrderBuilder } from "./ProcurementOrderBuilder";

type Props = { permissions: string[]; userId: string };
type RequestSummary = { id: string; requestNo: string; requesterId: string; requesterName: string; title: string; reason: string; status: ProcurementStatus; totalEstimatedAmount: number; createdAt: string; updatedAt: string };
type ProcurementItem = { id: string; item_name: string; spec: string; unit?: string; quantity: number; estimated_unit_price: number | null; source_type?: "catalog" | "custom" };
type ProcurementDetail = { id: string; request_no?: string; requestNo?: string; requester_id?: string; requesterId?: string; title: string; reason: string; status: ProcurementStatus; items?: ProcurementItem[] };

const field = "mt-1 w-full border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 focus:border-cyan-700 focus:outline-none";
const primary = "bg-blue-950 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400";
const secondary = "border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:border-cyan-700";
const statusLabels: Record<ProcurementStatus, string> = { draft: "草稿", submitted: "待审批", approved: "已批准", rejected: "已驳回", purchasing: "采购中", purchased: "已采购", received: "已到货", closed: "已关闭", cancelled: "已撤回" };

export function ProcurementConsole({ permissions, userId }: Props) {
  const capability = procurementCapabilities(permissions);
  const [scope, setScope] = useState<"mine" | "all">("mine"); const [requests, setRequests] = useState<RequestSummary[]>([]); const [selected, setSelected] = useState<ProcurementDetail | null>(null);
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false);
  const [view, setView] = useState<"requests" | "catalog">("requests"); const [comment, setComment] = useState(""); const [note, setNote] = useState("");

  const refresh = useCallback(async (nextScope = scope) => { setLoading(true); try { setRequests(await loadProcurements(nextScope) as RequestSummary[]); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "无法加载采购申请。"); } finally { setLoading(false); } }, [scope]);
  useEffect(() => { void refresh(); }, [refresh]);

  async function openRequest(id: string) { try { setSelected(await loadProcurement(id) as ProcurementDetail); setNote(""); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "无法加载申请详情。"); } }
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); try { await action(); await refresh(); if (selected?.id) setSelected(await loadProcurement(selected.id) as ProcurementDetail); setMessage(success); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败。"); return false; } finally { setBusy(false); } }
  async function submit(body: unknown) { const succeeded = await run(() => createProcurement(body), "采购申请已提交。"); if (succeeded) setShowForm(false); return succeeded; }
  const actions = useMemo(() => selected ? availableActions(selected.status, capability, selected.requester_id === userId || selected.requesterId === userId) : [], [capability, selected, userId]);

  return <section aria-labelledby="procurement-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-300 pb-5"><div><p className="text-sm font-semibold text-cyan-800">内部业务</p><h1 className="mt-2 font-serif text-3xl font-bold text-slate-950" id="procurement-heading">零件采购</h1><p className="mt-2 text-sm text-slate-600">提交采购申请，并按权限完成审批、采购、到货和关闭流程</p></div>{capability.create ? <button className={primary} onClick={() => setShowForm(true)} type="button">新建申请</button> : null}</header>
    <nav aria-label="采购模块视图" className="mt-5 flex gap-1 border-b border-slate-300"><button className={`border-b-2 px-3 py-2.5 text-sm font-semibold ${view === "requests" ? "border-cyan-700 text-cyan-800" : "border-transparent text-slate-600"}`} onClick={() => setView("requests")} type="button">采购申请</button>{capability.purchase ? <button className={`border-b-2 px-3 py-2.5 text-sm font-semibold ${view === "catalog" ? "border-cyan-700 text-cyan-800" : "border-transparent text-slate-600"}`} onClick={() => setView("catalog")} type="button">标准件目录</button> : null}</nav>
    {message ? <p className="mt-4 border border-cyan-200 bg-white px-4 py-3 text-sm text-slate-700" role="status">{message}</p> : null}
    {view === "catalog" && capability.purchase ? <ProcurementCatalogManager/> : <>{showForm ? <ProcurementOrderBuilder busy={busy} onCancel={() => setShowForm(false)} onSubmit={submit}/> : null}<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex border border-slate-300 bg-white p-1"><button className={`px-3 py-2 text-sm font-semibold ${scope === "mine" ? "bg-blue-950 text-white" : "text-slate-600"}`} onClick={() => { setScope("mine"); setSelected(null); }} type="button">我的申请</button>{capability.readAll ? <button className={`px-3 py-2 text-sm font-semibold ${scope === "all" ? "bg-blue-950 text-white" : "text-slate-600"}`} onClick={() => { setScope("all"); setSelected(null); }} type="button">全部申请</button> : null}</div><button className={secondary} onClick={() => void refresh()} type="button">刷新</button></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]"><div className="overflow-x-auto border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">申请</th><th className="px-4 py-3">申请人</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">预计金额</th></tr></thead><tbody className="divide-y divide-slate-200">{requests.map((request) => <tr className="cursor-pointer hover:bg-cyan-50" key={request.id} onClick={() => void openRequest(request.id)}><td className="px-4 py-3"><strong>{request.title}</strong><p className="font-mono text-xs text-slate-500">{request.requestNo}</p></td><td className="px-4 py-3">{request.requesterName}</td><td className="px-4 py-3">{statusLabels[request.status]}</td><td className="px-4 py-3">¥{request.totalEstimatedAmount.toFixed(2)}</td></tr>)}</tbody></table>{loading ? <p className="p-5 text-sm text-slate-500">正在加载...</p> : !requests.length ? <p className="p-5 text-sm text-slate-500">暂无采购申请。</p> : null}</div>
      {selected ? <aside className="border border-slate-200 bg-white p-5"><p className="font-mono text-xs text-slate-500">{selected.request_no || selected.requestNo}</p><h2 className="mt-2 text-xl font-bold">{selected.title}</h2><p className="mt-2 text-sm text-slate-600">{selected.reason}</p><p className="mt-4 text-sm"><strong>状态：</strong>{statusLabels[selected.status]}</p><h3 className="mt-5 border-b border-slate-200 pb-2 font-bold">零件明细</h3><div className="mt-3 space-y-3">{(selected.items ?? []).map((item) => <div className="border-l-2 border-cyan-700 pl-3 text-sm" key={item.id}><div className="flex items-center gap-2"><strong>{item.item_name}</strong><span className="text-xs text-slate-400">{item.source_type === "catalog" ? "目录" : "自定义"}</span></div><p className="text-slate-500">{item.spec || "未填写规格"} · {item.quantity}{item.unit || "件"} × ¥{Number(item.estimated_unit_price ?? 0).toFixed(2)}</p></div>)}</div>{actions.length ? <div className="mt-5 border-t border-slate-200 pt-4"><label className="text-sm font-semibold">处理备注<textarea className={`${field} min-h-20`} value={note} onChange={(event) => setNote(event.target.value)}/></label><div className="mt-3 flex flex-wrap gap-2">{actions.map((action) => <button className={action.action === "reject" || action.action === "cancel" ? "border border-red-300 bg-white px-3 py-2 text-sm font-semibold text-red-700" : primary} disabled={busy} key={action.action} onClick={() => void run(() => transitionProcurement(selected.id, action.action, note), `${action.label}成功。`).then((succeeded) => { if (succeeded) setNote(""); })} type="button">{action.label}</button>)}</div></div> : null}<form className="mt-5 border-t border-slate-200 pt-4" onSubmit={(event) => { event.preventDefault(); if (!comment.trim()) return; void run(() => addProcurementComment(selected.id, comment), "评论已添加。").then((succeeded) => { if (succeeded) setComment(""); }); }}><label className="text-sm font-semibold">添加评论<textarea className={`${field} min-h-20`} value={comment} onChange={(event) => setComment(event.target.value)}/></label><button className={`${secondary} mt-2`} disabled={busy} type="submit">发送评论</button></form></aside> : <aside className="border border-dashed border-slate-300 p-6 text-sm text-slate-500">选择一条申请查看明细和处理记录。</aside>}</div></>}
  </section>;
}
