import type { Pool, PoolClient } from "pg";
import type { AssetBatchInput, AssetImportInput, AssetImportRow, LabAsset, LabDeviceType, LabNote, LabPlatform, LabPlatformType, LocalizedText, UsageReviewInput } from "./schemas.js";
import { insertNotifications, type NotificationEvent } from "../notifications/notificationService.js";

type TransactionPool = Pick<Pool, "connect">;
type AuditInput = { actorId: string; action: string; targetType: string; targetId: string; revision: string; detail?: Record<string, unknown> };
type ErrorWithCleanupFailures = Error & { cleanupFailures?: unknown[] };
type SnapshotActor = { id: string; canManage: boolean };
type Dependencies = { getSnapshot?: (actor: SnapshotActor) => Promise<any>; notify?: (client: Pick<PoolClient,"query">, event: NotificationEvent) => Promise<void> };
type UsageReview = Omit<UsageReviewInput,"expectedRevision">;

export type { LabAsset, LabDeviceType, LabNote, LabPlatform, LabPlatformType } from "./schemas.js";
export class ConflictError extends Error { constructor(message: string) { super(message); this.name = "ConflictError"; } }
export class RevisionConflictError extends Error { constructor() { super("Lab assets revision conflict"); this.name = "RevisionConflictError"; } }
export type AssetImportIssue={field:string;message:string;severity:"error"|"warning"};
export type AssetImportResultRow={index:number;row:AssetImportRow;issues:AssetImportIssue[]};
export type AssetImportReport={summary:{total:number;valid:number;warnings:number;errors:number};rows:AssetImportResultRow[]};
export class ImportValidationError extends Error { constructor(readonly report:AssetImportReport) { super("Asset import validation failed"); this.name="ImportValidationError"; } }

function localized(zh?: string | null, en?: string | null): LocalizedText { return { zh: zh ?? "", en: en ?? "" }; }
function natural(left: string, right: string) { return left.localeCompare(right, "zh-CN", { numeric: true, sensitivity: "base" }); }
export function assetDisplayState(asset:{condition?:string;status?:string;currentPlatformCode?:string|null;assignedUserId?:string|null;borrowerName?:string}){if(asset.condition==="retired")return"retired";if(asset.condition==="maintenance")return"maintenance";if(asset.status==="lend"||asset.borrowerName)return"lend";if(asset.assignedUserId||asset.status==="in_use")return"in_use";if(asset.currentPlatformCode)return"mounted";return"idle";}
function attachCleanupFailure(primaryError: unknown, cleanupError: unknown) { if (primaryError instanceof Error) { const error = primaryError as ErrorWithCleanupFailures; error.cleanupFailures ??= []; error.cleanupFailures.push(cleanupError); } }

async function claimRevision(client: PoolClient, expectedRevision: string) {
  const result = await client.query<{ revision: string }>(`UPDATE site_content_revisions SET revision=revision+1,updated_at=now() WHERE module_key='lab-assets' AND revision=$1::bigint RETURNING revision::text revision`, [expectedRevision]);
  if (!result.rowCount) throw new RevisionConflictError();
  return result.rows[0].revision;
}

async function audit(client: PoolClient, input: AuditInput) {
  await client.query(`INSERT INTO audit_logs(actor_id,action,target_type,target_id,detail) VALUES($1,$2,$3,$4,$5::jsonb)`, [input.actorId,input.action,input.targetType,input.targetId,JSON.stringify({ revision: input.revision, ...input.detail })]);
}

export function createLabAssetsService(pool: TransactionPool, dependencies: Dependencies = {}) {
  const notify=dependencies.notify??insertNotifications;
  async function managers(client:Pick<PoolClient,"query">,exclude?:string){const result=await client.query<{id:string}>(`SELECT DISTINCT users.id FROM users LEFT JOIN user_permission_templates templates ON templates.user_id=users.id LEFT JOIN permission_template_permissions allowed ON allowed.template_key=templates.template_key AND allowed.permission_key='lab_assets.write' LEFT JOIN user_permission_overrides grants ON grants.user_id=users.id AND grants.permission_key='lab_assets.write' AND grants.decision='grant' LEFT JOIN user_permission_overrides revokes ON revokes.user_id=users.id AND revokes.permission_key='lab_assets.write' AND revokes.decision='revoke' WHERE users.status='active' AND ($1::uuid IS NULL OR users.id<>$1) AND revokes.user_id IS NULL AND (users.base_tier='super' OR allowed.permission_key IS NOT NULL OR grants.permission_key IS NOT NULL)`,[exclude??null]);return result.rows.map((row)=>row.id).filter(Boolean);}
  async function transaction<T>(invoke: (client: PoolClient) => Promise<T>) {
    const client = await pool.connect(); let primaryError: unknown;
    try { await client.query("BEGIN"); const result = await invoke(client); await client.query("COMMIT"); return result; }
    catch (error) { primaryError = error; try { await client.query("ROLLBACK"); } catch (cleanup) { attachCleanupFailure(primaryError, cleanup); } }
    finally { try { client.release(); } catch (cleanup) { if (primaryError === undefined) throw cleanup; attachCleanupFailure(primaryError, cleanup); } }
    throw primaryError;
  }

  async function mutate(input: Omit<AuditInput,"revision"> & { expectedRevision: string }, write: (client: PoolClient) => Promise<void>) {
    return transaction(async (client) => { const revision = await claimRevision(client,input.expectedRevision); await write(client); await audit(client,{...input,revision}); return revision; });
  }

  async function findId(client: PoolClient, table: "lab_platforms"|"lab_platform_types"|"lab_device_types", code: string) {
    const result = await client.query<{id:string}>(`SELECT id FROM ${table} WHERE code=$1 LIMIT 1`,[code]);
    if (!result.rowCount) throw new ConflictError(`${table === "lab_platforms" ? "Platform" : table === "lab_platform_types" ? "Platform type" : "Device type"} not found`);
    return result.rows[0].id;
  }

  async function findDeviceType(client:PoolClient,code:string){const result=await client.query<{id:string;name:string}>(`SELECT id,name FROM lab_device_types WHERE code=$1 LIMIT 1`,[code]);if(!result.rowCount)throw new ConflictError("Device type not found");return result.rows[0];}

  async function duplicate(client: PoolClient, table: string, code: string, currentCode?: string) {
    const result=await client.query(`SELECT 1 FROM ${table} WHERE code=$1${currentCode===undefined?"":" AND code<>$2"} LIMIT 1`,currentCode===undefined?[code]:[code,currentCode]);
    return Boolean(result.rowCount);
  }
  function requireAffected(result:{rowCount:number|null},target:string){if(!result.rowCount)throw new ConflictError(`${target} not found`);}

  async function getSnapshot(actor: SnapshotActor={id:"",canManage:false}) {
    const client=await pool.connect();let primaryError:unknown;
    try{
      await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");
      const [pageResult,revisionResult,platformTypesResult,deviceTypesResult,platformsResult,assetsResult,membersResult,requestsResult,platformSpecsResult,assetSpecsResult,slotsResult,definitionsResult]=await Promise.all([
        client.query(`SELECT content_json FROM page_content WHERE page_key='lab_assets_page' LIMIT 1`),
        client.query(`SELECT revision::text revision FROM site_content_revisions WHERE module_key='lab-assets'`),
        client.query(`SELECT code,COALESCE(NULLIF(name_zh,''),NULLIF(name_en,''),code) name FROM lab_platform_types ORDER BY COALESCE(NULLIF(name_zh,''),NULLIF(name_en,''),code),code`),
        client.query(`SELECT code,name FROM lab_device_types ORDER BY name,code`),
        client.query(`SELECT p.code,t.code type_code,p.name_zh,p.name_en,p.description_zh,p.description_en,p.status,p.location,p.maintainer_user_id,maintainer.display_name maintainer_name,p.commissioned_at,pp.public_visible,pp.title_zh public_title_zh,pp.title_en public_title_en,pp.description_zh public_description_zh,pp.description_en public_description_en,pp.image_asset_id,media.url image_url,pp.tags,pp.component_display_mode,pp.sort_order public_sort_order FROM lab_platforms p JOIN lab_platform_types t ON t.id=p.type_id LEFT JOIN users maintainer ON maintainer.id=p.maintainer_user_id LEFT JOIN lab_platform_public_profiles pp ON pp.platform_id=p.id LEFT JOIN media_assets media ON media.id=pp.image_asset_id ORDER BY COALESCE(NULLIF(t.name_zh,''),NULLIF(t.name_en,''),t.code),p.code`),
        client.query(`SELECT a.code,dt.code device_type_code,dt.name device_type_name,a.manufacturer,a.model,a.name_zh,a.name_en,a.description_zh,a.description_en,a.vendor_serial,a.status,a.condition,p.code current_platform_code,a.platform_role_zh,a.platform_role_en,a.platform_slot,a.platform_sort_order,a.mounted_at,a.assigned_user_id,u.display_name assigned_user_name,a.borrower_name,a.borrower_contact,a.storage_location,a.updated_at,ap.public_visible,ap.title_zh public_title_zh,ap.title_en public_title_en,ap.description_zh public_description_zh,ap.description_en public_description_en,ap.image_asset_id,media.url image_url,ap.sort_order public_sort_order
          FROM lab_assets a JOIN lab_device_types dt ON dt.id=a.device_type_id LEFT JOIN lab_platforms p ON p.id=a.current_platform_id LEFT JOIN users u ON u.id=a.assigned_user_id LEFT JOIN lab_asset_public_profiles ap ON ap.asset_id=a.id LEFT JOIN media_assets media ON media.id=ap.image_asset_id ORDER BY dt.name,a.code`),
        actor.canManage?client.query(`SELECT id,username,display_name FROM users WHERE status='active' ORDER BY display_name,username`):Promise.resolve({rows:[]}),
        client.query(`SELECT r.id,r.status,r.reason,r.review_note,r.created_at,r.reviewed_at,a.code asset_code,a.name_zh asset_name_zh,a.name_en asset_name_en,u.id requester_id,u.display_name requester_name,reviewer.display_name reviewer_name
          FROM lab_asset_usage_requests r JOIN lab_assets a ON a.id=r.asset_id JOIN users u ON u.id=r.requester_id LEFT JOIN users reviewer ON reviewer.id=r.reviewed_by
          WHERE $1::boolean OR r.requester_id=$2 ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.created_at DESC`,[actor.canManage,actor.id]),
        client.query(`SELECT p.code owner_code,s.key,s.label_zh,s.label_en,s.value_zh,s.value_en,s.unit,s.public_visible,s.sort_order FROM lab_platform_specs s JOIN lab_platforms p ON p.id=s.platform_id ORDER BY p.code,s.sort_order,s.id`),
        client.query(`SELECT a.code owner_code,s.key,s.label_zh,s.label_en,s.value_zh,s.value_en,s.unit,s.public_visible,s.sort_order FROM lab_asset_specs s JOIN lab_assets a ON a.id=s.asset_id ORDER BY a.code,s.sort_order,s.id`),
        client.query(`SELECT pt.code platform_type_code,s.slot_key,s.name_zh,s.name_en,dt.code device_type_code,s.required,s.min_count,s.max_count,s.sort_order FROM lab_platform_type_slots s JOIN lab_platform_types pt ON pt.id=s.platform_type_id LEFT JOIN lab_device_types dt ON dt.id=s.device_type_id ORDER BY pt.code,s.sort_order,s.id`),
        client.query(`SELECT dt.code device_type_code,d.key,d.label_zh,d.label_en,d.unit,d.sort_order FROM lab_device_type_spec_definitions d JOIN lab_device_types dt ON dt.id=d.device_type_id ORDER BY dt.code,d.sort_order,d.id`),
      ]);
      const specs=(rows:any[],code:string)=>rows.filter((row)=>row.owner_code===code).map((row)=>({key:row.key,label:localized(row.label_zh,row.label_en),value:localized(row.value_zh,row.value_en),unit:row.unit??"",publicVisible:Boolean(row.public_visible),sortOrder:row.sort_order??0}));
      const assets=assetsResult.rows.map((row:any)=>{const item:any={code:row.code,deviceTypeCode:row.device_type_code,deviceTypeName:row.device_type_name,manufacturer:row.manufacturer??"",model:row.model??"",name:localized(row.name_zh,row.name_en),description:localized(row.description_zh,row.description_en),vendorSerial:row.vendor_serial??"",status:row.status,condition:row.condition,currentPlatformCode:row.current_platform_code,platformRole:localized(row.platform_role_zh,row.platform_role_en),platformSlot:row.platform_slot,platformSortOrder:row.platform_sort_order??0,mountedAt:row.mounted_at,assignedUserId:row.assigned_user_id,assignedUserName:row.assigned_user_name??"",borrowerName:row.borrower_name??"",borrowerContact:row.borrower_contact??"",storageLocation:row.storage_location??null,updatedAt:row.updated_at,specs:specs(assetSpecsResult.rows,row.code),publicProfile:{publicVisible:Boolean(row.public_visible),title:localized(row.public_title_zh,row.public_title_en),description:localized(row.public_description_zh,row.public_description_en),imageAssetId:row.image_asset_id,imageUrl:row.image_url??null,sortOrder:row.public_sort_order??0}};item.displayState=assetDisplayState(item);return item}).sort((a:any,b:any)=>natural(a.deviceTypeName,b.deviceTypeName)||natural(a.code,b.code));
      const assetCodesByPlatform=new Map<string,string[]>();for(const asset of assets){if(!asset.currentPlatformCode)continue;const codes=assetCodesByPlatform.get(asset.currentPlatformCode)??[];codes.push(asset.code);assetCodesByPlatform.set(asset.currentPlatformCode,codes);}
      const platforms=platformsResult.rows.map((row:any)=>({code:row.code,typeCode:row.type_code,name:localized(row.name_zh,row.name_en),description:localized(row.description_zh,row.description_en),status:row.status,location:row.location,maintainerUserId:row.maintainer_user_id,maintainerName:row.maintainer_name??"",commissionedAt:row.commissioned_at?String(row.commissioned_at).slice(0,10):"",specs:specs(platformSpecsResult.rows,row.code),publicProfile:{publicVisible:Boolean(row.public_visible),title:localized(row.public_title_zh,row.public_title_en),description:localized(row.public_description_zh,row.public_description_en),imageAssetId:row.image_asset_id,imageUrl:row.image_url??null,tags:row.tags??[],componentDisplayMode:row.component_display_mode??"summary",sortOrder:row.public_sort_order??0},assetCodes:(assetCodesByPlatform.get(row.code)??[]).sort(natural)}));
      const platformTypes=platformTypesResult.rows.map((row:any)=>({code:row.code,name:row.name,slots:slotsResult.rows.filter((slot:any)=>slot.platform_type_code===row.code).map((slot:any)=>({slotKey:slot.slot_key,name:localized(slot.name_zh,slot.name_en),deviceTypeCode:slot.device_type_code,required:slot.required,minCount:slot.min_count,maxCount:slot.max_count,sortOrder:slot.sort_order})),platforms:platforms.filter((item:any)=>item.typeCode===row.code).sort((a:any,b:any)=>natural(a.code,b.code))}));
      const count=(status:string)=>assets.filter((item:any)=>item.status===status).length;
      const snapshot={page:pageResult.rows[0]?.content_json??{},revision:revisionResult.rows[0]?.revision??"0",platformTypes,deviceTypes:deviceTypesResult.rows.map((row:any)=>({code:row.code,name:row.name,specDefinitions:definitionsResult.rows.filter((definition:any)=>definition.device_type_code===row.code).map((definition:any)=>({key:definition.key,label:localized(definition.label_zh,definition.label_en),unit:definition.unit,sortOrder:definition.sort_order}))})),platforms,assets,members:membersResult.rows.map((row:any)=>({id:row.id,username:row.username,displayName:row.display_name})),usageRequests:requestsResult.rows.map((row:any)=>({id:row.id,status:row.status,reason:row.reason,reviewNote:row.review_note,createdAt:row.created_at,reviewedAt:row.reviewed_at,assetCode:row.asset_code,assetName:localized(row.asset_name_zh,row.asset_name_en),requesterId:row.requester_id,requesterName:row.requester_name,reviewerName:row.reviewer_name??""})),stats:{totalPlatforms:platforms.length,activePlatforms:platforms.filter((item:any)=>item.status==="active").length,totalAssets:assets.length,idleAssets:assets.filter((item:any)=>item.displayState==="idle").length,inUseAssets:assets.filter((item:any)=>item.displayState==="in_use").length,mountedAssets:assets.filter((item:any)=>item.displayState==="mounted").length,maintenanceAssets:assets.filter((item:any)=>item.displayState==="maintenance").length,lentAssets:assets.filter((item:any)=>item.displayState==="lend").length,pendingRequests:requestsResult.rows.filter((row:any)=>row.status==="pending").length}};
      await client.query("COMMIT");return snapshot;
    }catch(error){primaryError=error;try{await client.query("ROLLBACK");}catch(cleanup){attachCleanupFailure(primaryError,cleanup);}}
    finally{try{client.release();}catch(cleanup){if(primaryError===undefined)throw cleanup;attachCleanupFailure(primaryError,cleanup);}}
    throw primaryError;
  }

  async function writeAsset(client:PoolClient,asset:LabAsset,code?:string,sourceProcurementRequestId?:string){
    const deviceType=await findDeviceType(client,asset.deviceTypeCode),typeId=deviceType.id;
    const platformId=asset.currentPlatformCode?await findId(client,"lab_platforms",asset.currentPlatformCode):null;
    const assignedUserId=asset.status==="in_use"?asset.assignedUserId:null;
    if(assignedUserId){const user=await client.query(`SELECT 1 FROM users WHERE id=$1 AND status='active'`,[assignedUserId]);if(!user.rowCount)throw new ConflictError("Assigned member not found");}
    const borrowerName=asset.status==="lend"?asset.borrowerName:"",borrowerContact=asset.status==="lend"?asset.borrowerContact:"";
    const condition=asset.condition??(asset.status==="maintenance"?"maintenance":asset.status==="retired"?"retired":"normal");
    const status=assignedUserId?"in_use":borrowerName?"lend":platformId?"mounted":"idle";
    const values=[asset.code,typeId,deviceType.name,asset.manufacturer??"",asset.model,asset.name.zh,asset.name.en,asset.description.zh,asset.description.en,asset.vendorSerial,status,condition,platformId,assignedUserId,borrowerName,borrowerContact,asset.storageLocation,asset.platformRole?.zh??"",asset.platformRole?.en??"",asset.platformSlot??null,asset.platformSortOrder??0,sourceProcurementRequestId??null];
    let assetId:string;
    if(code===undefined){const created=await client.query<{id:string}>(`INSERT INTO lab_assets(code,device_type_id,device_type_zh,device_type_en,manufacturer,model,name_zh,name_en,description_zh,description_en,vendor_serial,status,condition,current_platform_id,assigned_user_id,borrower_name,borrower_contact,storage_location,platform_role_zh,platform_role_en,platform_slot,platform_sort_order,mounted_at,source_procurement_request_id,share_scope,sort_order) VALUES($1,$2,$3,'',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,CASE WHEN $13::bigint IS NULL THEN NULL ELSE now() END,$22,'internal',0) RETURNING id`,values);assetId=created.rows[0].id;}
    else{const updated=await client.query<{id:string}>(`UPDATE lab_assets SET code=$1,device_type_id=$2,device_type_zh=$3,device_type_en='',manufacturer=$4,model=$5,name_zh=$6,name_en=$7,description_zh=$8,description_en=$9,vendor_serial=$10,status=$11,condition=$12,current_platform_id=$13,assigned_user_id=$14,borrower_name=$15,borrower_contact=$16,storage_location=$17,platform_role_zh=$18,platform_role_en=$19,platform_slot=$20,platform_sort_order=$21,mounted_at=CASE WHEN $13::bigint IS NULL THEN NULL WHEN current_platform_id IS DISTINCT FROM $13 THEN now() ELSE mounted_at END,updated_at=now() WHERE code=$23 RETURNING id`,[...values,code]);requireAffected(updated,"Asset");assetId=updated.rows[0].id;}
    await replaceSpecs(client,"lab_asset_specs","asset_id",assetId,asset.specs??[]);
    const profile=asset.publicProfile??{publicVisible:false,title:{zh:"",en:""},description:{zh:"",en:""},imageAssetId:null,sortOrder:0};
    await client.query(`INSERT INTO lab_asset_public_profiles(asset_id,public_visible,title_zh,title_en,description_zh,description_en,image_asset_id,sort_order,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()) ON CONFLICT(asset_id) DO UPDATE SET public_visible=EXCLUDED.public_visible,title_zh=EXCLUDED.title_zh,title_en=EXCLUDED.title_en,description_zh=EXCLUDED.description_zh,description_en=EXCLUDED.description_en,image_asset_id=EXCLUDED.image_asset_id,sort_order=EXCLUDED.sort_order,updated_at=now()`,[assetId,profile.publicVisible,profile.title.zh,profile.title.en,profile.description.zh,profile.description.en,profile.imageAssetId,profile.sortOrder]);
  }

  async function replaceSpecs(client:PoolClient,table:"lab_platform_specs"|"lab_asset_specs",ownerColumn:"platform_id"|"asset_id",ownerId:string,specs:any[]){await client.query(`DELETE FROM ${table} WHERE ${ownerColumn}=$1`,[ownerId]);for(const spec of specs)await client.query(`INSERT INTO ${table}(${ownerColumn},key,label_zh,label_en,value_zh,value_en,unit,public_visible,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[ownerId,spec.key,spec.label.zh,spec.label.en,spec.value.zh,spec.value.en,spec.unit,spec.publicVisible,spec.sortOrder]);}

  async function writePlatformDetails(client:PoolClient,platformId:string,item:LabPlatform){await replaceSpecs(client,"lab_platform_specs","platform_id",platformId,item.specs??[]);const profile=item.publicProfile??{publicVisible:false,title:{zh:"",en:""},description:{zh:"",en:""},imageAssetId:null,tags:[],componentDisplayMode:"summary",sortOrder:0};await client.query(`INSERT INTO lab_platform_public_profiles(platform_id,public_visible,title_zh,title_en,description_zh,description_en,image_asset_id,tags,component_display_mode,sort_order,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()) ON CONFLICT(platform_id) DO UPDATE SET public_visible=EXCLUDED.public_visible,title_zh=EXCLUDED.title_zh,title_en=EXCLUDED.title_en,description_zh=EXCLUDED.description_zh,description_en=EXCLUDED.description_en,image_asset_id=EXCLUDED.image_asset_id,tags=EXCLUDED.tags,component_display_mode=EXCLUDED.component_display_mode,sort_order=EXCLUDED.sort_order,updated_at=now()`,[platformId,profile.publicVisible,profile.title.zh,profile.title.en,profile.description.zh,profile.description.en,profile.imageAssetId,profile.tags,profile.componentDisplayMode,profile.sortOrder]);}

  async function validateImportRows(client:PoolClient,rows:AssetImportRow[],createMissingDeviceTypes=false):Promise<AssetImportReport>{
    const codes=rows.map((row)=>row.code),serials=rows.map((row)=>row.vendorSerial.trim().toLocaleLowerCase()).filter(Boolean);
    const [typesResult,platformsResult,existingResult]=await Promise.all([
      client.query<{code:string}>(`SELECT code FROM lab_device_types WHERE code=ANY($1::text[])`,[[...new Set(rows.map((row)=>row.deviceTypeCode))]]),
      client.query<{code:string}>(`SELECT code FROM lab_platforms WHERE code=ANY($1::text[])`,[[...new Set(rows.map((row)=>row.platformCode).filter(Boolean))]]),
      client.query<{code:string;vendor_serial:string}>(`SELECT code,vendor_serial FROM lab_assets WHERE code=ANY($1::text[]) OR LOWER(NULLIF(BTRIM(vendor_serial),''))=ANY($2::text[])`,[codes,serials]),
    ]);
    const knownTypes=new Set(typesResult.rows.map((row)=>row.code)),knownPlatforms=new Set(platformsResult.rows.map((row)=>row.code));
    const existingCodes=new Set(existingResult.rows.map((row)=>row.code)),existingSerials=new Set(existingResult.rows.map((row)=>row.vendor_serial?.trim().toLocaleLowerCase()).filter(Boolean));
    const codeCounts=new Map<string,number>(),serialCounts=new Map<string,number>();
    for(const row of rows){codeCounts.set(row.code,(codeCounts.get(row.code)??0)+1);const serial=row.vendorSerial.trim().toLocaleLowerCase();if(serial)serialCounts.set(serial,(serialCounts.get(serial)??0)+1);}
    const resultRows=rows.map((row,index)=>{const issues:AssetImportIssue[]=[];const serial=row.vendorSerial.trim().toLocaleLowerCase();
      if((codeCounts.get(row.code)??0)>1)issues.push({field:"code",message:"文件内资产编号重复",severity:"error"});
      if(existingCodes.has(row.code))issues.push({field:"code",message:"资产编号已存在",severity:"error"});
      if(serial&&(serialCounts.get(serial)??0)>1)issues.push({field:"vendorSerial",message:"文件内厂商序列号重复",severity:"error"});
      if(serial&&existingSerials.has(serial))issues.push({field:"vendorSerial",message:"厂商序列号已存在",severity:"error"});
      if(!["idle","mounted","maintenance","retired"].includes(row.status))issues.push({field:"status",message:"状态无效，仅支持 idle、mounted、maintenance、retired",severity:"error"});
      if(!knownTypes.has(row.deviceTypeCode))issues.push({field:"deviceTypeCode",message:createMissingDeviceTypes?"设备类型不存在，提交时将自动创建":"设备类型不存在",severity:createMissingDeviceTypes?"warning":"error"});
      if(row.platformCode&&!knownPlatforms.has(row.platformCode))issues.push({field:"platformCode",message:"实验平台不存在",severity:"error"});
      if(row.status==="mounted"&&!row.platformCode)issues.push({field:"platformCode",message:"已装载设备必须指定实验平台",severity:"error"});
      if(row.status!=="mounted"&&row.platformCode)issues.push({field:"platformCode",message:"只有已装载设备可以指定实验平台",severity:"error"});
      if(!row.vendorSerial)issues.push({field:"vendorSerial",message:"未填写厂商序列号",severity:"warning"});
      if(!row.model)issues.push({field:"model",message:"未填写设备型号",severity:"warning"});
      if(!row.storageLocation&&!row.platformCode)issues.push({field:"storageLocation",message:"未填写存放位置",severity:"warning"});
      return{index:index+1,row,issues};});
    const errors=resultRows.filter((row)=>row.issues.some((issue)=>issue.severity==="error")).length,warnings=resultRows.filter((row)=>!row.issues.some((issue)=>issue.severity==="error")&&row.issues.some((issue)=>issue.severity==="warning")).length;
    return{summary:{total:rows.length,valid:rows.length-errors-warnings,warnings,errors},rows:resultRows};
  }

  return {
    getSnapshot:dependencies.getSnapshot??getSnapshot,
    createDeviceType:(item:LabDeviceType,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.device-type.create",targetType:"lab_device_types",targetId:item.code},async(client)=>{const duplicateType=await client.query(`SELECT 1 FROM lab_device_types WHERE code=$1 OR name=$2 LIMIT 1`,[item.code,item.name]);if(duplicateType.rowCount)throw new ConflictError("设备类型代码或名称已存在");await client.query(`INSERT INTO lab_device_types(code,name) VALUES($1,$2)`,[item.code,item.name]);}),
    createPlatformType:(item:LabPlatformType,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform-type.create",targetType:"lab_platform_types",targetId:item.code},async(client)=>{if(await duplicate(client,"lab_platform_types",item.code))throw new ConflictError("Platform type code already exists");await client.query(`INSERT INTO lab_platform_types(code,name_zh,name_en,description_zh,description_en,sort_order) VALUES($1,$2,'','','',0)`,[item.code,item.name]);}),
    updatePlatformType:(code:string,item:LabPlatformType,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform-type.update",targetType:"lab_platform_types",targetId:code},async(client)=>{if(await duplicate(client,"lab_platform_types",item.code,code))throw new ConflictError("Platform type code already exists");requireAffected(await client.query(`UPDATE lab_platform_types SET code=$1,name_zh=$2,name_en='',updated_at=now() WHERE code=$3`,[item.code,item.name,code]),"Platform type");}),
    deletePlatformType:(code:string,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform-type.delete",targetType:"lab_platform_types",targetId:code},async(client)=>{const id=await findId(client,"lab_platform_types",code);const referenced=await client.query(`SELECT 1 FROM lab_platforms WHERE type_id=$1 LIMIT 1`,[id]);if(referenced.rowCount)throw new ConflictError("Platform type is still referenced");requireAffected(await client.query(`DELETE FROM lab_platform_types WHERE id=$1`,[id]),"Platform type");}),
    createAsset:(item:LabAsset,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.asset.create",targetType:"lab_assets",targetId:item.code},async(client)=>{if(await duplicate(client,"lab_assets",item.code))throw new ConflictError("Asset code already exists");await writeAsset(client,item);}),
    batchAssets:(input:AssetBatchInput,actorId:string)=>transaction(async(client)=>{
      const revision=await claimRevision(client,input.expectedRevision);
      const locked=await client.query<{code:string}>(`SELECT code FROM lab_assets WHERE code=ANY($1::text[]) FOR UPDATE`,[input.assetCodes]);
      if(locked.rows.length!==input.assetCodes.length)throw new ConflictError("One or more selected assets do not exist");
      if(input.action==="set_status"){
        await client.query(`UPDATE lab_assets SET condition=CASE WHEN $2='idle' THEN 'normal' ELSE $2 END,updated_at=now() WHERE code=ANY($1::text[])`,[input.assetCodes,input.value]);
      }else if(input.action==="set_device_type"){
        const deviceType=await findDeviceType(client,input.value);
        await client.query(`UPDATE lab_assets SET device_type_id=$2,device_type_zh=$3,device_type_en='',updated_at=now() WHERE code=ANY($1::text[])`,[input.assetCodes,deviceType.id,deviceType.name]);
      }else{
        await client.query(`UPDATE lab_assets SET storage_location=$2,updated_at=now() WHERE code=ANY($1::text[])`,[input.assetCodes,input.value]);
      }
      await audit(client,{actorId,action:`lab-assets.asset.batch.${input.action}`,targetType:"lab_assets",targetId:"batch",revision,detail:{assetCodes:input.assetCodes,value:input.value}});
      return revision;
    }),
    validateAssetImport:(input:AssetImportInput)=>transaction(async(client)=>{const current=await client.query<{revision:string}>(`SELECT revision::text revision FROM site_content_revisions WHERE module_key='lab-assets'`);if(current.rows[0]?.revision!==input.expectedRevision)throw new RevisionConflictError();return validateImportRows(client,input.rows,Boolean(input.createMissingDeviceTypes));}),
    commitAssetImport:(input:AssetImportInput,actorId:string)=>transaction(async(client)=>{const revision=await claimRevision(client,input.expectedRevision);await client.query(`SELECT pg_advisory_xact_lock(hashtext('lab-assets-import'))`);const procurementIds=[...new Set(input.rows.map((row)=>row.procurementRequestId).filter((id):id is string=>Boolean(id)))];if(procurementIds.length){const sources=await client.query<{id:string}>(`SELECT id FROM procurement_requests WHERE id=ANY($1::uuid[]) AND status IN ('received','closed') FOR SHARE`,[procurementIds]);if(sources.rows.length!==procurementIds.length)throw new ConflictError("采购来源不存在或尚未确认到货");}if(input.createMissingDeviceTypes){const requested=[...new Set(input.rows.map((row)=>row.deviceTypeCode))];await client.query(`INSERT INTO lab_device_types(code,name) SELECT code,code FROM unnest($1::text[]) code ON CONFLICT DO NOTHING`,[requested]);}const report=await validateImportRows(client,input.rows,Boolean(input.createMissingDeviceTypes));if(report.summary.errors)throw new ImportValidationError(report);for(const row of input.rows){await writeAsset(client,{code:row.code,deviceTypeCode:row.deviceTypeCode,model:row.model,name:{zh:row.nameZh,en:row.nameEn},description:{zh:row.descriptionZh,en:""},vendorSerial:row.vendorSerial,status:row.status as LabAsset["status"],currentPlatformCode:row.status==="mounted"?row.platformCode:null,assignedUserId:null,borrowerName:"",borrowerContact:"",storageLocation:row.storageLocation||null},undefined,row.procurementRequestId);}await audit(client,{actorId,action:"lab-assets.asset.import",targetType:"lab_assets",targetId:"batch",revision,detail:{count:input.rows.length,procurementRequestIds:procurementIds,createdMissingDeviceTypes:Boolean(input.createMissingDeviceTypes)}});return revision;}),
    updateAsset:(code:string,item:LabAsset,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.asset.update",targetType:"lab_assets",targetId:code},async(client)=>{if(await duplicate(client,"lab_assets",item.code,code))throw new ConflictError("Asset code already exists");await writeAsset(client,item,code);}),
    deleteAsset:(code:string,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.asset.delete",targetType:"lab_assets",targetId:code},async(client)=>requireAffected(await client.query(`DELETE FROM lab_assets WHERE code=$1`,[code]),"Asset")),
    createPlatform:(item:LabPlatform,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform.create",targetType:"lab_platforms",targetId:item.code},async(client)=>{if(await duplicate(client,"lab_platforms",item.code))throw new ConflictError("Platform code already exists");const typeId=await findId(client,"lab_platform_types",item.typeCode);const created=await client.query<{id:string}>(`INSERT INTO lab_platforms(code,type_id,name_zh,name_en,description_zh,description_en,status,location,maintainer_user_id,commissioned_at,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,0) RETURNING id`,[item.code,typeId,item.name.zh,item.name.en,item.description.zh,item.description.en,item.status,item.location??null,item.maintainerUserId??null,item.commissionedAt||null]);await writePlatformDetails(client,created.rows[0].id,item);}),
    updatePlatform:(code:string,item:LabPlatform,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform.update",targetType:"lab_platforms",targetId:code},async(client)=>{if(await duplicate(client,"lab_platforms",item.code,code))throw new ConflictError("Platform code already exists");const typeId=await findId(client,"lab_platform_types",item.typeCode);const updated=await client.query<{id:string}>(`UPDATE lab_platforms SET code=$1,type_id=$2,name_zh=$3,name_en=$4,description_zh=$5,description_en=$6,status=$7,location=$8,maintainer_user_id=$9,commissioned_at=$10,updated_at=now() WHERE code=$11 RETURNING id`,[item.code,typeId,item.name.zh,item.name.en,item.description.zh,item.description.en,item.status,item.location??null,item.maintainerUserId??null,item.commissionedAt||null,code]);requireAffected(updated,"Platform");await writePlatformDetails(client,updated.rows[0].id,item);}),
    deletePlatform:(code:string,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform.delete",targetType:"lab_platforms",targetId:code},async(client)=>{const id=await findId(client,"lab_platforms",code);const components=await client.query(`SELECT 1 FROM lab_assets WHERE current_platform_id=$1 LIMIT 1`,[id]);if(components.rowCount)throw new ConflictError("请先拆除或转移组成设备");requireAffected(await client.query(`DELETE FROM lab_platforms WHERE id=$1`,[id]),"Platform");}),
    addPlatformComponent:(platformCode:string,input:{assetCode:string;role:LocalizedText;slot:string|null;sortOrder:number;expectedRevision:string},actorId:string)=>mutate({expectedRevision:input.expectedRevision,actorId,action:"platform.component.add",targetType:"lab_platforms",targetId:platformCode,detail:{assetCode:input.assetCode}},async(client)=>{const platformId=await findId(client,"lab_platforms",platformCode);const asset=await client.query<any>(`SELECT id,status,condition,current_platform_id FROM lab_assets WHERE code=$1 FOR UPDATE`,[input.assetCode]);if(!asset.rowCount)throw new ConflictError("Asset not found");const row=asset.rows[0];if(row.current_platform_id===platformId)return;if(row.current_platform_id)throw new ConflictError("设备已属于其他平台，请使用转移操作");if(row.status==="in_use")throw new ConflictError("使用中的设备不能直接添加");if(row.status==="lend")throw new ConflictError("借出设备不能添加");if(row.condition==="retired")throw new ConflictError("已报废设备不能添加");await client.query(`UPDATE lab_assets SET current_platform_id=$2,status='mounted',platform_role_zh=$3,platform_role_en=$4,platform_slot=$5,platform_sort_order=$6,mounted_at=now(),updated_at=now() WHERE id=$1`,[row.id,platformId,input.role.zh,input.role.en,input.slot,input.sortOrder]);}),
    updatePlatformComponent:(platformCode:string,assetCode:string,input:{role:LocalizedText;slot:string|null;sortOrder:number;expectedRevision:string},actorId:string)=>mutate({expectedRevision:input.expectedRevision,actorId,action:"platform.component.role.update",targetType:"lab_assets",targetId:assetCode,detail:{platformCode}},async(client)=>{const result=await client.query(`UPDATE lab_assets a SET platform_role_zh=$3,platform_role_en=$4,platform_slot=$5,platform_sort_order=$6,updated_at=now() FROM lab_platforms p WHERE a.code=$1 AND p.code=$2 AND a.current_platform_id=p.id`,[assetCode,platformCode,input.role.zh,input.role.en,input.slot,input.sortOrder]);requireAffected(result,"Platform component");}),
    removePlatformComponent:(platformCode:string,assetCode:string,input:{storageLocation:string;expectedRevision:string},actorId:string)=>mutate({expectedRevision:input.expectedRevision,actorId,action:"platform.component.remove",targetType:"lab_assets",targetId:assetCode,detail:{platformCode}},async(client)=>{const result=await client.query(`UPDATE lab_assets a SET current_platform_id=NULL,status='idle',platform_role_zh='',platform_role_en='',platform_slot=NULL,platform_sort_order=0,mounted_at=NULL,storage_location=$3,updated_at=now() FROM lab_platforms p WHERE a.code=$1 AND p.code=$2 AND a.current_platform_id=p.id`,[assetCode,platformCode,input.storageLocation]);requireAffected(result,"Platform component");}),
    transferPlatformComponent:(platformCode:string,assetCode:string,input:{role:LocalizedText;slot:string|null;sortOrder:number;expectedRevision:string},actorId:string)=>mutate({expectedRevision:input.expectedRevision,actorId,action:"platform.component.transfer",targetType:"lab_assets",targetId:assetCode,detail:{toPlatform:platformCode}},async(client)=>{const platformId=await findId(client,"lab_platforms",platformCode);const asset=await client.query<any>(`SELECT id,status,condition,current_platform_id FROM lab_assets WHERE code=$1 FOR UPDATE`,[assetCode]);if(!asset.rowCount)throw new ConflictError("Asset not found");const row=asset.rows[0];if(!row.current_platform_id)throw new ConflictError("设备当前不属于其他平台，请使用添加操作");if(row.current_platform_id===platformId)throw new ConflictError("设备已属于当前平台");if(row.status==="in_use"||row.status==="lend"||row.condition==="retired")throw new ConflictError("该设备当前不可转移");await client.query(`UPDATE lab_assets SET current_platform_id=$2,status='mounted',platform_role_zh=$3,platform_role_en=$4,platform_slot=$5,platform_sort_order=$6,mounted_at=now(),updated_at=now() WHERE id=$1`,[row.id,platformId,input.role.zh,input.role.en,input.slot,input.sortOrder]);}),
    replacePlatformTypeSlots:(code:string,input:{slots:any[];expectedRevision:string},actorId:string)=>mutate({expectedRevision:input.expectedRevision,actorId,action:"lab-assets.platform-type.slots.update",targetType:"lab_platform_types",targetId:code},async(client)=>{const typeId=await findId(client,"lab_platform_types",code);await client.query(`DELETE FROM lab_platform_type_slots WHERE platform_type_id=$1`,[typeId]);for(const slot of input.slots){const deviceTypeId=slot.deviceTypeCode?await findId(client,"lab_device_types",slot.deviceTypeCode):null;await client.query(`INSERT INTO lab_platform_type_slots(platform_type_id,slot_key,name_zh,name_en,device_type_id,required,min_count,max_count,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[typeId,slot.slotKey,slot.name.zh,slot.name.en,deviceTypeId,slot.required,slot.minCount,slot.maxCount,slot.sortOrder]);}}),
    replaceDeviceTypeSpecDefinitions:(code:string,input:{definitions:any[];expectedRevision:string},actorId:string)=>mutate({expectedRevision:input.expectedRevision,actorId,action:"lab-assets.device-type.spec-definitions.update",targetType:"lab_device_types",targetId:code},async(client)=>{const typeId=await findId(client,"lab_device_types",code);await client.query(`DELETE FROM lab_device_type_spec_definitions WHERE device_type_id=$1`,[typeId]);for(const definition of input.definitions)await client.query(`INSERT INTO lab_device_type_spec_definitions(device_type_id,key,label_zh,label_en,unit,sort_order) VALUES($1,$2,$3,$4,$5,$6)`,[typeId,definition.key,definition.label.zh,definition.label.en,definition.unit,definition.sortOrder]);}),
    submitUsageRequest:(assetCode:string,reason:string,revision:string,actorId:string)=>transaction(async(client)=>{const nextRevision=await claimRevision(client,revision);const asset=await client.query<{id:string;status:string}>(`SELECT id,status FROM lab_assets WHERE code=$1 FOR UPDATE`,[assetCode]);if(!asset.rowCount)throw new ConflictError("Asset not found");const existing=await client.query(`SELECT 1 FROM lab_asset_usage_requests WHERE asset_id=$1 AND requester_id=$2 AND status='pending' LIMIT 1`,[asset.rows[0].id,actorId]);if(existing.rowCount)throw new ConflictError("你已经提交过该设备的待审批申请");const autoApproved=asset.rows[0].status==="idle";const created=await client.query<{id:string}>(`INSERT INTO lab_asset_usage_requests(asset_id,requester_id,status,reason,reviewed_by,reviewed_at) VALUES($1,$2,$3,$4,$5,CASE WHEN $3='approved' THEN now() ELSE NULL END) RETURNING id`,[asset.rows[0].id,actorId,autoApproved?"approved":"pending",reason,autoApproved?actorId:null]);if(autoApproved)await client.query(`UPDATE lab_assets SET status='in_use',assigned_user_id=$2,current_platform_id=NULL,borrower_name='',borrower_contact='',updated_at=now() WHERE id=$1`,[asset.rows[0].id,actorId]);await audit(client,{actorId,action:"lab-assets.usage-request.create",targetType:"lab_asset_usage_requests",targetId:created.rows[0].id,revision:nextRevision,detail:{autoApproved}});await notify(client,{eventKey:`asset-usage:${created.rows[0].id}:created`,type:"asset.usage.created",title:autoApproved?"设备使用申请已自动批准":"有新的设备使用申请",message:assetCode,href:`/console/lab-assets?asset=${encodeURIComponent(assetCode)}`,userIds:autoApproved?[actorId]:await managers(client,actorId)});return{revision:nextRevision,id:created.rows[0].id,status:autoApproved?"approved":"pending"};}),
    reviewUsageRequest:(id:string,input:UsageReview,revision:string,actorId:string)=>transaction(async(client)=>{const nextRevision=await claimRevision(client,revision);const request=await client.query<{asset_id:string;status:string;requester_id:string}>(`SELECT asset_id,status,requester_id FROM lab_asset_usage_requests WHERE id=$1 FOR UPDATE`,[id]);if(!request.rowCount)throw new ConflictError("Usage request not found");if(request.rows[0].status!=="pending")throw new ConflictError("Usage request has already been processed");if(input.action==="approve"){await client.query(`SELECT id FROM lab_assets WHERE id=$1 FOR UPDATE`,[request.rows[0].asset_id]);await client.query(`UPDATE lab_assets SET status='in_use',assigned_user_id=$2,current_platform_id=NULL,borrower_name='',borrower_contact='',updated_at=now() WHERE id=$1`,[request.rows[0].asset_id,request.rows[0].requester_id]);await client.query(`UPDATE lab_asset_usage_requests SET status='rejected',review_note='设备已分配给其他成员',reviewed_by=$3,reviewed_at=now(),updated_at=now() WHERE asset_id=$1 AND status='pending' AND id<>$2`,[request.rows[0].asset_id,id,actorId]);}await client.query(`UPDATE lab_asset_usage_requests SET status=$2,review_note=$3,reviewed_by=$4,reviewed_at=now(),updated_at=now() WHERE id=$1`,[id,input.action==="approve"?"approved":"rejected",input.note,actorId]);await audit(client,{actorId,action:`lab-assets.usage-request.${input.action}`,targetType:"lab_asset_usage_requests",targetId:id,revision:nextRevision});await notify(client,{eventKey:`asset-usage:${id}:${input.action}`,type:`asset.usage.${input.action}`,title:input.action==="approve"?"设备使用申请已批准":"设备使用申请已驳回",message:input.note,href:"/console/lab-assets",userIds:[request.rows[0].requester_id]});return{revision:nextRevision,status:input.action==="approve"?"approved":"rejected"};}),
    listInventoryBatches:()=>transaction(async(client)=>{const batches=await client.query<any>(`SELECT batches.*,count(items.asset_id)::integer item_count,count(items.scanned_at)::integer scanned_count FROM lab_asset_inventory_batches batches LEFT JOIN lab_asset_inventory_items items ON items.batch_id=batches.id GROUP BY batches.id ORDER BY batches.created_at DESC LIMIT 100`);return batches.rows.map((row:any)=>({id:row.id,name:row.name,status:row.status,expectedCount:row.expected_count,itemCount:row.item_count,scannedCount:row.scanned_count,createdAt:row.created_at,completedAt:row.completed_at}));}),
    getInventoryBatch:(id:string)=>transaction(async(client)=>{const batch=await client.query<any>(`SELECT * FROM lab_asset_inventory_batches WHERE id=$1`,[id]);if(!batch.rowCount)throw new ConflictError("Inventory batch not found");const items=await client.query<any>(`SELECT asset_code_snapshot code,asset_name_snapshot name,scanned_at,scanned_by FROM lab_asset_inventory_items WHERE batch_id=$1 ORDER BY asset_code_snapshot`,[id]);return{...batch.rows[0],items:items.rows.map((row:any)=>({code:row.code,name:row.name,scannedAt:row.scanned_at,scannedBy:row.scanned_by})),scannedCount:items.rows.filter((row:any)=>row.scanned_at).length,missingCount:items.rows.filter((row:any)=>!row.scanned_at).length};}),
    createInventoryBatch:(name:string,assetCodes:string[],actorId:string)=>transaction(async(client)=>{const assets=await client.query<any>(assetCodes.length?`SELECT id,code,COALESCE(NULLIF(name_zh,''),NULLIF(name_en,''),code) name FROM lab_assets WHERE code=ANY($1::text[]) ORDER BY code FOR SHARE`:`SELECT id,code,COALESCE(NULLIF(name_zh,''),NULLIF(name_en,''),code) name FROM lab_assets WHERE status<>'retired' ORDER BY code FOR SHARE`,assetCodes.length?[assetCodes]:[]);if(assetCodes.length&&assets.rows.length!==new Set(assetCodes).size)throw new ConflictError("One or more assets do not exist");const batch=await client.query<{id:string}>(`INSERT INTO lab_asset_inventory_batches(name,created_by,expected_count) VALUES($1,$2,$3) RETURNING id`,[name,actorId,assets.rows.length]);for(const asset of assets.rows)await client.query(`INSERT INTO lab_asset_inventory_items(batch_id,asset_id,asset_code_snapshot,asset_name_snapshot) VALUES($1,$2,$3,$4)`,[batch.rows[0].id,asset.id,asset.code,asset.name]);await audit(client,{actorId,action:"lab-assets.inventory.create",targetType:"lab_asset_inventory_batch",targetId:batch.rows[0].id,revision:"0",detail:{count:assets.rows.length}});return{id:batch.rows[0].id,expectedCount:assets.rows.length};}),
    scanInventoryAsset:(id:string,assetCode:string,actorId:string)=>transaction(async(client)=>{const batch=await client.query<{status:string}>(`SELECT status FROM lab_asset_inventory_batches WHERE id=$1 FOR UPDATE`,[id]);if(!batch.rowCount)throw new ConflictError("Inventory batch not found");if(batch.rows[0].status!=="open")throw new ConflictError("Inventory batch is completed");const scanned=await client.query<any>(`UPDATE lab_asset_inventory_items SET scanned_at=COALESCE(scanned_at,now()),scanned_by=COALESCE(scanned_by,$3) WHERE batch_id=$1 AND asset_code_snapshot=$2 RETURNING scanned_at`,[id,assetCode,actorId]);if(!scanned.rowCount)throw new ConflictError("Asset is not included in this inventory batch");return{assetCode,scannedAt:scanned.rows[0].scanned_at};}),
    completeInventoryBatch:(id:string,actorId:string)=>transaction(async(client)=>{const batch=await client.query<{status:string}>(`SELECT status FROM lab_asset_inventory_batches WHERE id=$1 FOR UPDATE`,[id]);if(!batch.rowCount)throw new ConflictError("Inventory batch not found");await client.query(`UPDATE lab_asset_inventory_batches SET status='completed',completed_at=COALESCE(completed_at,now()),updated_at=now() WHERE id=$1`,[id]);const counts=await client.query<any>(`SELECT count(*)::integer expected,count(scanned_at)::integer scanned FROM lab_asset_inventory_items WHERE batch_id=$1`,[id]);await audit(client,{actorId,action:"lab-assets.inventory.complete",targetType:"lab_asset_inventory_batch",targetId:id,revision:"0",detail:counts.rows[0]});return counts.rows[0];}),
    updatePage:(page:unknown,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.page.update",targetType:"page_content",targetId:"lab_assets_page"},async(client)=>{await client.query(`INSERT INTO page_content(page_key,content_json,updated_at) VALUES('lab_assets_page',$1::jsonb,now()) ON CONFLICT(page_key) DO UPDATE SET content_json=EXCLUDED.content_json,updated_at=now()`,[JSON.stringify(page)]);}),
    // Legacy note endpoints remain available during the console transition.
    addAssetNote:(code:string,note:LabNote,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.asset-note.create",targetType:"lab_asset_notes",targetId:code},async(client)=>requireAffected(await client.query(`INSERT INTO lab_asset_notes(asset_id,sort_order,content_zh,content_en) SELECT id,$1,$2,$3 FROM lab_assets WHERE code=$4`,[note.sortOrder,note.content.zh,note.content.en,code]),"Asset")),
    addPlatformNote:(code:string,note:LabNote,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform-note.create",targetType:"lab_platform_notes",targetId:code},async(client)=>requireAffected(await client.query(`INSERT INTO lab_platform_notes(platform_id,sort_order,content_zh,content_en) SELECT id,$1,$2,$3 FROM lab_platforms WHERE code=$4`,[note.sortOrder,note.content.zh,note.content.en,code]),"Platform")),
    deleteAssetNote:(code:string,noteId:string,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.asset-note.delete",targetType:"lab_asset_notes",targetId:noteId},async(client)=>requireAffected(await client.query(`DELETE FROM lab_asset_notes n USING lab_assets a WHERE n.id=$1::bigint AND n.asset_id=a.id AND a.code=$2`,[noteId,code]),"Asset note")),
    deletePlatformNote:(code:string,noteId:string,revision:string,actorId:string)=>mutate({expectedRevision:revision,actorId,action:"lab-assets.platform-note.delete",targetType:"lab_platform_notes",targetId:noteId},async(client)=>requireAffected(await client.query(`DELETE FROM lab_platform_notes n USING lab_platforms p WHERE n.id=$1::bigint AND n.platform_id=p.id AND p.code=$2`,[noteId,code]),"Platform note")),
  };
}

export type LabAssetsService=ReturnType<typeof createLabAssetsService>;
