import assert from "node:assert/strict";
import test from "node:test";
import { ConflictError,createLabAssetsService,RevisionConflictError,type LabAsset,type LabPlatform } from "./labAssetsService.js";

type Call={sql:string;values?:readonly unknown[]};type Result={rowCount:number;rows:Record<string,any>[]};
class FakeClient{calls:Call[]=[];released=false;constructor(private respond:(call:Call)=>Result=defaultResponse){}async query(sql:string,values?:readonly unknown[]){const call={sql,values};this.calls.push(call);return this.respond(call)}release(){this.released=true}}
function defaultResponse({sql}:Call):Result{if(sql.includes("UPDATE site_content_revisions"))return{rowCount:1,rows:[{revision:"4"}]};if(sql.includes("SELECT 1 FROM lab_"))return{rowCount:0,rows:[]};if(sql.includes("SELECT id FROM lab_platforms"))return{rowCount:1,rows:[{id:"22"}]};if(sql.includes("SELECT id FROM lab_platform_types"))return{rowCount:1,rows:[{id:"11"}]};if(sql.includes("SELECT id,name FROM lab_device_types"))return{rowCount:1,rows:[{id:"33",name:"相机"}]};if(sql.includes("INSERT INTO lab_platforms")&&sql.includes("RETURNING id"))return{rowCount:1,rows:[{id:"22"}]};if(sql.includes("UPDATE lab_platforms")&&sql.includes("RETURNING id"))return{rowCount:1,rows:[{id:"22"}]};if(sql.includes("INSERT INTO lab_asset_usage_requests"))return{rowCount:1,rows:[{id:"request-1"}]};return{rowCount:1,rows:[]}}
const asset=(overrides:Partial<LabAsset>={}):LabAsset=>({code:"CAM-1",deviceTypeCode:"camera",model:"D455",name:{zh:"相机",en:"Camera"},description:{zh:"前置",en:"Front"},vendorSerial:"SN-1",status:"mounted",currentPlatformCode:"DOG-2",assignedUserId:null,borrowerName:"",borrowerContact:"",...overrides});
const platform=(overrides:Partial<LabPlatform>={}):LabPlatform=>({code:"DOG-2",typeCode:"robot",name:{zh:"机器狗",en:"Robot dog"},description:{zh:"四足平台",en:"Quadruped"},status:"active",assetCodes:["CAM-1"],...overrides});
const serviceWith=(client:FakeClient)=>createLabAssetsService({connect:async()=>client} as never);const find=(client:FakeClient,fragment:string)=>client.calls.find((call)=>call.sql.includes(fragment));

test("snapshot exposes devices, platforms, members, requests, and direct relationships",async()=>{const client=new FakeClient(({sql})=>{if(sql.includes("FROM page_content"))return{rowCount:1,rows:[{content_json:{}}]};if(sql.includes("FROM site_content_revisions"))return{rowCount:1,rows:[{revision:"9"}]};if(sql.includes("FROM lab_platform_types"))return{rowCount:1,rows:[{code:"robot",name:"机器人"}]};if(sql.includes("FROM lab_device_types"))return{rowCount:1,rows:[{code:"camera",name:"相机"}]};if(sql.includes("FROM lab_platforms p"))return{rowCount:1,rows:[{code:"DOG-2",type_code:"robot",name_zh:"机器狗",name_en:"Robot dog",description_zh:"四足",description_en:"Quadruped",status:"active"}]};if(sql.includes("FROM lab_asset_usage_requests"))return{rowCount:1,rows:[{id:"request-1",status:"pending",reason:"实验",review_note:"",created_at:new Date(),reviewed_at:null,asset_code:"CAM-1",asset_name_zh:"相机",asset_name_en:"Camera",requester_id:"user-2",requester_name:"张三",reviewer_name:null}]};if(sql.includes("FROM lab_assets a"))return{rowCount:2,rows:[{code:"CAM-1",device_type_code:"camera",device_type_name:"相机",model:"D455",name_zh:"相机",name_en:"Camera",description_zh:"前置",description_en:"Front",vendor_serial:"SN-1",status:"mounted",current_platform_code:"DOG-2",assigned_user_id:null,assigned_user_name:null,borrower_name:"",borrower_contact:""},{code:"LIDAR-1",device_type_code:"lidar",device_type_name:"雷达",model:"M1",name_zh:"雷达",name_en:"Lidar",description_zh:"",description_en:"",vendor_serial:"SN-2",status:"in_use",current_platform_code:null,assigned_user_id:"user-2",assigned_user_name:"张三",borrower_name:"",borrower_contact:""}]};if(sql.includes("FROM users WHERE status"))return{rowCount:1,rows:[{id:"user-2",username:"zhang",display_name:"张三"}]};return defaultResponse({sql})});const snapshot=await serviceWith(client).getSnapshot({id:"admin",canManage:true});assert.equal(snapshot.revision,"9");assert.deepEqual(snapshot.platforms[0].assetCodes,["CAM-1"]);assert.equal(snapshot.assets.find((item:any)=>item.code==="LIDAR-1")?.assignedUserName,"张三");assert.equal(snapshot.members.length,1);assert.equal(snapshot.usageRequests.length,1);assert.equal(snapshot.stats.inUseAssets,1);assert.match(client.calls.find((call)=>call.sql.includes("FROM lab_platforms p"))!.sql,/COALESCE\(NULLIF\(t\.name_zh,''\),NULLIF\(t\.name_en,''\),t\.code\)/);assert.equal(client.calls[0].sql,"BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");assert.equal(client.calls.at(-1)?.sql,"COMMIT")});

test("asset status fields are normalized when persisted",async()=>{for(const item of[asset(),asset({status:"in_use",currentPlatformCode:null,assignedUserId:"00000000-0000-4000-8000-000000000001"}),asset({status:"lend",currentPlatformCode:null,borrowerName:"李四",borrowerContact:"13800000000"})]){const client=new FakeClient();await serviceWith(client).createAsset(item,"3","admin");const insert=find(client,"INSERT INTO lab_assets");assert.ok(insert);if(item.status==="mounted")assert.equal(insert?.values?.[10],"22");if(item.status==="in_use")assert.equal(insert?.values?.[11],item.assignedUserId);if(item.status==="lend")assert.deepEqual(insert?.values?.slice(12,14),["李四","13800000000"]);}});

test("platform editing mounts selected devices and releases removed devices to idle",async()=>{const client=new FakeClient(({sql})=>{if(sql.includes("SELECT id,code FROM lab_assets"))return{rowCount:2,rows:[{id:"1",code:"CAM-1"},{id:"2",code:"OLD-1"}]};return defaultResponse({sql})});await serviceWith(client).updatePlatform("DOG-1",platform(),"3","admin");assert.ok(find(client,"current_platform_id=NULL,status='idle'"));assert.ok(find(client,"current_platform_id=$1,status='mounted'"));assert.deepEqual(find(client,"code=ANY($2::text[])")?.values?.[1],["CAM-1"])});

test("removing a platform releases its mounted devices before deletion",async()=>{const client=new FakeClient();await serviceWith(client).deletePlatform("DOG-2","3","admin");assert.ok(find(client,"UPDATE lab_assets SET current_platform_id=NULL,status='idle'"));assert.ok(find(client,"DELETE FROM lab_platforms"))});

test("idle usage requests auto approve and assign the requester",async()=>{const client=new FakeClient(({sql})=>{if(sql.includes("SELECT id,status FROM lab_assets"))return{rowCount:1,rows:[{id:"asset-1",status:"idle"}]};return defaultResponse({sql})});const result=await serviceWith(client).submitUsageRequest("CAM-1","实验","3","user-1");assert.equal(result.status,"approved");assert.ok(find(client,"status='in_use'"));assert.ok(client.calls.some((call)=>call.sql.includes("INSERT INTO audit_logs")&&String(call.values?.[1]).includes("usage-request.create")))});

test("non-idle usage requests wait for review",async()=>{const client=new FakeClient(({sql})=>sql.includes("SELECT id,status FROM lab_assets")?{rowCount:1,rows:[{id:"asset-1",status:"mounted"}]}:defaultResponse({sql}));const result=await serviceWith(client).submitUsageRequest("CAM-1","实验","3","user-1");assert.equal(result.status,"pending");assert.equal(Boolean(find(client,"UPDATE lab_assets SET status='in_use'")),false)});

test("approving a pending request assigns the requester and rejects competing requests",async()=>{for(const action of["approve","reject"] as const){const client=new FakeClient(({sql})=>sql.includes("FROM lab_asset_usage_requests")?{rowCount:1,rows:[{asset_id:"asset-1",status:"pending",requester_id:"user-1"}]}:defaultResponse({sql}));const result=await serviceWith(client).reviewUsageRequest("00000000-0000-4000-8000-000000000099",{action,note:"处理"},"3","admin");assert.equal(result.status,action==="approve"?"approved":"rejected");assert.equal(Boolean(find(client,"UPDATE lab_assets SET status='in_use'")),action==="approve");assert.equal(Boolean(find(client,"设备已分配给其他成员")),action==="approve")}});

test("duplicate codes, missing relations, and revision conflicts roll back",async()=>{const duplicateClient=new FakeClient(({sql})=>sql.includes("SELECT 1 FROM lab_assets")?{rowCount:1,rows:[{}]}:defaultResponse({sql}));await assert.rejects(serviceWith(duplicateClient).createAsset(asset(),"3","admin"),ConflictError);const missingType=new FakeClient(({sql})=>sql.includes("SELECT id,name FROM lab_device_types")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(missingType).createAsset(asset(),"3","admin"),ConflictError);const revision=new FakeClient(({sql})=>sql.includes("UPDATE site_content_revisions")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(revision).deleteAsset("CAM-1","3","admin"),RevisionConflictError);assert.equal(revision.calls.at(-1)?.sql,"ROLLBACK")});
