import assert from "node:assert/strict";
import test from "node:test";
import { assetDisplayState,ConflictError,createLabAssetsService,RevisionConflictError,type LabAsset,type LabPlatform } from "./labAssetsService.js";
import type { AssetImportRow } from "./schemas.js";

type Call={sql:string;values?:readonly unknown[]};type Result={rowCount:number;rows:Record<string,any>[]};
class FakeClient{calls:Call[]=[];released=false;constructor(private respond:(call:Call)=>Result=defaultResponse){}async query(sql:string,values?:readonly unknown[]){const call={sql,values};this.calls.push(call);return this.respond(call)}release(){this.released=true}}
function defaultResponse({sql}:Call):Result{if(sql.includes("UPDATE site_content_revisions"))return{rowCount:1,rows:[{revision:"4"}]};if(sql.includes("SELECT 1 FROM lab_"))return{rowCount:0,rows:[]};if(sql.includes("SELECT id FROM lab_platforms"))return{rowCount:1,rows:[{id:"22"}]};if(sql.includes("SELECT id FROM lab_platform_types"))return{rowCount:1,rows:[{id:"11"}]};if(sql.includes("SELECT id,name FROM lab_device_types"))return{rowCount:1,rows:[{id:"33",name:"相机"}]};if(sql.includes("INSERT INTO lab_platforms")&&sql.includes("RETURNING id"))return{rowCount:1,rows:[{id:"22"}]};if(sql.includes("UPDATE lab_platforms")&&sql.includes("RETURNING id"))return{rowCount:1,rows:[{id:"22"}]};if(sql.includes("INSERT INTO lab_assets")&&sql.includes("RETURNING id"))return{rowCount:1,rows:[{id:"44"}]};if(sql.includes("UPDATE lab_assets")&&sql.includes("RETURNING id"))return{rowCount:1,rows:[{id:"44"}]};if(sql.includes("INSERT INTO lab_asset_usage_requests"))return{rowCount:1,rows:[{id:"request-1"}]};return{rowCount:1,rows:[]}}
const asset=(overrides:Partial<LabAsset>={}):LabAsset=>({code:"CAM-1",deviceTypeCode:"camera",model:"D455",name:{zh:"相机",en:"Camera"},description:{zh:"前置",en:"Front"},vendorSerial:"SN-1",status:"mounted",currentPlatformCode:"DOG-2",assignedUserId:null,borrowerName:"",borrowerContact:"",storageLocation:"507-A 柜 3 层",...overrides});
const platform=(overrides:Partial<LabPlatform>={}):LabPlatform=>({code:"DOG-2",typeCode:"robot",name:{zh:"机器狗",en:"Robot dog"},description:{zh:"四足平台",en:"Quadruped"},status:"active",assetCodes:["CAM-1"],...overrides});
const serviceWith=(client:FakeClient)=>createLabAssetsService({connect:async()=>client} as never);const find=(client:FakeClient,fragment:string)=>client.calls.find((call)=>call.sql.includes(fragment));

test("display state gives condition and allocation precedence over platform membership",()=>{assert.equal(assetDisplayState({currentPlatformCode:"DOG-1",condition:"normal"}),"mounted");assert.equal(assetDisplayState({currentPlatformCode:"DOG-1",condition:"maintenance"}),"maintenance");assert.equal(assetDisplayState({assignedUserId:"user-1",condition:"normal"}),"in_use");assert.equal(assetDisplayState({currentPlatformCode:"DOG-1",condition:"retired"}),"retired");});

test("snapshot exposes devices, platforms, members, requests, and direct relationships",async()=>{const client=new FakeClient(({sql})=>{if(sql.includes("FROM page_content"))return{rowCount:1,rows:[{content_json:{}}]};if(sql.includes("FROM site_content_revisions"))return{rowCount:1,rows:[{revision:"9"}]};if(sql.includes("FROM lab_platform_types"))return{rowCount:1,rows:[{code:"robot",name:"机器人"}]};if(sql.includes("FROM lab_device_types"))return{rowCount:1,rows:[{code:"camera",name:"相机"}]};if(sql.includes("FROM lab_platforms p"))return{rowCount:1,rows:[{code:"DOG-2",type_code:"robot",name_zh:"机器狗",name_en:"Robot dog",description_zh:"四足",description_en:"Quadruped",status:"active"}]};if(sql.includes("FROM lab_asset_usage_requests"))return{rowCount:1,rows:[{id:"request-1",status:"pending",reason:"实验",review_note:"",created_at:new Date(),reviewed_at:null,asset_code:"CAM-1",asset_name_zh:"相机",asset_name_en:"Camera",requester_id:"user-2",requester_name:"张三",reviewer_name:null}]};if(sql.includes("FROM lab_assets a"))return{rowCount:2,rows:[{code:"CAM-1",device_type_code:"camera",device_type_name:"相机",model:"D455",name_zh:"相机",name_en:"Camera",description_zh:"前置",description_en:"Front",vendor_serial:"SN-1",status:"mounted",current_platform_code:"DOG-2",assigned_user_id:null,assigned_user_name:null,borrower_name:"",borrower_contact:""},{code:"LIDAR-1",device_type_code:"lidar",device_type_name:"雷达",model:"M1",name_zh:"雷达",name_en:"Lidar",description_zh:"",description_en:"",vendor_serial:"SN-2",status:"in_use",current_platform_code:null,assigned_user_id:"user-2",assigned_user_name:"张三",borrower_name:"",borrower_contact:""}]};if(sql.includes("FROM users WHERE status"))return{rowCount:1,rows:[{id:"user-2",username:"zhang",display_name:"张三"}]};return defaultResponse({sql})});const snapshot=await serviceWith(client).getSnapshot({id:"admin",canManage:true});assert.equal(snapshot.revision,"9");assert.deepEqual(snapshot.platforms[0].assetCodes,["CAM-1"]);assert.equal(snapshot.assets.find((item:any)=>item.code==="LIDAR-1")?.assignedUserName,"张三");assert.equal(snapshot.members.length,1);assert.equal(snapshot.usageRequests.length,1);assert.equal(snapshot.stats.inUseAssets,1);assert.match(client.calls.find((call)=>call.sql.includes("FROM lab_platforms p"))!.sql,/COALESCE\(NULLIF\(t\.name_zh,''\),NULLIF\(t\.name_en,''\),t\.code\)/);assert.equal(client.calls[0].sql,"BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");assert.equal(client.calls.at(-1)?.sql,"COMMIT")});

test("asset allocation and condition fields are normalized when persisted",async()=>{for(const item of[asset(),asset({status:"in_use",currentPlatformCode:null,assignedUserId:"00000000-0000-4000-8000-000000000001"}),asset({status:"lend",currentPlatformCode:null,borrowerName:"李四",borrowerContact:"13800000000"}),asset({status:"maintenance",condition:"maintenance",currentPlatformCode:"DOG-2"})]){const client=new FakeClient();await serviceWith(client).createAsset(item,"3","admin");const insert=find(client,"INSERT INTO lab_assets");assert.ok(insert);if(item.currentPlatformCode)assert.equal(insert?.values?.[12],"22");if(item.status==="in_use")assert.equal(insert?.values?.[13],item.assignedUserId);if(item.status==="lend")assert.deepEqual(insert?.values?.slice(14,16),["李四","13800000000"]);if(item.condition==="maintenance")assert.equal(insert?.values?.[11],"maintenance");}});

test("batch asset changes lock every target and commit one audited update",async()=>{for(const input of[
  {assetCodes:["CAM-1","CAM-2"],action:"set_status" as const,value:"maintenance" as const,expectedRevision:"3"},
  {assetCodes:["CAM-1","CAM-2"],action:"set_device_type" as const,value:"lidar",expectedRevision:"3"},
  {assetCodes:["CAM-1","CAM-2"],action:"set_location" as const,value:"507 实验室",expectedRevision:"3"},
]){const client=new FakeClient(({sql})=>sql.includes("SELECT code FROM lab_assets")?{rowCount:2,rows:[{code:"CAM-1"},{code:"CAM-2"}]}:defaultResponse({sql}));const revision=await serviceWith(client).batchAssets(input,"admin");assert.equal(revision,"4");assert.ok(find(client,"FOR UPDATE"));assert.ok(client.calls.some((call)=>call.sql.includes("UPDATE lab_assets SET")));assert.equal(client.calls.filter((call)=>call.sql.includes("INSERT INTO audit_logs")).length,1);assert.equal(client.calls.at(-1)?.sql,"COMMIT");}});

test("batch asset changes roll back when any selected asset is missing",async()=>{const client=new FakeClient(({sql})=>sql.includes("SELECT code FROM lab_assets")?{rowCount:1,rows:[{code:"CAM-1"}]}:defaultResponse({sql}));await assert.rejects(serviceWith(client).batchAssets({assetCodes:["CAM-1","MISSING"],action:"set_location",value:null,expectedRevision:"3"},"admin"),ConflictError);assert.equal(Boolean(find(client,"UPDATE lab_assets SET storage_location")),false);assert.equal(client.calls.at(-1)?.sql,"ROLLBACK");});

test("batch asset changes reject stale revisions before locking assets",async()=>{const client=new FakeClient(({sql})=>sql.includes("UPDATE site_content_revisions")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(client).batchAssets({assetCodes:["CAM-1"],action:"set_status",value:"maintenance",expectedRevision:"2"},"admin"),RevisionConflictError);assert.equal(Boolean(find(client,"SELECT code FROM lab_assets")),false);assert.equal(client.calls.at(-1)?.sql,"ROLLBACK");});

test("batch condition changes preserve platform allocation",async()=>{const client=new FakeClient(({sql})=>sql.includes("SELECT code FROM lab_assets")?{rowCount:1,rows:[{code:"CAM-1"}]}:defaultResponse({sql}));await serviceWith(client).batchAssets({assetCodes:["CAM-1"],action:"set_status",value:"maintenance",expectedRevision:"3"},"admin");const update=find(client,"UPDATE lab_assets SET condition");assert.deepEqual(update?.values,[['CAM-1'],'maintenance']);assert.doesNotMatch(update?.sql??"",/current_platform_id/);});

const importRow=(overrides:Partial<AssetImportRow>={}):AssetImportRow=>({code:"CAM-2",nameZh:"相机",nameEn:"Camera",model:"D455",deviceTypeCode:"camera",vendorSerial:"SN-2",storageLocation:"507",status:"idle",platformCode:"",descriptionZh:"",...overrides});
function importResponse({sql}:Call):Result{if(sql.includes("SELECT revision::text"))return{rowCount:1,rows:[{revision:"3"}]};if(sql.includes("SELECT code FROM lab_device_types WHERE code=ANY"))return{rowCount:1,rows:[{code:"camera"}]};if(sql.includes("SELECT code FROM lab_platforms WHERE code=ANY"))return{rowCount:0,rows:[]};if(sql.includes("SELECT code,vendor_serial FROM lab_assets"))return{rowCount:0,rows:[]};return defaultResponse({sql});}

test("asset import validates normal rows and classifies non-blocking warnings",async()=>{const client=new FakeClient(importResponse);const report=await serviceWith(client).validateAssetImport({rows:[importRow(),importRow({code:"CAM-3",vendorSerial:"",model:"",storageLocation:""})],expectedRevision:"3"});assert.deepEqual(report.summary,{total:2,valid:1,warnings:1,errors:0});assert.equal(report.rows[1].issues.every((issue)=>issue.severity==="warning"),true);assert.equal(client.calls.at(-1)?.sql,"COMMIT");});

test("asset import reports file and database duplicates plus unknown references",async()=>{const client=new FakeClient((call)=>{if(call.sql.includes("SELECT code FROM lab_device_types WHERE code=ANY"))return{rowCount:0,rows:[]};if(call.sql.includes("SELECT code,vendor_serial FROM lab_assets"))return{rowCount:1,rows:[{code:"CAM-2",vendor_serial:"SN-2"}]};return importResponse(call);});const report=await serviceWith(client).validateAssetImport({rows:[importRow(),importRow()],expectedRevision:"3"});assert.equal(report.summary.errors,2);const messages=report.rows.flatMap((row)=>row.issues.map((issue)=>issue.message));assert.ok(messages.includes("文件内资产编号重复"));assert.ok(messages.includes("文件内厂商序列号重复"));assert.ok(messages.includes("资产编号已存在"));assert.ok(messages.includes("厂商序列号已存在"));assert.ok(messages.includes("设备类型不存在"));});

test("asset import commits every row in one audited transaction",async()=>{const client=new FakeClient(importResponse);const revision=await serviceWith(client).commitAssetImport({rows:[importRow(),importRow({code:"CAM-3",vendorSerial:"SN-3"})],expectedRevision:"3"},"admin");assert.equal(revision,"4");assert.equal(client.calls.filter((call)=>call.sql.includes("INSERT INTO lab_assets")).length,2);assert.equal(client.calls.filter((call)=>call.sql.includes("INSERT INTO audit_logs")).length,1);assert.ok(find(client,"pg_advisory_xact_lock"));assert.equal(client.calls.at(-1)?.sql,"COMMIT");});

test("asset import preserves a received procurement source",async()=>{const sourceId="00000000-0000-4000-8000-000000000099";const client=new FakeClient((call)=>call.sql.includes("SELECT id FROM procurement_requests")?{rowCount:1,rows:[{id:sourceId}]}:importResponse(call));await serviceWith(client).commitAssetImport({rows:[importRow({procurementRequestId:sourceId})],expectedRevision:"3"},"admin");assert.match(find(client,"SELECT id FROM procurement_requests")!.sql,/status IN \('received','closed'\).*FOR SHARE/);assert.equal(find(client,"INSERT INTO lab_assets")?.values?.[21],sourceId);assert.deepEqual(JSON.parse(String(find(client,"INSERT INTO audit_logs")?.values?.[4])),{revision:"4",count:1,procurementRequestIds:[sourceId],createdMissingDeviceTypes:false});});

test("asset import can classify and create unknown device types",async()=>{const validateClient=new FakeClient((call)=>call.sql.includes("SELECT code FROM lab_device_types WHERE code=ANY")?{rowCount:0,rows:[]}:importResponse(call));const report=await serviceWith(validateClient).validateAssetImport({rows:[importRow({deviceTypeCode:"new-camera"})],expectedRevision:"3",createMissingDeviceTypes:true});assert.equal(report.summary.errors,0);assert.match(report.rows[0].issues[0].message,/自动创建/);const commitClient=new FakeClient(importResponse);await serviceWith(commitClient).commitAssetImport({rows:[importRow({deviceTypeCode:"new-camera"})],expectedRevision:"3",createMissingDeviceTypes:true},"admin");assert.deepEqual(find(commitClient,"INSERT INTO lab_device_types")?.values?.[0],["new-camera"]);});

test("asset import rejects a missing or unreceived procurement source",async()=>{const client=new FakeClient((call)=>call.sql.includes("SELECT id FROM procurement_requests")?{rowCount:0,rows:[]}:importResponse(call));await assert.rejects(serviceWith(client).commitAssetImport({rows:[importRow({procurementRequestId:"00000000-0000-4000-8000-000000000099"})],expectedRevision:"3"},"admin"),ConflictError);assert.equal(Boolean(find(client,"INSERT INTO lab_assets")),false);assert.equal(client.calls.at(-1)?.sql,"ROLLBACK");});

test("asset import rolls back all rows on validation failure and stale revisions",async()=>{const invalidClient=new FakeClient((call)=>call.sql.includes("SELECT code FROM lab_device_types WHERE code=ANY")?{rowCount:0,rows:[]}:importResponse(call));await assert.rejects(serviceWith(invalidClient).commitAssetImport({rows:[importRow()],expectedRevision:"3"},"admin"),/validation failed/);assert.equal(Boolean(find(invalidClient,"INSERT INTO lab_assets")),false);assert.equal(invalidClient.calls.at(-1)?.sql,"ROLLBACK");const staleClient=new FakeClient(({sql})=>sql.includes("UPDATE site_content_revisions")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(staleClient).commitAssetImport({rows:[importRow()],expectedRevision:"2"},"admin"),RevisionConflictError);assert.equal(Boolean(find(staleClient,"pg_advisory_xact_lock")),false);});

test("platform metadata editing does not silently rewrite component relationships",async()=>{const client=new FakeClient();await serviceWith(client).updatePlatform("DOG-1",platform(),"3","admin");assert.equal(client.calls.some((call)=>call.sql.includes("UPDATE lab_assets SET current_platform_id")),false);assert.ok(find(client,"INSERT INTO lab_platform_public_profiles"));});

test("removing a platform is blocked until all components are removed",async()=>{const blocked=new FakeClient(({sql})=>sql.includes("SELECT 1 FROM lab_assets WHERE current_platform_id")?{rowCount:1,rows:[{}]}:defaultResponse({sql}));await assert.rejects(serviceWith(blocked).deletePlatform("DOG-2","3","admin"),ConflictError);assert.equal(Boolean(find(blocked,"DELETE FROM lab_platforms")),false);const empty=new FakeClient();await serviceWith(empty).deletePlatform("DOG-2","3","admin");assert.ok(find(empty,"DELETE FROM lab_platforms"));});

test("component add permits idle and maintenance devices and audits the operation",async()=>{for(const condition of["normal","maintenance"]){const client=new FakeClient(({sql})=>sql.includes("SELECT id,status,condition,current_platform_id")?{rowCount:1,rows:[{id:"44",status:"idle",condition,current_platform_id:null}]}:defaultResponse({sql}));await serviceWith(client).addPlatformComponent("DOG-2",{assetCode:"CAM-1",role:{zh:"前视相机",en:"Front camera"},slot:"front",sortOrder:1,expectedRevision:"3"},"admin");assert.ok(find(client,"SET current_platform_id=$2,status='mounted'"));assert.equal(find(client,"SET current_platform_id=$2,status='mounted'")?.values?.[1],"22");assert.equal(find(client,"INSERT INTO audit_logs")?.values?.[1],"platform.component.add");}});

test("component add is idempotent on the current platform and rejects unsafe ownership or state",async()=>{const cases=[{row:{id:"44",status:"idle",condition:"normal",current_platform_id:"22"},reject:false},{row:{id:"44",status:"idle",condition:"normal",current_platform_id:"99"},reject:true},{row:{id:"44",status:"in_use",condition:"normal",current_platform_id:null},reject:true},{row:{id:"44",status:"lend",condition:"normal",current_platform_id:null},reject:true},{row:{id:"44",status:"idle",condition:"retired",current_platform_id:null},reject:true}];for(const item of cases){const client=new FakeClient(({sql})=>sql.includes("SELECT id,status,condition,current_platform_id")?{rowCount:1,rows:[item.row]}:defaultResponse({sql}));const action=serviceWith(client).addPlatformComponent("DOG-2",{assetCode:"CAM-1",role:{zh:"",en:""},slot:null,sortOrder:0,expectedRevision:"3"},"admin");if(item.reject)await assert.rejects(action,ConflictError);else{await action;assert.equal(Boolean(find(client,"SET current_platform_id=$2")),false);}}});

test("component removal keeps condition untouched and records the new storage location",async()=>{const client=new FakeClient();await serviceWith(client).removePlatformComponent("DOG-2","CAM-1",{storageLocation:"507-A 柜",expectedRevision:"3"},"admin");const update=find(client,"SET current_platform_id=NULL,status='idle'");assert.ok(update);assert.doesNotMatch(update.sql,/condition=/);assert.equal(update.values?.[2],"507-A 柜");assert.equal(find(client,"INSERT INTO audit_logs")?.values?.[1],"platform.component.remove");});

test("component transfer is one locked atomic update and revision conflicts write nothing",async()=>{const client=new FakeClient(({sql})=>sql.includes("SELECT id,status,condition,current_platform_id")?{rowCount:1,rows:[{id:"44",status:"mounted",condition:"normal",current_platform_id:"99"}]}:defaultResponse({sql}));await serviceWith(client).transferPlatformComponent("DOG-2","CAM-1",{role:{zh:"定位",en:"Positioning"},slot:"top",sortOrder:2,expectedRevision:"3"},"admin");assert.ok(find(client,"FOR UPDATE"));assert.equal(client.calls.filter((call)=>call.sql.includes("UPDATE lab_assets SET current_platform_id=$2")).length,1);assert.equal(find(client,"INSERT INTO audit_logs")?.values?.[1],"platform.component.transfer");const stale=new FakeClient(({sql})=>sql.includes("UPDATE site_content_revisions")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(stale).transferPlatformComponent("DOG-2","CAM-1",{role:{zh:"",en:""},slot:null,sortOrder:0,expectedRevision:"2"},"admin"),RevisionConflictError);assert.equal(Boolean(find(stale,"SELECT id,status,condition,current_platform_id")),false);});

test("idle usage requests auto approve and assign the requester",async()=>{const client=new FakeClient(({sql})=>{if(sql.includes("SELECT id,status FROM lab_assets"))return{rowCount:1,rows:[{id:"asset-1",status:"idle"}]};return defaultResponse({sql})});const result=await serviceWith(client).submitUsageRequest("CAM-1","实验","3","user-1");assert.equal(result.status,"approved");assert.ok(find(client,"status='in_use'"));assert.ok(client.calls.some((call)=>call.sql.includes("INSERT INTO audit_logs")&&String(call.values?.[1]).includes("usage-request.create")))});

test("non-idle usage requests wait for review",async()=>{const client=new FakeClient(({sql})=>sql.includes("SELECT id,status FROM lab_assets")?{rowCount:1,rows:[{id:"asset-1",status:"mounted"}]}:defaultResponse({sql}));const result=await serviceWith(client).submitUsageRequest("CAM-1","实验","3","user-1");assert.equal(result.status,"pending");assert.equal(Boolean(find(client,"UPDATE lab_assets SET status='in_use'")),false)});

test("approving a pending request assigns the requester and rejects competing requests",async()=>{for(const action of["approve","reject"] as const){const client=new FakeClient(({sql})=>sql.includes("FROM lab_asset_usage_requests")?{rowCount:1,rows:[{asset_id:"asset-1",status:"pending",requester_id:"user-1"}]}:defaultResponse({sql}));const result=await serviceWith(client).reviewUsageRequest("00000000-0000-4000-8000-000000000099",{action,note:"处理"},"3","admin");assert.equal(result.status,action==="approve"?"approved":"rejected");assert.equal(Boolean(find(client,"UPDATE lab_assets SET status='in_use'")),action==="approve");assert.equal(Boolean(find(client,"设备已分配给其他成员")),action==="approve")}});

test("duplicate codes, missing relations, and revision conflicts roll back",async()=>{const duplicateClient=new FakeClient(({sql})=>sql.includes("SELECT 1 FROM lab_assets")?{rowCount:1,rows:[{}]}:defaultResponse({sql}));await assert.rejects(serviceWith(duplicateClient).createAsset(asset(),"3","admin"),ConflictError);const missingType=new FakeClient(({sql})=>sql.includes("SELECT id,name FROM lab_device_types")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(missingType).createAsset(asset(),"3","admin"),ConflictError);const revision=new FakeClient(({sql})=>sql.includes("UPDATE site_content_revisions")?{rowCount:0,rows:[]}:defaultResponse({sql}));await assert.rejects(serviceWith(revision).deleteAsset("CAM-1","3","admin"),RevisionConflictError);assert.equal(revision.calls.at(-1)?.sql,"ROLLBACK")});
