"use client";
import { useEffect,useState } from "react";
import type { Member } from "./MemberManagement";

const field="w-full border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-cyan-700";
const labels:Record<string,string>={name:"姓名",avatar:"头像",degree:"学历阶段",major:"专业",research:"研究方向",enrollmentYear:"入组年份",graduationYear:"毕业年份",destination:"毕业去向"};
export function MemberProfileEditor({member,busy,canEdit,onSave,onConvert}:{member:Member;busy:boolean;canEdit:boolean;onSave:(body:Record<string,unknown>)=>Promise<void>;onConvert:()=>Promise<void>}){
  const [draft,setDraft]=useState(member);useEffect(()=>setDraft(member),[member]);const update=(key:keyof Member,value:unknown)=>setDraft((current)=>({...current,[key]:value}));
  const save=()=>onSave({version:draft.version,memberCategory:draft.memberCategory,memberStatus:draft.memberStatus,degreeLevel:draft.degreeLevel,nameZh:draft.nameZh,nameEn:draft.nameEn,email:draft.publicEmail,phone:draft.phone,bioZh:draft.bioZh,bioEn:draft.bioEn,researchInterestsZh:draft.researchInterestsZh,researchInterestsEn:draft.researchInterestsEn,enrollmentYear:draft.enrollmentYear,graduationYear:draft.graduationYear,majorZh:draft.majorZh,majorEn:draft.majorEn,thesisZh:draft.thesisZh,thesisEn:draft.thesisEn,destinationZh:draft.destinationZh,destinationEn:draft.destinationEn,avatarAssetId:draft.avatarAssetId,avatarPositionX:draft.avatarPositionX,avatarPositionY:draft.avatarPositionY,avatarZoom:draft.avatarZoom,personalLinks:draft.personalLinks,publicFields:draft.publicFields,publicVisible:draft.publicVisible});
  const visible=new Set(draft.publicFields);
  return <div><div className={`mb-5 border p-4 text-sm ${draft.completeness.complete?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-900"}`}><b>{draft.completeness.complete?"资料完整":"资料待完善"}</b>{draft.completeness.missing.length?<span> · 缺少 {draft.completeness.missing.map((key)=>labels[key]??key).join("、")}</span>:null}<span className="ml-2">· 上次内容更新 {new Date(draft.profileContentUpdatedAt).toLocaleDateString("zh-CN")}</span></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(260px,.65fr)]"><div className="grid gap-4 sm:grid-cols-2">
    {([['nameZh','中文姓名'],['nameEn','英文姓名'],['publicEmail','公开联系邮箱'],['phone','联系电话'],['enrollmentYear','入组年份'],['graduationYear','毕业年份'],['majorZh','专业（中文）'],['majorEn','专业（英文）'],['researchInterestsZh','研究方向（中文）'],['researchInterestsEn','研究方向（英文）'],['destinationZh','毕业去向（中文）'],['destinationEn','毕业去向（英文）']] as const).map(([key,label])=><label className="text-sm" key={key}>{label}<input className={`${field} mt-1`} disabled={!canEdit||busy} value={String(draft[key]??"")} onChange={(event)=>update(key,event.target.value)}/></label>)}
    <label className="text-sm">成员类别<select className={`${field} mt-1`} disabled={!canEdit||busy} value={draft.memberCategory} onChange={(event)=>update('memberCategory',event.target.value)}>{['advisor','postdoc','phd','master','undergrad','alumni'].map((value)=><option key={value}>{value}</option>)}</select></label>
    <label className="text-sm">学历阶段<select className={`${field} mt-1`} disabled={!canEdit||busy} value={draft.degreeLevel} onChange={(event)=>update('degreeLevel',event.target.value)}>{['','faculty','postdoc','undergrad','master','phd'].map((value)=><option key={value} value={value}>{value||'未设置'}</option>)}</select></label>
    <label className="flex items-center gap-3 border border-slate-200 p-4 text-sm font-semibold sm:col-span-2"><input checked={draft.publicVisible} disabled={!canEdit||busy} type="checkbox" onChange={(event)=>update('publicVisible',event.target.checked)}/>在官网公开展示该成员</label>
    <fieldset className="border border-slate-200 p-4 sm:col-span-2"><legend className="px-1 text-xs font-semibold text-slate-500">官网公开字段</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{[['avatar','头像'],['name_zh','中文名'],['name_en','英文名'],['academic','学术信息'],['major','专业'],['research','研究方向'],['bio','简介'],['email','公开邮箱'],['links','个人链接'],['thesis','论文'],['destination','去向']].map(([key,label])=><label className="flex items-center gap-2 text-xs" key={key}><input checked={draft.publicFields.includes(key)} disabled={!canEdit||busy} type="checkbox" onChange={(event)=>update('publicFields',event.target.checked?[...draft.publicFields,key]:draft.publicFields.filter((item)=>item!==key))}/>{label}</label>)}</div></fieldset>
    {([['bioZh','个人简介（中文）'],['bioEn','个人简介（英文）'],['thesisZh','论文题目（中文）'],['thesisEn','论文题目（英文）']] as const).map(([key,label])=><label className="text-sm sm:col-span-2" key={key}>{label}<textarea className={`${field} mt-1 min-h-24`} disabled={!canEdit||busy} value={draft[key]} onChange={(event)=>update(key,event.target.value)}/></label>)}
  </div><aside><p className="mb-2 text-xs font-bold text-cyan-800">官网成员卡片预览</p><article className={`border-t-4 bg-slate-50 p-5 ${draft.publicVisible?"border-cyan-600":"border-slate-400 opacity-70"}`}><p className="text-xs text-slate-500">{draft.publicVisible?"将展示在官网":"当前不会在官网展示"}</p><h3 className="mt-3 font-serif text-2xl text-blue-950">{visible.has("name_zh")?draft.nameZh:""} <span className="text-base text-slate-500">{visible.has("name_en")?draft.nameEn:""}</span></h3>{visible.has("academic")?<p className="mt-2 text-sm text-slate-600">{draft.memberStatus==='alumni'?`${draft.graduationYear||'未填'} 届`:`${draft.enrollmentYear||'未填'} 级`} · {draft.degreeLevel}</p>:null}{visible.has("major")?<p className="mt-3 text-sm">{draft.majorZh||draft.majorEn}</p>:null}{visible.has("research")?<p className="mt-4 text-sm"><b>研究方向：</b>{draft.researchInterestsZh||draft.researchInterestsEn}</p>:null}{visible.has("bio")?<p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{draft.bioZh||draft.bioEn}</p>:null}{visible.has("email")&&draft.publicEmail?<p className="mt-4 text-sm text-cyan-800">{draft.publicEmail}</p>:null}</article></aside></div>{canEdit?<div className="mt-5 flex flex-wrap gap-3"><button className="bg-blue-950 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400" disabled={busy} onClick={()=>void save()} type="button">保存成员资料</button>{draft.memberStatus==='current'&&draft.baseTier!=='super'?<button className="border border-amber-400 px-4 py-2 text-sm font-bold text-amber-900" disabled={busy} onClick={()=>{if(window.confirm('确认转换为校友？系统将检查占用设备，清理岗位权限并撤销旧会话。'))void onConvert();}} type="button">转换为校友</button>:null}</div>:null}</div>;
}
