"use client";
import { useEffect,useState } from "react";
import { consoleApi } from "@/lib/consoleApi";
import type { Member } from "./MemberManagement";

const field="w-full border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-cyan-700";
const labels:Record<string,string>={name:"姓名",avatar:"头像",degree:"学历阶段",major:"专业",research:"研究方向",enrollmentYear:"入组年份",graduationYear:"毕业年份",destination:"毕业去向"};
export function MemberProfileEditor({member,busy,canEdit,onSave,onConvert}:{member:Member;busy:boolean;canEdit:boolean;onSave:(body:Record<string,unknown>)=>Promise<void>;onConvert:()=>Promise<void>}){
  const [draft,setDraft]=useState(member);const [uploading,setUploading]=useState(false);const [uploadError,setUploadError]=useState("");useEffect(()=>{setDraft(member);setUploadError("")},[member]);const update=(key:keyof Member,value:unknown)=>setDraft((current)=>({...current,[key]:value}));
  const save=()=>onSave({version:draft.version,memberCategory:draft.memberCategory,memberStatus:draft.memberStatus,degreeLevel:draft.degreeLevel,nameZh:draft.nameZh,nameEn:draft.nameEn,email:draft.publicEmail,phone:draft.phone,bioZh:draft.bioZh,bioEn:draft.bioEn,researchInterestsZh:draft.researchInterestsZh,researchInterestsEn:draft.researchInterestsEn,enrollmentYear:draft.enrollmentYear,graduationYear:draft.graduationYear,majorZh:draft.majorZh,majorEn:draft.majorEn,thesisZh:draft.thesisZh,thesisEn:draft.thesisEn,destinationZh:draft.destinationZh,destinationEn:draft.destinationEn,avatarAssetId:draft.avatarAssetId,avatarPositionX:draft.avatarPositionX,avatarPositionY:draft.avatarPositionY,avatarZoom:draft.avatarZoom,personalLinks:draft.personalLinks,publicFields:draft.publicFields,publicVisible:draft.publicVisible});
  const uploadAvatar=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setUploading(true);setUploadError("");try{const data=new FormData();data.append("file",file);const asset=await consoleApi<{id:string;url:string}>("/api/media/upload",{method:"POST",body:data});setDraft((current)=>({...current,avatarAssetId:asset.id,avatarUrl:asset.url,avatarPositionX:50,avatarPositionY:50,avatarZoom:1}));}catch(reason){setUploadError((reason as Error).message)}finally{setUploading(false);event.target.value=""}};
  const visible=new Set(draft.publicFields);
  return <div><div className={`mb-5 border p-4 text-sm ${draft.completeness.complete?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-900"}`}><b>{draft.completeness.complete?"资料完整":"资料待完善"}</b>{draft.completeness.missing.length?<span> · 缺少 {draft.completeness.missing.map((key)=>labels[key]??key).join("、")}</span>:null}<span className="ml-2">· 上次内容更新 {new Date(draft.profileContentUpdatedAt).toLocaleDateString("zh-CN")}</span></div>{draft.publicVisible&&!draft.completeness.complete?<p className="mb-5 border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">该成员已公开展示，但仍缺少：{draft.completeness.missing.map((key)=>labels[key]??key).join("、")}。仍可保存，建议先完善。</p>:null}{uploadError?<p className="mb-5 border border-red-200 bg-red-50 p-3 text-sm text-red-800">{uploadError}</p>:null}<div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(260px,.65fr)]"><div className="grid gap-4 sm:grid-cols-2">
    <section className="grid gap-4 border border-slate-200 p-4 sm:col-span-2 sm:grid-cols-[128px_1fr]"><div>{draft.avatarUrl?<AvatarPreview member={draft}/>:<div className="grid aspect-square w-32 place-items-center bg-slate-100 text-xs text-slate-500">尚未上传头像</div>}</div><div><h3 className="font-semibold text-blue-950">成员头像与裁剪</h3><p className="mt-1 text-xs text-slate-600">支持 JPG、PNG、WebP；上传后调整显示区域，再保存成员资料。</p><div className="mt-3 flex flex-wrap gap-2"><label className="cursor-pointer bg-blue-950 px-3 py-2 text-xs font-semibold text-white">{uploading?"上传中…":draft.avatarUrl?"重新上传":"上传头像"}<input accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={!canEdit||busy||uploading} onChange={uploadAvatar} type="file"/></label>{draft.avatarAssetId?<button className="border border-slate-300 px-3 py-2 text-xs" disabled={!canEdit||busy||uploading} onClick={()=>setDraft((current)=>({...current,avatarAssetId:null,avatarUrl:null}))} type="button">移除头像</button>:null}</div>{draft.avatarUrl?<div className="mt-4 grid gap-3 sm:grid-cols-3"><Range label="水平位置" value={draft.avatarPositionX} min={0} max={100} onChange={(value)=>update('avatarPositionX',value)}/><Range label="垂直位置" value={draft.avatarPositionY} min={0} max={100} onChange={(value)=>update('avatarPositionY',value)}/><Range label="缩放" value={draft.avatarZoom} min={1} max={3} step={0.05} onChange={(value)=>update('avatarZoom',value)}/></div>:null}</div></section>
    {([['nameZh','中文姓名'],['nameEn','英文姓名'],['publicEmail','公开联系邮箱'],['phone','联系电话'],['enrollmentYear','入组年份'],['graduationYear','毕业年份'],['majorZh','专业（中文）'],['majorEn','专业（英文）'],['researchInterestsZh','研究方向（中文）'],['researchInterestsEn','研究方向（英文）'],['destinationZh','毕业去向（中文）'],['destinationEn','毕业去向（英文）']] as const).map(([key,label])=><label className="text-sm" key={key}>{label}<input className={`${field} mt-1`} disabled={!canEdit||busy} value={String(draft[key]??"")} onChange={(event)=>update(key,event.target.value)}/></label>)}
    <label className="text-sm">成员类别<select className={`${field} mt-1`} disabled={!canEdit||busy} value={draft.memberCategory} onChange={(event)=>update('memberCategory',event.target.value)}>{['advisor','postdoc','phd','master','undergrad','alumni'].map((value)=><option key={value}>{value}</option>)}</select></label>
    <label className="text-sm">学历阶段<select className={`${field} mt-1`} disabled={!canEdit||busy} value={draft.degreeLevel} onChange={(event)=>update('degreeLevel',event.target.value)}>{['','faculty','postdoc','undergrad','master','phd'].map((value)=><option key={value} value={value}>{value||'未设置'}</option>)}</select></label>
    <label className="flex items-center gap-3 border border-slate-200 p-4 text-sm font-semibold sm:col-span-2"><input checked={draft.publicVisible} disabled={!canEdit||busy} type="checkbox" onChange={(event)=>update('publicVisible',event.target.checked)}/>在官网公开展示该成员</label>
    <fieldset className="border border-slate-200 p-4 sm:col-span-2"><legend className="px-1 text-xs font-semibold text-slate-500">官网公开字段</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{[['avatar','头像'],['name_zh','中文名'],['name_en','英文名'],['academic','学术信息'],['major','专业'],['research','研究方向'],['bio','简介'],['email','公开邮箱'],['links','个人链接'],['thesis','论文'],['destination','去向']].map(([key,label])=><label className="flex items-center gap-2 text-xs" key={key}><input checked={draft.publicFields.includes(key)} disabled={!canEdit||busy} type="checkbox" onChange={(event)=>update('publicFields',event.target.checked?[...draft.publicFields,key]:draft.publicFields.filter((item)=>item!==key))}/>{label}</label>)}</div></fieldset>
    {([['bioZh','个人简介（中文）'],['bioEn','个人简介（英文）'],['thesisZh','论文题目（中文）'],['thesisEn','论文题目（英文）']] as const).map(([key,label])=><label className="text-sm sm:col-span-2" key={key}>{label}<textarea className={`${field} mt-1 min-h-24`} disabled={!canEdit||busy} value={draft[key]} onChange={(event)=>update(key,event.target.value)}/></label>)}
    <section className="sm:col-span-2"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-blue-950">个人链接</h3><p className="mt-1 text-xs text-slate-600">个人主页、GitHub、Google Scholar 等公开链接。</p></div><button className="border border-slate-300 px-3 py-2 text-xs font-semibold" disabled={!canEdit||busy} onClick={()=>update('personalLinks',[...draft.personalLinks,{labelZh:'',labelEn:'',url:''}])} type="button">新增链接</button></div><div className="mt-3 space-y-3">{draft.personalLinks.map((link,index)=><div className="grid gap-2 border border-slate-200 p-3 md:grid-cols-[1fr_1fr_2fr_auto]" key={index}><input className={field} disabled={!canEdit||busy} placeholder="中文标签" value={link.labelZh} onChange={(event)=>update('personalLinks',draft.personalLinks.map((item,itemIndex)=>itemIndex===index?{...item,labelZh:event.target.value}:item))}/><input className={field} disabled={!canEdit||busy} placeholder="English label" value={link.labelEn} onChange={(event)=>update('personalLinks',draft.personalLinks.map((item,itemIndex)=>itemIndex===index?{...item,labelEn:event.target.value}:item))}/><input className={field} disabled={!canEdit||busy} placeholder="https://" value={link.url} onChange={(event)=>update('personalLinks',draft.personalLinks.map((item,itemIndex)=>itemIndex===index?{...item,url:event.target.value}:item))}/><button className="text-xs font-semibold text-red-700 underline" disabled={!canEdit||busy} onClick={()=>update('personalLinks',draft.personalLinks.filter((_,itemIndex)=>itemIndex!==index))} type="button">删除</button></div>)}</div></section>
  </div><aside><p className="mb-2 text-xs font-bold text-cyan-800">官网成员卡片预览</p><article className={`border-t-4 bg-slate-50 p-5 ${draft.publicVisible?"border-cyan-600":"border-slate-400 opacity-70"}`}><p className="text-xs text-slate-500">{draft.publicVisible?"将展示在官网":"当前不会在官网展示"}</p>{visible.has("avatar")&&draft.avatarUrl?<AvatarPreview member={draft}/>:null}<h3 className="mt-3 font-serif text-2xl text-blue-950">{visible.has("name_zh")?draft.nameZh:""} <span className="text-base text-slate-500">{visible.has("name_en")?draft.nameEn:""}</span></h3>{visible.has("academic")?<p className="mt-2 text-sm text-slate-600">{draft.memberStatus==='alumni'?`${draft.graduationYear||'未填'} 届`:`${draft.enrollmentYear||'未填'} 级`} · {draft.degreeLevel}</p>:null}{visible.has("major")?<p className="mt-3 text-sm">{draft.majorZh||draft.majorEn}</p>:null}{visible.has("research")?<p className="mt-4 text-sm"><b>研究方向：</b>{draft.researchInterestsZh||draft.researchInterestsEn}</p>:null}{visible.has("bio")?<p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{draft.bioZh||draft.bioEn}</p>:null}{visible.has("email")&&draft.publicEmail?<p className="mt-4 text-sm text-cyan-800">{draft.publicEmail}</p>:null}{visible.has("links")&&draft.personalLinks.length?<div className="mt-4 flex flex-wrap gap-3">{draft.personalLinks.filter((link)=>link.url).map((link,index)=><span className="text-sm text-cyan-800 underline" key={index}>{link.labelZh||link.labelEn||link.url}</span>)}</div>:null}</article></aside></div>{canEdit?<div className="mt-5 flex flex-wrap gap-3"><button className="bg-blue-950 px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400" disabled={busy||uploading} onClick={()=>void save()} type="button">保存成员资料</button>{draft.memberStatus==='current'&&draft.baseTier!=='super'?<button className="border border-amber-400 px-4 py-2 text-sm font-bold text-amber-900" disabled={busy||uploading} onClick={()=>{if(window.confirm('确认转换为校友？系统将检查占用设备，清理岗位权限并撤销旧会话。'))void onConvert();}} type="button">转换为校友</button>:null}</div>:null}</div>;
}

function Range({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(value:number)=>void}){return <label className="text-xs text-slate-700">{label}<span className="ml-2 text-slate-500">{value}</span><input className="mt-2 block w-full accent-cyan-700" min={min} max={max} step={step} type="range" value={value} onChange={(event)=>onChange(Number(event.target.value))}/></label>}
function AvatarPreview({member}:{member:Pick<Member,"avatarUrl"|"avatarPositionX"|"avatarPositionY"|"avatarZoom">}){return <div className="mt-3 aspect-square w-32 overflow-hidden bg-slate-100"><img alt="成员头像预览" className="h-full w-full object-cover" src={member.avatarUrl??""} style={{objectPosition:`${member.avatarPositionX}% ${member.avatarPositionY}%`,transform:`scale(${member.avatarZoom})`,transformOrigin:`${member.avatarPositionX}% ${member.avatarPositionY}%`}}/></div>}
