"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- CMS documents are heterogeneous schema-validated JSON. */

import { useState } from "react";
import { ConsoleButton, ConsoleConfirmDialog, ConsoleInput, ConsoleSearchInput } from "@/features/console/ui";
import type { SiteModule } from "./model";
import { asList, asRecord, cmsId, EditorPanel, Field, LocalizedFields, MediaField, MoveButtons, moveItem } from "./CmsFields";

const emptyDirection = () => ({ key: cmsId("direction"), sortOrder: 0, title: { zh: "", en: "" }, subtitle: { zh: "", en: "" }, description: { zh: "", en: "" }, keywords: [], capability: { zh: "", en: "" }, scenario: { zh: "", en: "" }, topicKey: "", image: null });

export function DirectionsEditor({ value, modules, onChange }: { value: unknown; modules: SiteModule[]; onChange: (value: unknown) => void }) {
  const page = asRecord(value), legacyHome = asRecord(modules.find((item) => item.key === "home")?.value);
  const legacy = !Object.prototype.hasOwnProperty.call(page, "directions");
  const items = legacy ? asList(legacyHome.researchAreas) : asList(page.directions);
  const [selectedKey, setSelectedKey] = useState(""), [search, setSearch] = useState(""), [pendingDelete, setPendingDelete] = useState<string | null>(null);
  const keys = items.map((item, index) => String(item.key || item.id || `legacy-${index}`));
  const selectedIndex = Math.max(0, keys.indexOf(selectedKey));
  const selected = items[selectedIndex];
  const filtered = items.map((item, index) => ({ item, index, key: keys[index] })).filter(({ item }) => `${item.title?.zh ?? ""} ${item.title?.en ?? ""} ${item.description?.zh ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const commitItems = (next: Record<string, any>[]) => onChange({ ...page, directions: next.map((item, index) => ({ ...item, key: item.key || item.id || cmsId("direction"), sortOrder: index })) });
  const updateSelected = (next: Record<string, any>) => commitItems(items.map((item, index) => index === selectedIndex ? next : item));
  const header = asRecord(page.header), hero = asRecord(page.hero);
  return <div className="space-y-5">
    {legacy ? <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950"><b>来源：兼容首页旧数据</b><p className="mt-1 text-xs leading-5">首次修改会写入独立的研究方向模块；首页旧字段继续保留作为回退。</p></div> : <p className="text-xs font-semibold text-cyan-800">来源：官网内容 · 独立研究方向模块</p>}
    <EditorPanel title="页面设置" description="标题、介绍和顶部照片同时用于研究方向公开页。"><div className="space-y-5"><LocalizedFields label="页面标题" value={header.title} onChange={(title) => onChange({ ...page, header: { ...header, title } })}/><LocalizedFields label="页面简介" multiline value={header.description} onChange={(description) => onChange({ ...page, header: { ...header, description } })}/><MediaField label="Hero 图片" value={hero.image || header.image || legacyHome.directionsHeroImage} onChange={(image) => onChange({ ...page, hero: { ...hero, image } })}/></div></EditorPanel>
    <div className="grid min-h-[38rem] gap-5 lg:grid-cols-[minmax(16rem,.72fr)_minmax(0,1.45fr)]">
      <EditorPanel title="方向列表" description={`${items.length} 个方向`} actions={<ConsoleButton onClick={() => { const next = emptyDirection(); next.sortOrder = items.length; commitItems([...items, next]); setSelectedKey(next.key); }} size="sm" type="button" variant="primary">新增方向</ConsoleButton>}><ConsoleSearchInput aria-label="搜索研究方向" onChange={(event) => setSearch(event.target.value)} placeholder="搜索标题或简介" value={search}/><div className="mt-4 space-y-2">{filtered.map(({ item, index, key }) => <button className={`w-full rounded-lg border px-3 py-3 text-left transition ${index === selectedIndex ? "border-cyan-600 bg-cyan-50" : "border-slate-200 hover:border-cyan-300"}`} key={key} onClick={() => setSelectedKey(key)} type="button"><span className="block text-sm font-semibold text-slate-900">{item.title?.zh || item.title?.en || "未命名方向"}</span><span className="mt-1 block truncate text-xs text-slate-500">{item.title?.en || item.description?.zh || "等待完善"}</span></button>)}</div></EditorPanel>
      {selected ? <EditorPanel title={selected.title?.zh || selected.title?.en || "编辑方向"} actions={<div className="flex gap-2"><MoveButtons index={selectedIndex} length={items.length} onMove={(target) => commitItems(moveItem(items, selectedIndex, target))}/><ConsoleButton onClick={() => setPendingDelete(keys[selectedIndex])} size="sm" type="button" variant="danger">删除</ConsoleButton></div>}><div className="space-y-5"><LocalizedFields label="标题" value={selected.title} onChange={(title) => updateSelected({ ...selected, title })}/><LocalizedFields label="副标题" value={selected.subtitle} onChange={(subtitle) => updateSelected({ ...selected, subtitle })}/><LocalizedFields label="简介" multiline value={selected.description} onChange={(description) => updateSelected({ ...selected, description })}/><Field label="关键词" hint="中英文可混合，以逗号分隔"><ConsoleInput value={asList(selected.keywords).map((item) => item.zh || item.en).join(", ")} onChange={(event) => updateSelected({ ...selected, keywords: event.target.value.split(/[,，]/).map((word) => word.trim()).filter(Boolean).map((word) => ({ zh: word, en: word })) })}/></Field><LocalizedFields label="核心能力" multiline value={selected.capability} onChange={(capability) => updateSelected({ ...selected, capability })}/><LocalizedFields label="应用场景" multiline value={selected.scenario} onChange={(scenario) => updateSelected({ ...selected, scenario })}/><MediaField label="方向配图" value={selected.image} onChange={(image) => updateSelected({ ...selected, image })}/><details className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold text-slate-700">高级设置</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="稳定 Key"><ConsoleInput value={String(selected.key || selected.id || "")} onChange={(event) => updateSelected({ ...selected, key: event.target.value })}/></Field><Field label="论文 Topic Key"><ConsoleInput value={String(selected.topicKey ?? "")} onChange={(event) => updateSelected({ ...selected, topicKey: event.target.value })}/></Field><Field label="排序"><ConsoleInput type="number" value={Number(selected.sortOrder ?? selectedIndex)} onChange={(event) => updateSelected({ ...selected, sortOrder: Number(event.target.value) })}/></Field></div></details></div></EditorPanel> : <EditorPanel title="暂无研究方向"><p className="text-sm text-slate-500">新增第一个方向后即可开始编辑。</p></EditorPanel>}
    </div>
    <ConsoleConfirmDialog danger description="删除后将在保存当前模块时生效。旧首页回退数据不会被删除。" onClose={() => setPendingDelete(null)} onConfirm={() => { const index = keys.indexOf(pendingDelete || ""); if (index >= 0) commitItems(items.filter((_, itemIndex) => itemIndex !== index)); setPendingDelete(null); setSelectedKey(""); }} open={Boolean(pendingDelete)} title="删除这个研究方向？" confirmLabel="删除方向"/>
  </div>;
}
