"use client";

import { useCallback, useEffect, useState } from "react";
import { ConsoleAlert, ConsoleButton, ConsoleSelect } from "@/features/console/ui";
import { scholarlyApi, type PublicationCandidate, type PublicationSourceCandidate, type PublicationSyncInfo, type ScholarlyStatus } from "./scholarlyApi";

const managedLabels: Record<string, string> = { title_en: "英文标题", year: "年份", venue_en: "英文 Venue", type: "成果类型", doi_link: "DOI 链接", external_links: "外部链接" };

export function usePublicationSyncInfo(id?: string) {
  const [info, setInfo] = useState<PublicationSyncInfo | null>(null);
  const reload = useCallback(async () => { if (!id) { setInfo(null); return; } const result = await scholarlyApi.info(id); setInfo(result.sync); }, [id]);
  useEffect(() => { void reload().catch(() => setInfo(null)); }, [reload]);
  return { info, setInfo, reload };
}

export function PublicationSourceEditor({ researchItemId, info, onChange }: { researchItemId: string; info: PublicationSyncInfo | null; onChange: (value: PublicationSyncInfo) => void }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(""), [sourceCandidates, setSourceCandidates] = useState<PublicationSourceCandidate[]>([]);
  const run = async (operation: () => Promise<{ sync: PublicationSyncInfo }>, success: string) => { setBusy(true); setError(""); try { const result = await operation(); onChange(result.sync); setMessage(success); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } };
  if (!info) return <p className="text-sm text-slate-500">正在加载同步信息…</p>;
  return <div className="space-y-4">
    {error ? <ConsoleAlert title="操作失败" tone="danger">{error}</ConsoleAlert> : null}{message ? <ConsoleAlert title="已更新" tone="success">{message}</ConsoleAlert> : null}
    <dl className="grid gap-3 rounded-lg bg-slate-50 p-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">来源</dt><dd className="font-semibold text-blue-950">{info.source_type === "openalex" ? "OpenAlex 自动同步" : "手工维护"}</dd></div><div><dt className="text-slate-500">来源状态</dt><dd className="font-semibold text-blue-950">{info.decision}</dd></div><div><dt className="text-slate-500">OpenAlex Work ID</dt><dd>{info.openalex_work_id || "尚未绑定"}</dd></div><div><dt className="text-slate-500">DOI</dt><dd>{info.doi_normalized || "未识别"}</dd></div></dl>
    {info.openalex_work_id ? <fieldset><legend className="text-sm font-bold text-blue-950">自动更新字段</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(managedLabels).map(([key, label]) => <label className="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm" key={key}><input checked={info.managed_fields.includes(key)} disabled={busy} onChange={(event) => { const next = event.target.checked ? [...info.managed_fields, key] : info.managed_fields.filter((item) => item !== key); void run(() => scholarlyApi.managedFields(researchItemId, next), "自动更新字段已保存。"); }} type="checkbox"/>{label}</label>)}</div><p className="mt-2 text-xs text-slate-500">手动修改受管理字段并保存论文库后，该字段会自动转为人工维护。Topic、图片与 PDF 始终由人工维护。</p></fieldset> : <><ConsoleButton disabled={busy} onClick={() => { setBusy(true); setError(""); void scholarlyApi.resolveSource(researchItemId).then((result) => { if (result.sync) { onChange(result.sync); setMessage("已按 DOI 绑定外部来源；现有展示内容保持不变。"); } else { setSourceCandidates(result.candidates ?? []); setMessage("该论文没有 DOI，请人工选择 OpenAlex 记录。"); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "查找失败")).finally(() => setBusy(false)); }} type="button">查找外部记录</ConsoleButton>{sourceCandidates.length?<div className="space-y-2"><p className="text-sm font-bold text-blue-950">请选择匹配的 OpenAlex 成果</p>{sourceCandidates.map((candidate)=><article className="flex flex-wrap items-start justify-between gap-3 rounded-lg border border-slate-200 p-3" key={candidate.openalexWorkId}><div><strong className="text-sm text-blue-950">{candidate.title}</strong><p className="mt-1 text-xs text-slate-500">{candidate.year||"年份未知"} · {candidate.venue||"Venue 未知"} · {candidate.doi||candidate.openalexWorkId}</p><p className="mt-1 text-xs text-slate-500">{candidate.authors.join("、")}</p></div><ConsoleButton disabled={busy} onClick={() => { setBusy(true); setError(""); void scholarlyApi.resolveSource(researchItemId,candidate.openalexWorkId).then((result)=>{if(result.sync){onChange(result.sync);setSourceCandidates([]);setMessage("外部来源已绑定；人工展示内容保持不变。")}}).catch((reason)=>setError(reason instanceof Error?reason.message:"绑定失败")).finally(()=>setBusy(false)); }} size="sm" type="button">确认绑定</ConsoleButton></article>)}</div>:null}</>}
  </div>;
}

export function PublicationSyncPanel({ researchItems }: { researchItems: Array<{ id?: unknown; title?: { zh?: unknown; en?: unknown } }> }) {
  const [status, setStatus] = useState<ScholarlyStatus | null>(null), [mode, setMode] = useState<"pending" | "ignored">("pending"), [candidates, setCandidates] = useState<PublicationCandidate[]>([]), [merges, setMerges] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { const [nextStatus, nextCandidates] = await Promise.all([scholarlyApi.status(), scholarlyApi.candidates(mode)]); setStatus(nextStatus); setCandidates(nextCandidates.candidates); }, [mode]);
  useEffect(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : "无法加载论文同步状态")); }, [load]);
  const run = async (operation: () => Promise<unknown>, success: string) => { setBusy(true); setError(""); setMessage(""); try { await operation(); await load(); setMessage(success); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } };
  return <section className="mb-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-700">Scholarly Sync</p><h3 className="mt-1 text-lg font-bold text-blue-950">论文自动同步</h3><p className="mt-1 text-sm text-slate-500">OpenAlex 发现 · Crossref DOI 校准 · 人工展示优先</p></div><ConsoleButton disabled={busy || !status?.enabled} onClick={() => void run(scholarlyApi.syncAll, "全体成员同步完成；若产生公开变更，请刷新论文库快照。") } type="button" variant="primary">同步全部</ConsoleButton></div>
    {error ? <div className="mt-4"><ConsoleAlert title="同步服务异常" tone="danger">{error}</ConsoleAlert></div> : null}{message ? <div className="mt-4"><ConsoleAlert title="操作完成" tone="success">{message}</ConsoleAlert></div> : null}
    {status ? <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["OpenAlex",status.providers?.openAlexKeyConfigured?"已配置":"未配置 Key"],["Crossref",status.providers?.crossrefContactConfigured?"Polite 模式":"未配置邮箱"],["已验证成员",String(status.profiles?.verified??0)],["待确认",String(status.pending??0)],["最近同步",status.lastRun?.started_at?new Date(status.lastRun.started_at).toLocaleString("zh-CN"):"暂无"]].map(([label,value])=><div className="rounded-lg bg-slate-50 p-3" key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-blue-950">{value}</p></div>)}</div> : null}
    <div className="mt-5 flex gap-1 border-b border-slate-200"><button className={`px-3 py-2 text-sm font-semibold ${mode==="pending"?"border-b-2 border-cyan-700 text-cyan-800":"text-slate-500"}`} onClick={()=>setMode("pending")} type="button">待确认 {status?.pending??0}</button><button className={`px-3 py-2 text-sm font-semibold ${mode==="ignored"?"border-b-2 border-cyan-700 text-cyan-800":"text-slate-500"}`} onClick={()=>setMode("ignored")} type="button">已忽略 {status?.ignored??0}</button></div>
    <div className="mt-4 space-y-3">{candidates.map((candidate)=>{const work=candidate.sourceSnapshot.normalized??{};return <article className="rounded-lg border border-slate-200 p-4" key={candidate.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h4 className="font-bold text-blue-950">{work.title||"未命名成果"}</h4><p className="mt-1 text-xs text-slate-500">{work.year||"年份未知"} · {work.venue||"Venue 未知"} · {candidate.doi_normalized||candidate.openalex_work_id}</p><p className="mt-2 text-xs text-slate-600">关联成员：{candidate.members.map((item)=>item.name).join("、")||"无"}</p>{candidate.sourceSnapshot.possibleDuplicateResearchItemId?<p className="mt-2 text-xs font-semibold text-amber-700">可能与 {candidate.sourceSnapshot.possibleDuplicateResearchItemId} 重复，请人工确认。</p>:null}</div>{mode==="ignored"?<ConsoleButton disabled={busy} onClick={()=>void run(()=>scholarlyApi.restore(candidate.id),"候选已恢复。") } size="sm" type="button">恢复</ConsoleButton>:<div className="flex flex-wrap gap-2"><ConsoleButton disabled={busy} onClick={()=>void run(()=>scholarlyApi.accept(candidate.id),"论文已接受并创建；请刷新论文库快照。") } size="sm" type="button" variant="primary">接受并创建</ConsoleButton><ConsoleButton disabled={busy} onClick={()=>void run(()=>scholarlyApi.ignore(candidate.id),"候选已忽略。") } size="sm" type="button">忽略</ConsoleButton></div>}</div>{mode==="pending"?<div className="mt-3 flex gap-2"><ConsoleSelect aria-label="合并目标论文" value={merges[candidate.id]??""} onChange={(event)=>setMerges((current)=>({...current,[candidate.id]:event.target.value}))}><option value="">选择已有论文合并…</option>{researchItems.map((item)=><option key={String(item.id)} value={String(item.id)}>{String(item.title?.zh||item.title?.en||item.id||"未命名论文")}</option>)}</ConsoleSelect><ConsoleButton disabled={busy||!merges[candidate.id]} onClick={()=>void run(()=>scholarlyApi.merge(candidate.id,merges[candidate.id]),"候选已绑定到现有论文，展示内容未改变。") } size="sm" type="button">合并</ConsoleButton></div>:null}</article>})}{!candidates.length?<p className="py-3 text-sm text-slate-500">当前没有{mode==="pending"?"待确认":"已忽略"}论文。</p>:null}</div>
  </section>;
}
