"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ConsoleAlert, ConsoleButton, ConsoleConfirmDialog, ConsoleSelect } from "@/features/console/ui";
import { scholarlyApi, type BulkPlan, type BulkResult, type PublicationCandidate, type PublicationSourceCandidate, type PublicationSyncInfo, type ScholarlyStatus } from "./scholarlyApi";

const managedLabels: Record<string, string> = { title_en: "英文标题", year: "年份", venue_en: "英文 Venue", type: "成果类型", doi_link: "DOI 链接", external_links: "外部链接" };

export function usePublicationSyncInfo(id?: string) {
  const [info, setInfo] = useState<PublicationSyncInfo | null>(null);
  const reload = useCallback(async () => { if (!id) { setInfo(null); return; } const result = await scholarlyApi.info(id); setInfo(result.sync); }, [id]);
  useEffect(() => { void reload().catch(() => setInfo(null)); }, [reload]);
  return { info, setInfo, reload };
}

export function PublicationSourceEditor({ researchItemId, info, onChange }: { researchItemId: string; info: PublicationSyncInfo | null; onChange: (value: PublicationSyncInfo) => void }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(""), [sourceCandidates, setSourceCandidates] = useState<PublicationSourceCandidate[]>([]);
  const run = async (operation: () => Promise<{ sync: PublicationSyncInfo }>, success: string) => { setBusy(true); setError(""); try { const result = await operation(); onChange(result.sync); setMessage(success); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } };
  if (!info) return <p className="text-sm text-slate-500">正在加载同步信息…</p>;
  return <div className="space-y-4">
    {error ? <ConsoleAlert title="操作失败" tone="danger">{error}</ConsoleAlert> : null}{message ? <ConsoleAlert title="已更新" tone="success">{message}</ConsoleAlert> : null}
    <dl className="grid gap-3 rounded-lg bg-slate-50 p-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">来源</dt><dd className="font-semibold text-blue-950">{info.source_type === "openalex" ? "OpenAlex 自动同步" : "手工维护"}</dd></div><div><dt className="text-slate-500">来源状态</dt><dd className="font-semibold text-blue-950">{info.decision}</dd></div><div><dt className="text-slate-500">OpenAlex Work ID</dt><dd>{info.openalex_work_id || "尚未绑定"}</dd></div><div><dt className="text-slate-500">DOI</dt><dd>{info.doi_normalized || "未识别"}</dd></div></dl>
    {info.openalex_work_id ? <fieldset><legend className="text-sm font-bold text-blue-950">自动更新字段</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(managedLabels).map(([key, label]) => <label className="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm" key={key}><input checked={info.managed_fields.includes(key)} disabled={busy} onChange={(event) => { const next = event.target.checked ? [...info.managed_fields, key] : info.managed_fields.filter((item) => item !== key); void run(() => scholarlyApi.managedFields(researchItemId, next), "自动更新字段已保存。"); }} type="checkbox"/>{label}</label>)}</div><p className="mt-2 text-xs text-slate-500">手动修改受管理字段并保存论文库后，该字段会自动转为人工维护。Topic、图片与 PDF 始终由人工维护。</p></fieldset> : <><ConsoleButton disabled={busy} onClick={() => { setBusy(true); setError(""); void scholarlyApi.resolveSource(researchItemId).then((result) => { if (result.sync) { onChange(result.sync); setMessage("已按 DOI 绑定外部来源；现有展示内容保持不变。"); } else { setSourceCandidates(result.candidates ?? []); setMessage("该论文没有 DOI，请人工选择 OpenAlex 记录。"); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "查找失败")).finally(() => setBusy(false)); }} type="button">查找外部记录</ConsoleButton>{sourceCandidates.length?<div className="space-y-2"><p className="text-sm font-bold text-blue-950">请选择匹配的 OpenAlex 成果</p>{sourceCandidates.map((candidate)=><article className="flex flex-wrap items-start justify-between gap-3 rounded-lg border border-slate-200 p-3" key={candidate.openalexWorkId}><div><strong className="text-sm text-blue-950">{candidate.title}</strong><p className="mt-1 text-xs text-slate-500">{candidate.year||"年份未知"} · {candidate.venue||"Venue 未知"} · {candidate.doi||candidate.openalexWorkId}</p><p className="mt-1 text-xs text-slate-500">{candidate.authors.join("、")}</p></div><ConsoleButton disabled={busy} onClick={() => { setBusy(true); setError(""); void scholarlyApi.resolveSource(researchItemId,candidate.openalexWorkId).then((result)=>{if(result.sync){onChange(result.sync);setSourceCandidates([]);setMessage("外部来源已绑定；人工展示内容保持不变。")}}).catch((reason)=>setError(reason instanceof Error?reason.message:"绑定失败")).finally(()=>setBusy(false)); }} size="sm" type="button">确认绑定</ConsoleButton></article>)}</div>:null}</>}
  </div>;
}

export function PublicationSyncPanel({ researchItems }: { researchItems: Array<{ id?: unknown; title?: { zh?: unknown; en?: unknown } }> }) {
  const [status, setStatus] = useState<ScholarlyStatus | null>(null), [mode, setMode] = useState<"pending" | "ignored">("pending"), [candidates, setCandidates] = useState<PublicationCandidate[]>([]), [merges, setMerges] = useState<Record<string, string>>({}), [selected, setSelected] = useState<string[]>([]), [plan, setPlan] = useState<BulkPlan | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""), [progress, setProgress] = useState(""), [confirm, setConfirm] = useState<"ignore" | "merge" | null>(null);
  const [memberFilter, setMemberFilter] = useState(""), [yearFilter, setYearFilter] = useState(""), [venueFilter, setVenueFilter] = useState(""), [riskFilter, setRiskFilter] = useState("");
  const load = useCallback(async () => { const [nextStatus, nextCandidates] = await Promise.all([scholarlyApi.status(), scholarlyApi.candidates(mode)]); setStatus(nextStatus); setCandidates(nextCandidates.candidates); }, [mode]);
  useEffect(() => { setSelected([]); setPlan(null); void load().catch((reason) => setError(reason instanceof Error ? reason.message : "无法加载论文同步状态")); }, [load]);
  const run = async (operation: () => Promise<unknown>, success: string) => { setBusy(true); setError(""); setMessage(""); try { await operation(); await load(); setMessage(success); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } };
  const years = useMemo(() => [...new Set(candidates.map((candidate) => candidate.sourceSnapshot.normalized?.year).filter((value): value is number => typeof value === "number"))].sort((a, b) => b - a), [candidates]);
  const venues = useMemo(() => [...new Set(candidates.map((candidate) => candidate.sourceSnapshot.normalized?.venue).filter((value): value is string => Boolean(value)))].sort(), [candidates]);
  const members = useMemo(() => [...new Map(candidates.flatMap((candidate) => candidate.members).map((member) => [member.userId, member])).values()].sort((a, b) => a.name.localeCompare(b.name, "zh-CN")), [candidates]);
  const filtered = useMemo(() => candidates.filter((candidate) => {
    const work = candidate.sourceSnapshot.normalized;
    return (!memberFilter || candidate.members.some((member) => member.userId === memberFilter)) && (!yearFilter || String(work?.year ?? "") === yearFilter) && (!venueFilter || work?.venue === venueFilter) && (!riskFilter || candidate.risk === riskFilter);
  }), [candidates, memberFilter, riskFilter, venueFilter, yearFilter]);
  const selectedSet = useMemo(() => new Set(selected), [selected]);
  const selectedCandidates = candidates.filter((candidate) => selectedSet.has(candidate.id));
  const highConfidenceMerges = selectedCandidates.filter((candidate) => candidate.duplicateSuggestion?.confidence === "high").map((candidate) => ({ workId: candidate.id, researchItemId: candidate.duplicateSuggestion!.researchItemId }));
  const chunks = <T,>(items: T[]) => Array.from({ length: Math.ceil(items.length / 50) }, (_, index) => items.slice(index * 50, index * 50 + 50));
  const executeChunks = async (ids: string[], operation: (chunk: string[]) => Promise<BulkResult>) => {
    const totals = { requested: 0, accepted: 0, ignored: 0, merged: 0, failed: 0, skipped: 0 };
    const batches = chunks(ids);
    for (const [index, batch] of batches.entries()) {
      setProgress(`正在处理第 ${index + 1}/${batches.length} 批（${batch.length} 篇）…`);
      const result = await operation(batch); totals.requested += result.requested; totals.accepted += result.accepted ?? 0; totals.ignored += result.ignored ?? 0; totals.merged += result.merged ?? 0; totals.failed += result.failed; totals.skipped += result.skipped ?? 0;
    }
    return totals;
  };
  const performBatch = async (kind: "accept" | "ignore" | "merge") => {
    setConfirm(null); setBusy(true); setError(""); setMessage(""); setProgress("");
    try {
      let totals;
      if (kind === "merge") {
        const batches = chunks(highConfidenceMerges); totals = { requested: 0, accepted: 0, ignored: 0, merged: 0, failed: 0, skipped: 0 };
        for (const [index, batch] of batches.entries()) { setProgress(`正在合并第 ${index + 1}/${batches.length} 批（${batch.length} 篇）…`); const result = await scholarlyApi.bulkMerge(batch); totals.requested += result.requested; totals.merged += result.merged ?? 0; totals.failed += result.failed; }
      } else totals = await executeChunks(selected, kind === "accept" ? scholarlyApi.bulkAccept : scholarlyApi.bulkIgnore);
      await load(); setSelected([]); setPlan(null); setMessage(`批量操作完成：处理 ${totals.requested} 篇，接收 ${totals.accepted}，合并 ${totals.merged}，忽略 ${totals.ignored}，跳过 ${totals.skipped}，失败 ${totals.failed}。`);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "批量操作失败，可保留选择后重试"); } finally { setBusy(false); setProgress(""); }
  };
  const makePlan = async () => {
    setBusy(true); setError(""); setMessage(""); setPlan(null);
    try {
      const combined: BulkPlan = { requested: 0, counts: { safe_accept: 0, suggested_merge: 0, already_accepted: 0, needs_review: 0, conflict: 0 }, items: [] };
      for (const [index, batch] of chunks(selected).entries()) { setProgress(`正在分析第 ${index + 1}/${Math.ceil(selected.length / 50)} 批…`); const result = await scholarlyApi.bulkPlan(batch); combined.requested += result.requested; combined.items.push(...result.items); for (const key of Object.keys(combined.counts) as Array<keyof BulkPlan["counts"]>) combined.counts[key] += result.counts[key]; }
      setPlan(combined);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "无法生成整理计划"); } finally { setBusy(false); setProgress(""); }
  };
  const openAlex = status?.providers?.openAlex;
  const healthLabel: Record<string, string> = { healthy: "连接正常", key_missing: "未配置 Key", auth_error: "鉴权失败", budget_exhausted: "今日额度已用尽", rate_limited: "请求频率受限", timeout: "请求超时", provider_error: "服务异常", unknown: "尚未检测" };
  const healthColor: Record<string, string> = { healthy: "bg-emerald-500", key_missing: "bg-amber-500", auth_error: "bg-red-500", budget_exhausted: "bg-red-500", rate_limited: "bg-amber-500", timeout: "bg-amber-500", provider_error: "bg-red-500", unknown: "bg-slate-400" };
  return <section className="mb-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-700">Scholarly Sync</p><h3 className="mt-1 text-lg font-bold text-blue-950">论文自动同步</h3><p className="mt-1 text-sm text-slate-500">OpenAlex 发现 · Crossref DOI 校准 · 人工展示优先</p></div><ConsoleButton disabled={busy || !status?.enabled} onClick={() => void run(scholarlyApi.syncAll, "全体成员同步完成；若产生公开变更，请刷新论文库快照。") } type="button" variant="primary">同步全部</ConsoleButton></div>
    {error ? <div className="mt-4"><ConsoleAlert title="同步服务异常" tone="danger">{error}</ConsoleAlert></div> : null}{message ? <div className="mt-4"><ConsoleAlert title="操作完成" tone="success">{message}</ConsoleAlert></div> : null}
    {status ? <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1.5fr)_repeat(3,minmax(8rem,.6fr))]"><div className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs font-bold text-slate-500"><span className={`size-2 rounded-full ${healthColor[openAlex?.health ?? "unknown"]}`}/>OpenAlex 服务状态</p><p className="mt-1 text-sm font-bold text-blue-950">{healthLabel[openAlex?.health ?? "unknown"]}</p><p className="mt-1 text-xs text-slate-500">{openAlex?.message ?? "状态尚未加载"}</p></div><ConsoleButton disabled={busy} onClick={() => void run(scholarlyApi.checkOpenAlex, "OpenAlex 状态已重新检测。") } size="sm" type="button">检测状态</ConsoleButton></div><dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 border-t border-slate-100 pt-3 text-xs"><div><dt className="text-slate-500">Key</dt><dd className="font-semibold">{openAlex?.configured ? "已配置" : "未配置"}</dd></div><div><dt className="text-slate-500">剩余额度</dt><dd className="font-semibold">{openAlex?.rateLimit.remaining ?? "—"}{openAlex?.rateLimit.limit != null ? ` / ${openAlex.rateLimit.limit}` : ""}</dd></div><div><dt className="text-slate-500">本次消耗</dt><dd className="font-semibold">{openAlex?.rateLimit.creditsUsed ?? "—"}</dd></div><div><dt className="text-slate-500">额度重置</dt><dd className="font-semibold">{openAlex?.rateLimit.resetAt ? new Date(openAlex.rateLimit.resetAt).toLocaleString("zh-CN") : "—"}</dd></div><div><dt className="text-slate-500">检测时间</dt><dd className="font-semibold">{openAlex?.checkedAt ? new Date(openAlex.checkedAt).toLocaleString("zh-CN") : "—"}</dd></div><div><dt className="text-slate-500">最近成功</dt><dd className="font-semibold">{openAlex?.lastSuccessAt ? new Date(openAlex.lastSuccessAt).toLocaleString("zh-CN") : "—"}</dd></div></dl></div>{[["Crossref",status.providers?.crossref?.configured?"Polite 模式":"未配置邮箱"],["已验证成员",String(status.profiles?.verified??0)],["待确认",String(status.pending??0)]].map(([label,value])=><div className="rounded-lg bg-slate-50 p-3" key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-blue-950">{value}</p></div>)}</div> : null}
    <div className="mt-5 flex gap-1 border-b border-slate-200"><button className={`px-3 py-2 text-sm font-semibold ${mode==="pending"?"border-b-2 border-cyan-700 text-cyan-800":"text-slate-500"}`} onClick={()=>setMode("pending")} type="button">待确认 {status?.pending??0}</button><button className={`px-3 py-2 text-sm font-semibold ${mode==="ignored"?"border-b-2 border-cyan-700 text-cyan-800":"text-slate-500"}`} onClick={()=>setMode("ignored")} type="button">已忽略 {status?.ignored??0}</button></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><ConsoleSelect aria-label="按成员筛选" value={memberFilter} onChange={(event)=>setMemberFilter(event.target.value)}><option value="">全部成员</option>{members.map((member)=><option key={member.userId} value={member.userId}>{member.name}</option>)}</ConsoleSelect><ConsoleSelect aria-label="按年份筛选" value={yearFilter} onChange={(event)=>setYearFilter(event.target.value)}><option value="">全部年份</option>{years.map((year)=><option key={year}>{year}</option>)}</ConsoleSelect><ConsoleSelect aria-label="按期刊筛选" value={venueFilter} onChange={(event)=>setVenueFilter(event.target.value)}><option value="">全部期刊 / 会议</option>{venues.map((venue)=><option key={venue}>{venue}</option>)}</ConsoleSelect><ConsoleSelect aria-label="按风险筛选" value={riskFilter} onChange={(event)=>setRiskFilter(event.target.value)}><option value="">全部风险</option><option value="safe">可安全接收</option><option value="high_confidence_duplicate">高置信重复</option><option value="possible_duplicate">疑似重复</option></ConsoleSelect></div>
    <div className="mt-3 flex flex-wrap items-center gap-2 border-y border-slate-100 py-3"><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input checked={filtered.length>0&&filtered.every((candidate)=>selectedSet.has(candidate.id))} onChange={(event)=>setSelected((current)=>event.target.checked?[...new Set([...current,...filtered.map((candidate)=>candidate.id)])]:current.filter((id)=>!filtered.some((candidate)=>candidate.id===id)))} type="checkbox"/>选择当前筛选结果</label><span className="mr-auto text-xs text-slate-500">已选 {selected.length} / 当前显示 {filtered.length}</span>{mode==="pending"?<><ConsoleButton disabled={busy||!selected.length} onClick={()=>void makePlan()} size="sm" type="button">智能整理</ConsoleButton><ConsoleButton disabled={busy||!selected.length} onClick={()=>void performBatch("accept")} size="sm" type="button" variant="primary">安全接收</ConsoleButton><ConsoleButton disabled={busy||!highConfidenceMerges.length} onClick={()=>setConfirm("merge")} size="sm" type="button">合并高置信项</ConsoleButton><ConsoleButton disabled={busy||!selected.length} onClick={()=>setConfirm("ignore")} size="sm" type="button" variant="danger">批量忽略</ConsoleButton></>:null}</div>
    {progress?<p aria-live="polite" className="mt-3 text-sm font-semibold text-cyan-800">{progress}</p>:null}
    {plan?<div className="mt-3 rounded-lg border border-cyan-200 bg-cyan-50 p-4"><p className="text-sm font-bold text-blue-950">智能整理预览（{plan.requested} 篇）</p><p className="mt-1 text-sm text-cyan-950">可安全接收 {plan.counts.safe_accept} · 建议合并 {plan.counts.suggested_merge} · 已接收 {plan.counts.already_accepted} · 需复核 {plan.counts.needs_review} · 冲突 {plan.counts.conflict}</p><p className="mt-2 text-xs text-cyan-900">“安全接收”只处理无重复提示的候选；建议合并和冲突项始终保留人工确认。</p></div>:null}
    <div className="mt-4 space-y-3">{filtered.map((candidate)=>{const work=candidate.sourceSnapshot.normalized??{};const suggestion=candidate.duplicateSuggestion;return <article className={`rounded-lg border bg-white p-4 ${selectedSet.has(candidate.id)?"border-cyan-400 ring-1 ring-cyan-200":"border-slate-200"}`} key={candidate.id}><div className="flex items-start gap-3"><input aria-label={`选择 ${work.title||"未命名成果"}`} checked={selectedSet.has(candidate.id)} className="mt-1" onChange={(event)=>setSelected((current)=>event.target.checked?[...current,candidate.id]:current.filter((id)=>id!==candidate.id))} type="checkbox"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h4 className="font-bold text-blue-950">{work.title||"未命名成果"}</h4><p className="mt-1 text-xs text-blue-700">{work.year||"年份未知"} · {work.venue||"Venue 未知"} · {candidate.doi_normalized||candidate.openalex_work_id}</p><p className="mt-2 text-xs text-blue-800">关联成员：{candidate.members.map((item)=>item.name).join("、")||"无"}</p>{suggestion?<div className="mt-2 rounded-md bg-amber-50 p-2 text-xs text-amber-900"><b>{suggestion.confidence==="high"?"高置信合并建议":"疑似重复"}</b>：{suggestion.title}（{suggestion.year??"年份未知"}）{suggestion.authorOverlap?` · ${suggestion.authorOverlap} 位作者重合`:" · 暂无作者重合"}</div>:null}</div>{mode==="ignored"?<ConsoleButton disabled={busy} onClick={()=>void run(()=>scholarlyApi.restore(candidate.id),"候选已恢复。") } size="sm" type="button">恢复</ConsoleButton>:<div className="flex flex-wrap gap-2"><ConsoleButton disabled={busy||Boolean(suggestion)} onClick={()=>void run(()=>scholarlyApi.accept(candidate.id),"论文已接受并创建；请刷新论文库快照。") } size="sm" type="button" variant="primary">接受并创建</ConsoleButton><ConsoleButton disabled={busy} onClick={()=>void run(()=>scholarlyApi.ignore(candidate.id),"候选已忽略。") } size="sm" type="button">忽略</ConsoleButton></div>}</div>{mode==="pending"?<div className="mt-3 flex flex-wrap gap-2"><ConsoleSelect aria-label="合并目标论文" className="min-w-64 flex-1" value={merges[candidate.id]??suggestion?.researchItemId??""} onChange={(event)=>setMerges((current)=>({...current,[candidate.id]:event.target.value}))}><option value="">选择其他论文…</option>{researchItems.map((item)=><option key={String(item.id)} value={String(item.id)}>{String(item.title?.zh||item.title?.en||item.id||"未命名论文")}</option>)}</ConsoleSelect><ConsoleButton disabled={busy||!(merges[candidate.id]||suggestion?.researchItemId)} onClick={()=>void run(()=>scholarlyApi.merge(candidate.id,merges[candidate.id]||suggestion!.researchItemId),"候选已绑定到现有论文，展示内容未改变。") } size="sm" type="button">{suggestion?.confidence==="high"?"采用建议并合并":"确认合并"}</ConsoleButton></div>:null}</div></div></article>})}{!filtered.length?<p className="py-3 text-sm text-blue-700">当前筛选条件下没有{mode==="pending"?"待确认":"已忽略"}论文。</p>:null}</div>
    <ConsoleConfirmDialog danger description={`将忽略已选择的 ${selected.length} 篇候选。操作会逐篇提交并保留审计记录，可在“已忽略”中恢复。`} onClose={()=>setConfirm(null)} onConfirm={()=>void performBatch("ignore")} open={confirm==="ignore"} title="批量忽略这些候选？" confirmLabel="确认忽略"/>
    <ConsoleConfirmDialog description={`将把 ${highConfidenceMerges.length} 篇高置信候选分别绑定到建议论文。现有论文展示内容不会被覆盖，请确认标题、年份和作者重合信息无误。`} onClose={()=>setConfirm(null)} onConfirm={()=>void performBatch("merge")} open={confirm==="merge"} title="采用高置信合并建议？" confirmLabel="确认合并"/>
  </section>;
}
