"use client";
import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
import { consoleApi } from "@/lib/consoleApi";
import { ConsoleDrawer } from "./ConsoleOverlay";
import { ConsoleSearchInput } from "./ConsoleFormControls";
import { ConsoleEmptyState } from "./ConsoleEmptyState";
import { ConsoleIcon } from "./ConsoleIcon";
import { ConsoleButton } from "./ConsoleButton";

type MediaOption = { id: string; filename: string; url: string; mimeType: string };
export function MediaPicker({ open, onClose, onSelect, accept = "image" }: { open: boolean; onClose: () => void; onSelect: (asset: MediaOption) => void; accept?: "image" | "all" }) {
  const [items, setItems] = useState<MediaOption[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [selected, setSelected] = useState<MediaOption | null>(null); const [uploading, setUploading] = useState(false);
  const load = useCallback(async () => { if (!open) return; try { setError(""); const data = await consoleApi<{ assets: MediaOption[] }>(`/api/media?status=active&search=${encodeURIComponent(search)}`); setItems(accept === "image" ? data.assets.filter((item) => item.mimeType.startsWith("image/")) : data.assets); } catch (cause) { setError((cause as Error).message); } }, [accept, open, search]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 150); return () => window.clearTimeout(timer); }, [load]);
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(""); try { const body = new FormData(); body.append("file", file); const asset = await consoleApi<MediaOption>("/api/media/upload", { method: "POST", body }); setItems((current) => [asset, ...current.filter((item) => item.id !== asset.id)]); setSelected(asset); } catch (cause) { setError((cause as Error).message); } finally { setUploading(false); event.target.value = ""; } }
  return <ConsoleDrawer onClose={onClose} open={open} title="选择媒体资源"><div className="flex gap-2"><div className="min-w-0 flex-1"><ConsoleSearchInput aria-label="搜索媒体资源" onChange={(event) => setSearch(event.target.value)} placeholder="搜索文件名" value={search}/></div><label className={`inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-xs font-semibold text-slate-700 shadow-sm hover:bg-slate-50 ${uploading ? "pointer-events-none opacity-50" : ""}`}><ConsoleIcon name="upload"/>{uploading ? "上传中…" : "上传"}<input accept={accept === "image" ? "image/jpeg,image/png,image/webp" : "image/jpeg,image/png,image/webp,application/pdf"} className="sr-only" disabled={uploading} onChange={upload} type="file"/></label></div>{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}{items.length ? <div className="mt-4 grid grid-cols-2 gap-3">{items.map((item) => <button aria-pressed={selected?.id === item.id} className={`overflow-hidden rounded-xl border bg-white text-left ${selected?.id === item.id ? "border-cyan-600 ring-2 ring-cyan-100" : "border-slate-200 hover:border-cyan-500"}`} key={item.id} onClick={() => setSelected(item)}><span className="relative grid aspect-[4/3] place-items-center overflow-hidden bg-slate-50">{item.mimeType.startsWith("image/") ? <Image alt="" className="object-cover" fill sizes="180px" src={item.url} unoptimized/> : <ConsoleIcon className="size-8 text-slate-400" name="media"/>}</span><span className="block truncate p-2.5 text-xs font-semibold text-slate-800">{item.filename}</span></button>)}</div> : <div className="mt-4"><ConsoleEmptyState description="上传资源后即可在这里选择。" title="没有可用资源"/></div>}<div className="sticky -bottom-5 mt-5 border-t border-slate-200 bg-white py-4"><p className="mb-3 truncate text-xs text-slate-500">已选择：{selected?.filename || "尚未选择"}</p><div className="flex justify-end gap-2"><ConsoleButton onClick={onClose}>取消</ConsoleButton><ConsoleButton disabled={!selected} onClick={() => { if (selected) { onSelect(selected); onClose(); } }} variant="primary">使用所选资源</ConsoleButton></div></div></ConsoleDrawer>;
}
