import assert from "node:assert/strict";
import test from "node:test";
import {applyRevision,canWriteLabAssets,filterAssets,groupAssets,groupAssetsByType,labAssetsRedirects,normalizeLabAssetsSnapshot} from "./model.ts";

test("legacy lab assets route permanently redirects into the console",()=>{assert.deepEqual(labAssetsRedirects,[{source:"/lab-assets",destination:"/console/lab-assets",permanent:true}])});
const rawSnapshot={revision:"7",page:{},stats:{totalAssets:3,totalPlatforms:1},platformTypes:[{code:"robot",name:"机器人",platforms:[{code:"DOG-2",typeCode:"robot",name:{zh:"机器狗",en:"Robot dog"},description:{zh:"四足",en:"Quadruped"},status:"active",assetCodes:["CAM-1"]}]}],platforms:[{code:"DOG-2",typeCode:"robot",name:{zh:"机器狗",en:"Robot dog"},description:{zh:"四足",en:"Quadruped"},status:"active",assetCodes:["CAM-1"]}],deviceTypes:[{code:"camera",name:"相机"},{code:"lidar",name:"雷达"}],members:[{id:"user-1",username:"alice",displayName:"张三"}],usageRequests:[],assets:[{code:"CAM-1",deviceTypeCode:"camera",deviceTypeName:"相机",model:"D455",name:{zh:"前置相机",en:"Front camera"},description:{zh:"已标定",en:"Calibrated"},vendorSerial:"SN-1",status:"mounted",currentPlatformCode:"DOG-2",assignedUserId:null,assignedUserName:"",borrowerName:"",borrowerContact:"",storageLocation:"507-A 柜 3 层",updatedAt:"2026-09-12T12:00:00.000Z"},{code:"LIDAR-2",deviceTypeCode:"lidar",deviceTypeName:"雷达",model:"M1",name:{zh:"雷达 2",en:"Lidar 2"},description:{zh:"",en:""},vendorSerial:"",status:"in_use",currentPlatformCode:null,assignedUserId:"user-1",assignedUserName:"张三",borrowerName:"",borrowerContact:"",storageLocation:"507 实验室",updatedAt:"2026-09-12T12:00:00.000Z"},{code:"LIDAR-10",deviceTypeCode:"lidar",deviceTypeName:"雷达",model:"M2",name:{zh:"雷达 10",en:"Lidar 10"},description:{zh:"外借",en:""},vendorSerial:"",status:"lend",currentPlatformCode:null,assignedUserId:null,assignedUserName:"",borrowerName:"李四",borrowerContact:"13800000000",storageLocation:null,updatedAt:"2026-09-12T12:00:00.000Z"}]};

test("normalizes the typed asset snapshot and direct platform composition",()=>{const snapshot=normalizeLabAssetsSnapshot(rawSnapshot);assert.equal(snapshot.revision,"7");assert.equal(snapshot.platforms[0].code,"DOG-2");assert.deepEqual(snapshot.platforms[0].assetCodes,["CAM-1"]);assert.equal(snapshot.assets[1].assignedUserName,"张三")});
test("filters assets by relationship text, type, status, platform, and location",()=>{const snapshot=normalizeLabAssetsSnapshot(rawSnapshot);assert.deepEqual(filterAssets(snapshot.assets,{deviceType:"camera",location:"507-A 柜 3 层",platform:"DOG-2",query:"d455",status:"mounted"}).map((item)=>item.code),["CAM-1"]);assert.deepEqual(filterAssets(snapshot.assets,{deviceType:"all",location:"all",platform:"unassigned",query:"张三",status:"all"}).map((item)=>item.code),["LIDAR-2"]);assert.deepEqual(filterAssets(snapshot.assets,{deviceType:"all",location:"unassigned",platform:"all",query:"李四",status:"lend"}).map((item)=>item.code),["LIDAR-10"])});
test("groups assets by device type and naturally sorts their codes",()=>{const snapshot=normalizeLabAssetsSnapshot(rawSnapshot);const groups=groupAssetsByType(snapshot.assets);assert.deepEqual(groups.map((group)=>group.name),["雷达","相机"]);assert.deepEqual(groups[0].items.map((item)=>item.code),["LIDAR-2","LIDAR-10"])});
test("groups assets by platform, storage location, and status",()=>{const assets=normalizeLabAssetsSnapshot(rawSnapshot).assets;assert.ok(groupAssets(assets,"platform").some((group)=>group.name==="未分配平台"));assert.ok(groupAssets(assets,"location").some((group)=>group.name==="未填写位置"));assert.ok(groupAssets(assets,"status").some((group)=>group.name==="使用中"));});
test("write controls and revision updates remain permission and revision based",()=>{assert.equal(canWriteLabAssets(["lab_assets.read"]),false);assert.equal(canWriteLabAssets(["lab_assets.write"]),true);const snapshot=normalizeLabAssetsSnapshot(rawSnapshot);assert.equal(applyRevision(snapshot,"8").revision,"8");assert.equal(snapshot.revision,"7")});
test("rejects malformed snapshots",()=>{assert.throws(()=>normalizeLabAssetsSnapshot({revision:1,assets:[]}),/数据格式/)});
