export type LocalizedText={en:string;zh:string};
export type LabSpec={key:string;label:LocalizedText;value:LocalizedText;unit:string;publicVisible:boolean;sortOrder:number};
export type LabDeviceType={code:string;name:string;specDefinitions:Array<{key:string;label:LocalizedText;unit:string;sortOrder:number}>};
export type LabPlatformType={code:string;name:string;platforms:LabPlatform[];slots:Array<{slotKey:string;name:LocalizedText;deviceTypeCode:string|null;required:boolean;minCount:number;maxCount:number|null;sortOrder:number}>};
export type LabMember={id:string;username:string;displayName:string};
export type LabPlatform={assetCodes:string[];code:string;description:LocalizedText;name:LocalizedText;status:"active"|"maintenance"|"building"|"lend"|"retired";typeCode:string;location:string|null;maintainerUserId:string|null;maintainerName:string;commissionedAt:string;specs:LabSpec[];publicProfile:{publicVisible:boolean;title:LocalizedText;description:LocalizedText;imageAssetId:string|null;imageUrl:string|null;tags:string[];componentDisplayMode:"none"|"summary"|"detail";sortOrder:number}};
export type LabAsset={code:string;currentPlatformCode:string|null;description:LocalizedText;deviceTypeCode:string;deviceTypeName:string;manufacturer:string;model:string;name:LocalizedText;vendorSerial:string;status:"idle"|"in_use"|"mounted"|"maintenance"|"lend"|"retired";condition:"normal"|"maintenance"|"retired";displayState:"idle"|"in_use"|"mounted"|"maintenance"|"lend"|"retired";platformRole:LocalizedText;platformSlot:string|null;platformSortOrder:number;mountedAt:string|null;assignedUserId:string|null;assignedUserName:string;borrowerName:string;borrowerContact:string;storageLocation:string|null;updatedAt:string;specs:LabSpec[];publicProfile:{publicVisible:boolean;title:LocalizedText;description:LocalizedText;imageAssetId:string|null;imageUrl:string|null;sortOrder:number}};
export type LabUsageRequest={id:string;status:"pending"|"approved"|"rejected"|"cancelled";reason:string;reviewNote:string;createdAt:string;reviewedAt:string|null;assetCode:string;assetName:LocalizedText;requesterId:string;requesterName:string;reviewerName:string};
export type LabAssetsSnapshot={assets:LabAsset[];deviceTypes:LabDeviceType[];members:LabMember[];page:Record<string,unknown>;platforms:LabPlatform[];platformTypes:LabPlatformType[];revision:string;stats:Record<string,number>;usageRequests:LabUsageRequest[]};
export type AssetFilters={deviceType:string;location:string;platform:string;query:string;status:string};
export type AssetGroupBy="deviceType"|"platform"|"location"|"status";
export const labAssetsRedirects=[{source:"/lab-assets",destination:"/console/lab-assets",permanent:true}];

function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("实验室资产数据格式无效。");return value as Record<string,unknown>}
function localized(value:unknown):LocalizedText{const item=object(value);if(typeof item.zh!=="string"||typeof item.en!=="string")throw new Error("实验室资产数据格式无效。");return{zh:item.zh,en:item.en}}
function strings(value:unknown){if(!Array.isArray(value)||value.some((item)=>typeof item!=="string"))throw new Error("实验室资产数据格式无效。");return value as string[]}
function specs(value:unknown):LabSpec[]{return Array.isArray(value)?value.map((entry)=>{const item=object(entry);return{key:String(item.key??""),label:localized(item.label),value:localized(item.value),unit:String(item.unit??""),publicVisible:Boolean(item.publicVisible),sortOrder:Number(item.sortOrder??0)}}):[]}
function platform(value:unknown):LabPlatform{const item=object(value);if(typeof item.code!=="string"||typeof item.typeCode!=="string"||typeof item.status!=="string")throw new Error("实验室资产数据格式无效。");const profile=object(item.publicProfile??{});return{assetCodes:strings(item.assetCodes),code:item.code,description:localized(item.description),name:localized(item.name),status:item.status as LabPlatform["status"],typeCode:item.typeCode,location:typeof item.location==="string"?item.location:null,maintainerUserId:typeof item.maintainerUserId==="string"?item.maintainerUserId:null,maintainerName:String(item.maintainerName??""),commissionedAt:String(item.commissionedAt??""),specs:specs(item.specs),publicProfile:{publicVisible:Boolean(profile.publicVisible),title:localized(profile.title??{zh:"",en:""}),description:localized(profile.description??{zh:"",en:""}),imageAssetId:typeof profile.imageAssetId==="string"?profile.imageAssetId:null,imageUrl:typeof profile.imageUrl==="string"?profile.imageUrl:null,tags:Array.isArray(profile.tags)?profile.tags.map(String):[],componentDisplayMode:(profile.componentDisplayMode??"summary") as LabPlatform["publicProfile"]["componentDisplayMode"],sortOrder:Number(profile.sortOrder??0)}}}
function asset(value:unknown):LabAsset{const item=object(value);if(typeof item.code!=="string"||typeof item.deviceTypeCode!=="string"||typeof item.deviceTypeName!=="string"||typeof item.model!=="string"||typeof item.vendorSerial!=="string"||typeof item.status!=="string")throw new Error("实验室资产数据格式无效。");const profile=object(item.publicProfile??{});return{code:item.code,currentPlatformCode:typeof item.currentPlatformCode==="string"?item.currentPlatformCode:null,description:localized(item.description),deviceTypeCode:item.deviceTypeCode,deviceTypeName:item.deviceTypeName,manufacturer:String(item.manufacturer??""),model:item.model,name:localized(item.name),vendorSerial:item.vendorSerial,status:item.status as LabAsset["status"],condition:(item.condition??(item.status==="maintenance"?"maintenance":item.status==="retired"?"retired":"normal")) as LabAsset["condition"],displayState:(item.displayState??item.status) as LabAsset["displayState"],platformRole:localized(item.platformRole??{zh:"",en:""}),platformSlot:typeof item.platformSlot==="string"?item.platformSlot:null,platformSortOrder:Number(item.platformSortOrder??0),mountedAt:item.mountedAt?String(item.mountedAt):null,assignedUserId:typeof item.assignedUserId==="string"?item.assignedUserId:null,assignedUserName:typeof item.assignedUserName==="string"?item.assignedUserName:"",borrowerName:typeof item.borrowerName==="string"?item.borrowerName:"",borrowerContact:typeof item.borrowerContact==="string"?item.borrowerContact:"",storageLocation:typeof item.storageLocation==="string"?item.storageLocation:null,updatedAt:typeof item.updatedAt==="string"?item.updatedAt:"",specs:specs(item.specs),publicProfile:{publicVisible:Boolean(profile.publicVisible),title:localized(profile.title??{zh:"",en:""}),description:localized(profile.description??{zh:"",en:""}),imageAssetId:typeof profile.imageAssetId==="string"?profile.imageAssetId:null,imageUrl:typeof profile.imageUrl==="string"?profile.imageUrl:null,sortOrder:Number(profile.sortOrder??0)}}}
function usageRequest(value:unknown):LabUsageRequest{const item=object(value);if(typeof item.id!=="string"||typeof item.status!=="string"||typeof item.assetCode!=="string"||typeof item.requesterId!=="string")throw new Error("实验室资产数据格式无效。");return{id:item.id,status:item.status as LabUsageRequest["status"],reason:typeof item.reason==="string"?item.reason:"",reviewNote:typeof item.reviewNote==="string"?item.reviewNote:"",createdAt:String(item.createdAt??""),reviewedAt:item.reviewedAt?String(item.reviewedAt):null,assetCode:item.assetCode,assetName:localized(item.assetName),requesterId:item.requesterId,requesterName:String(item.requesterName??""),reviewerName:String(item.reviewerName??"")}}

export function normalizeLabAssetsSnapshot(value:unknown):LabAssetsSnapshot{const item=object(value);if(typeof item.revision!=="string"||!Array.isArray(item.assets)||!Array.isArray(item.platforms)||!Array.isArray(item.platformTypes)||!Array.isArray(item.deviceTypes)||!Array.isArray(item.members)||!Array.isArray(item.usageRequests))throw new Error("实验室资产数据格式无效。");const statsValue=object(item.stats);return{assets:item.assets.map(asset),deviceTypes:item.deviceTypes.map((entry)=>{const row=object(entry);if(typeof row.code!=="string"||typeof row.name!=="string")throw new Error("实验室资产数据格式无效。");return{code:row.code,name:row.name,specDefinitions:Array.isArray(row.specDefinitions)?row.specDefinitions.map((definition)=>{const value=object(definition);return{key:String(value.key??""),label:localized(value.label),unit:String(value.unit??""),sortOrder:Number(value.sortOrder??0)}}):[]}}),members:item.members.map((entry)=>{const row=object(entry);if(typeof row.id!=="string"||typeof row.username!=="string"||typeof row.displayName!=="string")throw new Error("实验室资产数据格式无效。");return{id:row.id,username:row.username,displayName:row.displayName}}),page:object(item.page),platforms:item.platforms.map(platform),platformTypes:item.platformTypes.map((entry)=>{const row=object(entry);if(typeof row.code!=="string"||typeof row.name!=="string"||!Array.isArray(row.platforms))throw new Error("实验室资产数据格式无效。");return{code:row.code,name:row.name,slots:Array.isArray(row.slots)?row.slots.map((slot)=>{const value=object(slot);return{slotKey:String(value.slotKey??""),name:localized(value.name),deviceTypeCode:typeof value.deviceTypeCode==="string"?value.deviceTypeCode:null,required:Boolean(value.required),minCount:Number(value.minCount??0),maxCount:typeof value.maxCount==="number"?value.maxCount:null,sortOrder:Number(value.sortOrder??0)}}):[],platforms:row.platforms.map(platform)}}),revision:item.revision,stats:Object.fromEntries(Object.entries(statsValue).filter((entry):entry is[string,number]=>typeof entry[1]==="number")),usageRequests:item.usageRequests.map(usageRequest)};}
export function canWriteLabAssets(permissions:string[]){return permissions.includes("lab_assets.write")}
export function applyRevision(snapshot:LabAssetsSnapshot,revision:string):LabAssetsSnapshot{return{...snapshot,revision}}
export function filterAssets(assets:LabAsset[],filters:AssetFilters){const query=filters.query.trim().toLocaleLowerCase();return assets.filter((item)=>{const matchesStatus=filters.status==="all"||item.displayState===filters.status;const matchesType=filters.deviceType==="all"||item.deviceTypeCode===filters.deviceType;const matchesLocation=filters.location==="all"||(filters.location==="unassigned"?!item.storageLocation:item.storageLocation===filters.location);const matchesPlatform=filters.platform==="all"||(filters.platform==="unassigned"?!item.currentPlatformCode:item.currentPlatformCode===filters.platform);const haystack=[item.code,item.manufacturer,item.model,item.vendorSerial,item.name.zh,item.name.en,item.deviceTypeName,item.description.zh,item.description.en,item.currentPlatformCode??"",item.storageLocation??"",item.assignedUserName,item.borrowerName].join(" ").toLocaleLowerCase();return matchesStatus&&matchesType&&matchesLocation&&matchesPlatform&&(!query||haystack.includes(query))})}
export function groupAssetsByType(assets:LabAsset[]){const groups=new Map<string,LabAsset[]>();for(const item of assets){const group=groups.get(item.deviceTypeName)??[];group.push(item);groups.set(item.deviceTypeName,group)}return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b,"zh-CN",{numeric:true})).map(([name,items])=>({name,items:[...items].sort((a,b)=>a.code.localeCompare(b.code,"zh-CN",{numeric:true}))}))}
export function groupAssets(assets:LabAsset[],groupBy:AssetGroupBy){const labels:Record<LabAsset["displayState"],string>={idle:"闲置",in_use:"使用中",mounted:"已装载",maintenance:"维护中",lend:"借出",retired:"报废"};const groups=new Map<string,LabAsset[]>();for(const item of assets){const name=groupBy==="deviceType"?item.deviceTypeName:groupBy==="platform"?(item.currentPlatformCode??"未分配平台"):groupBy==="location"?(item.storageLocation??"未填写位置"):labels[item.displayState];const group=groups.get(name)??[];group.push(item);groups.set(name,group)}return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b,"zh-CN",{numeric:true})).map(([name,items])=>({name,items:[...items].sort((a,b)=>a.code.localeCompare(b.code,"zh-CN",{numeric:true}))}))}
